### PR TITLE
[angular] Fix infinite scroll sort if search is done 

### LINKED ISSUE #14138: Sorting entities does not work after searching for them
##### **Overview of the issue**

I'm using elasticsearch along with infinite-scroll and entities are not sortable after searching for them. I'd like to be able to sort the results of a search using the column names. When you view all the entities sorting works fine. It seems like clicking on the column names doesn't do anything and the callback on the jhiSort element is never called.

##### **Motivation for or Use Case**

I'd like to be able to sort the results of a search using the column names. 

##### **Reproduce the error**

You can see the issue when running the app using the attached JDL. If you go to the Phones entities and attempt to search for something, the table with the returned results isn't sortable.

##### **JHipster Version(s)**

6.10.5
##### .yo-rc.json

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.10.5",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "NDRkMmM4ZTBjMGQyZTNhNTA1YzEzZTc4ZmJjOWNjYzA3ZGI1M2QzMWQ2MzAzNjhjOTVhNDhlNzI1ZGI4NjQ0YTVkODIyMTc3MzEyYTFhZGE2YmM3NmYxY2U1ZDk5ZGNjOTQ2ZTRiODc0OTViNWI2NmYzNTRkNzAyYjhkNmI4NDI=",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1614709658487,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": [],
    "lastLiquibaseTimestamp": 1614710055000
  }
}
```

##### JDL file to recreate issue

```
application {
  config {
    applicationType monolith
    authenticationType jwt
    baseName jhipster
    blueprints []
    buildTool maven
    cacheProvider ehcache
    clientFramework angularX
    clientPackageManager npm
    clientTheme none
    creationTimestamp 1614709658487
    databaseType sql
    devDatabaseType h2Disk
    dtoSuffix DTO
    embeddableLaunchScript false
    enableHibernateCache true
    enableSwaggerCodegen true
    enableTranslation false
    jhiPrefix jhi
    jhipsterVersion "6.10.5"
    jwtSecretKey "NDRkMmM4ZTBjMGQyZTNhNTA1YzEzZTc4ZmJjOWNjYzA3ZGI1M2QzMWQ2MzAzNjhjOTVhNDhlNzI1ZGI4NjQ0YTVkODIyMTc3MzEyYTFhZGE2YmM3NmYxY2U1ZDk5ZGNjOTQ2ZTRiODc0OTViNWI2NmYzNTRkNzAyYjhkNmI4NDI="
    languages [en, fr]
    messageBroker false
    nativeLanguage en
    otherModules []
    packageName com.mycompany.myapp
    prodDatabaseType postgresql
    searchEngine elasticsearch
    serverPort 8080
    serviceDiscoveryType false
    skipClient false
    skipServer false
    skipUserManagement false
    testFrameworks []
    useSass true
    websocket false
  }

  entities Phones
}

entity Phones {
  name String,
  version String
}
paginate Phones with infinite-scroll
search Phones with elasticsearch

```

##### **Browsers and Operating System**

All browsers

- [ x ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by kaidohallik**
Fix #14138

As by default Elasticsearch can order by `numeric`, `boolean` and `datetime` fields then allowing to sort only by those fields after searching.

The second commit increases test coverage of the changed sort directive.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Comment by kaidohallik** [comment]
As binding callback function is hack then replaced this with standard Angular Output event.

File: generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs [hunk 1]
```diff
@@ -16,6 +16,12 @@
  See the License for the specific language governing permissions and
  limitations under the License.
 -%>
+<%_
+  const notSortableFieldsAfterSearch = !searchEngine ? '' : fields
+      .filter(field => !field.hidden && !field.fieldTypeBoolean && !field.fieldTypeNumeric && !field.fieldTypeTemporal)
+      .map(field => `'${field.fieldName}'`)
+      .join(', ');
+_%>
```
Comment (mshima) [inline generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs:24]: What about putting that in a constant in the generated source?
May be useful at other places.

File: generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs [hunk 2]
```diff
@@ -16,6 +16,12 @@
  See the License for the specific language governing permissions and
  limitations under the License.
 -%>
+<%_
+  const notSortableFieldsAfterSearch = !searchEngine ? '' : fields
+      .filter(field => !field.hidden && !field.fieldTypeBoolean && !field.fieldTypeNumeric && !field.fieldTypeTemporal)
```
Comment (mshima) [inline generators/entity-client/templates/angular/src/main/webapp/app/entities/list/entity-management.component.ts.ejs:21]:
```suggestion
      .filter(field => !field.hidden && !field.sortDisabledForSearchEngine)
```

This logic can be reused at other clients.
- put `sortDisabledForSearchEngine: field.fieldType !== BOOLEAN && !fieldTypeNumeric && !fieldTypeTemporal,`, naming can change.
- extract fieldTypeTemporal and fieldTypeNumeric.

at https://github.com/jhipster/generator-jhipster/blob/5d1410611fa380695038ed9a15dd82cc953546d2/utils/field.js#L226

**Comment by DanielFran** [comment]
@kaidohallik Can you please review the comments?

**Comment by mshima** [comment]
It’s already an improvement. Adjusts may be done afterwards.
