### PR TITLE
only use @Transactional with sql and @Lob without mongodb

### LINKED ISSUE #3010: Mongo DB & Cassandra build fails [master]
Our Mongo DB builds in travis are failing with below

```
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/MongoBankAccountDTO.java:9: error: cannot find symbol
import javax.persistence.Lob;
                        ^
  symbol:   class Lob
  location: package javax.persistence
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:9: error: cannot find symbol
import javax.persistence.Lob;
                        ^
  symbol:   class Lob
  location: package javax.persistence
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/MongoBankAccountDTO.java:52: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.MongoBankAccountDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/MongoBankAccountDTO.java:57: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.MongoBankAccountDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:137: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:143: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:149: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:155: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:160: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:166: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:172: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:178: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:183: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:188: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:193: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
[ERROR] diagnostic: /home/travis/app-mongodb/src/main/java/com/mycompany/myapp/web/rest/dto/FieldTestMapstructEntityDTO.java:198: error: cannot find symbol
    @Lob
     ^
  symbol:   class Lob
  location: class com.mycompany.myapp.web.rest.dto.FieldTestMapstructEntityDTO
```

### PR DESCRIPTION
**Pull request by ruddell**
The Tranactional annotation is normally only used with SQL (based off of _UserService.java) so removing that should allow AccountResourceIntTest to compile and run for mongo and cassandra.

Removing the Lob annotation for Mongo allows Mongo projects with entities containing blobs to compile/upload files and images.

Fix #3010

### CODE REVIEW

**Comment by deepu105** [comment]
but this code was always there how come it never failed before?

**Comment by ruddell** [comment]
The test used to work before though so this might be related to the recent dependency update

**Comment by deepu105** [comment]
@jdubois @andidev @pascalgrimaud what do you think?

**Comment by ruddell** [comment]
@deepu105 the issue is the hibernate-envers dependency was removed

**Comment by deepu105** [comment]
oh yes you are right

**Comment by jdubois** [comment]
Oh that's me yesterday!!
I have no idea why we have a dependency to hibernate-envers -> this was clearly an error for MongoDB so I removed it.
For JPA we need to check this

**Comment by deepu105** [comment]
some of the annotations we use are from the envers package if Lob and transactional is not required for mongoand cassandra then we can merge this PR

**Comment by ruddell** [comment]
Blob works correctly for Mongo without the Lob annotation.

The other option is available #3013.  Sorry for the flurry of PRs.

**Comment by deepu105** [comment]
@jdubois Shall I merge this to solve #3010 ?

**Comment by deepu105** [comment]
@jdubois btw does @Lob do anything for cassandra?
cc @andidev

**Comment by jdubois** [comment]
I can't test now (I'm in a car, using my phone) but yes it looks good to me.
We should also remove the Transactional from the Maven and Gradle dependencies.

**Comment by deepu105** [comment]
its passing travis so Im gonna trust it.

**Comment by jdubois** [comment]
I don't think @Lob does anything for Cassandra

File: generators/entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java [hunk 1]
```diff
@@ -9,7 +9,7 @@
 import java.util.HashSet;
 import java.util.Set;<% } %>
 import java.util.Objects;<% if (databaseType == 'cassandra') { %>
-import java.util.UUID;<% } %><% if (fieldsContainBlob == true) { %>
+import java.util.UUID;<% } %><% if (fieldsContainBlob == true && databaseType != 'mongodb') { %>
```
Comment (deepu105) [inline generators/entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java]: @andidev are you ok with removing Lob for mongo and cassandra? if so ill merge this and amend condition to add only for SQL

Comment (andidev) [inline generators/entity/templates/src/main/java/package/web/rest/dto/_EntityDTO.java]: I'm too unfamiliar with mongodb and Cassandra. I trust rudell on this.

**Comment by deepu105** [comment]
lets merge then

**Comment by jdubois** [comment]
No @Lob is from JPA, that dependency shouldn't even be there in the first place.

**Comment by deepu105** [comment]
its done
