### PR TITLE
Fix User relationship names

### LINKED ISSUE #17001: getUser() is undefined for type ...
##### **Overview of the issue**

This bug results in a compilation error.
If a ManyToOne relationship is defined in jdl as follows:

```
relationship ManyToOne {
    Roster{changedBy(login)} to User
}
```
The Roster domain class is generated as expected with a member variable : User changedBy

However the RestController RosterResource contains the following generated code which does not compile:
```
        if (roster.getUser() != null) {
            // Save user in case it's new and only exists in gateway
            userRepository.save(roster.getUser());
        }
```

##### **Motivation for or Use Case**

This is a bug because the generated app does not compile.

##### **Reproduce the error**

Sample jdl file below:

```
// To generate : jhipster import-jdl --skip-check-length-of-identifier model.jdl  

// application {
//   config {
//     baseName portal
//     applicationType gateway
//     packageName com.jhipster.demo.portal
//     authenticationType oauth2
//     databaseType no
//     devDatabaseType no
//     prodDatabaseType no
//     clientFramework vue
//   }
//   entities *
// }

application {
  config {
    baseName hr
    applicationType microservice
    packageName com.jhipster.demo.hr
    authenticationType oauth2
    databaseType sql
    devDatabaseType h2Disk
    prodDatabaseType oracle
  }
  entities Department, Employee, Roster
}

enum ShiftType {
    EARLY_SHIFT, LATE_SHIFT
}

entity Department {
    name String required
}

entity Employee {
    firstName String
    surname String
    startDate LocalDate
}

entity Roster {
    fromDate LocalDate
    thruDate LocalDate
    shiftType ShiftType
    changedAt Instant
}

relationship OneToOne {
    Employee{user(login)} to User
}

relationship ManyToOne {
    Employee{department(name) required} to Department
    Roster{department(name)} to Department
    Roster{changedBy(login)} to User
}

service * with serviceClass
paginate * with pagination

```

##### **Related issues**

None found

##### **Suggest a Fix**

The RestController generator should be changed to refer to the named relationship.
i.e. `getChangedBy` instead of `getUser`
```
        if (roster.getChangedBy() != null) {
            // Save user in case it's new and only exists in gateway
            userRepository.save(roster.getChangedBy());
        }
```

##### **JHipster Version(s)**

7.3.1

##### **JHipster configuration**

→ E:\mjh\jh\jh-user-rel [master]› jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
hr@0.0.0 E:\mjh\jh\jh-user-rel
└── generator-jhipster@7.3.1  

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "serverPort": "8081",
    "serviceDiscoveryType": "eureka",
    "skipUserManagement": true,
    "baseName": "hr",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en"],
    "messageBroker": false,
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "skipClient": true,
    "testFrameworks": [],
    "websocket": false,
    "enableGradleEnterprise": false,
    "gradleEnterpriseHost": "",
    "applicationType": "microservice",
    "packageName": "com.jhipster.demo.hr",
    "packageFolder": "com/jhipster/demo/hr",
    "jhipsterVersion": "7.3.1",
    "clientPackageManager": "npm",
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "applicationIndex": 0,
    "entities": ["Department", "Employee", "Roster"],
    "skipCheckLengthOfIdentifier": true,
    "skipServer": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": false,
    "nativeLanguage": "en",
    "creationTimestamp": 1636733398586,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1636733578000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Department {
  name String required
}
entity Employee {
  firstName String
  surname String
  startDate LocalDate
}
entity Roster {
  fromDate LocalDate
  thruDate LocalDate
  shiftType ShiftType
  changedAt Instant
}
enum ShiftType {
  EARLY_SHIFT,
  LATE_SHIFT
}

relationship OneToOne {
  Employee{user(login)} to User
}
relationship ManyToOne {
  Employee{department(name) required} to Department
  Roster{department(name)} to Department
  Roster{changedBy(login)} to User
}

paginate Department, Employee, Roster with pagination
service Department, Employee, Roster with serviceClass
microservice Department, Employee, Roster with hr
clientRootFolder Department, Employee, Roster with hr

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

git version 2.31.1.windows.1

node: v14.18.0

npm: 8.0.0

Docker version 20.10.8, build 3967b7d

Docker Compose version v2.0.0

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

##### **Browsers and Operating System**

Windows 10 Pro + Chrome
- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vicpermir**
Fixes #17001

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs [hunk 1]
```diff
@@ -245,17 +239,19 @@ public class <%= entityClass %>Resource {
...
+      <%_ if (userRelationship.collection) { _%> 
+          if (<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalizedPlural %>() != null) { 
+              // Save users in case they are new and only exist in gateway 
+              userRepository.saveAll(<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalizedPlural %>()); 
+          } 
+      <%_ } else { _%> 
+          if (<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalized %>() != null) { 
+              // Save user in case it's new and only exists in gateway 
+              userRepository.save(<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalized %>()); 
+          }
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs:252]:
```suggestion
        if (<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalizedPlural %>() != null) { 
            // Save users in case they are new and only exist in gateway 
            userRepository.saveAll(<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalizedPlural %>()); 
        } 
      <%_ } else { _%> 
        if (<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalized %>() != null) { 
            // Save user in case it's new and only exists in gateway 
            userRepository.save(<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalized %>()); 
        } 
```

File: generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs [hunk 2]
```diff
@@ -308,17 +304,19 @@ public class <%= entityClass %>Resource {
...
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs:317]:
```suggestion
        if (<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalizedPlural %>() != null) { 
            // Save users in case they are new and only exist in gateway 
            userRepository.saveAll(<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalizedPlural %>()); 
        } 
      <%_ } else { _%> 
        if (<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalized %>() != null) { 
            // Save user in case it's new and only exists in gateway 
            userRepository.save(<%= instanceName %>.get<%= userRelationship.relationshipNameCapitalized %>()); 
        } 
```

**Review by mshima — COMMENTED** [review]
Adjust the ident. Generated java source ident should not follow the ejs ident.

**Review by mshima — APPROVED** [review]

**Comment by mshima** [comment]
Thanks @vicpermir for the PR.
