### PR TITLE
throw correct exception on bad password for UAA

### LINKED ISSUE #8014: Gateway Incorrectly Reports UAA's Error Status
##### **Overview of the issue**
When calling UAA, the translated exceptions from a login 'bad request' are converted to status 500, when routed through the gateway.

500_should_be_400

As you can see above, in postman, the request's status code is 500, and in the body of the response, there are two conflicting statuses (400 and 500).

I have not investigated other exceptions' conversion, but I suspect the following lines in `ExceptionTranslator`'s call to `AdviceTrait` (interface) to be at play:

`final HttpStatus status = HttpStatus.valueOf(Optional.ofNullable(problem.getStatus())
        .orElse(Status.INTERNAL_SERVER_ERROR)
        .getStatusCode());`

as the following error is logged in the gateway:

`2018-07-23 14:38:27.093 ERROR 56528 --- [ XNIO-2 task-64] o.z.p.spring.web.advice.AdviceTrait      : Internal Server Error`

##### **JHipster Version(s)**

Version 5.1.0

##### **JHipster configuration**

```
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.xxx.uaa"
    },
    "jhipsterVersion": "5.1.0",
    "baseName": "uaa",
    "packageName": "com.xxx.uaa",
    "packageFolder": "com/x/x/x/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "xxxxxxx",
    "enableTranslation": false,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
```

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ruddell**
Fix #8014

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs [hunk 1]
```diff
@@ -88,9 +90,9 @@ public class OAuth2AuthenticationService {
                 log.debug("successfully authenticated user {}", params.get("username"));
             }
             return ResponseEntity.ok(accessToken);
-        } catch (Exception ex) {
```
Comment (ruddell) [inline generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs]: We can throw the correct `InvalidPasswordException` by catching `HttpClientErrorException` instead of a generic `Exception`.  For other errors (no UAA up or connection refused), the behavior is the same as before - the exception is thrown

File: generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs [hunk 2]
```diff
@@ -88,9 +90,9 @@ public class OAuth2AuthenticationService {
...
+        } catch (HttpClientErrorException ex) {
             log.error("failed to get OAuth2 tokens from UAA", ex);
-            throw ex;
+            throw new InvalidPasswordException();
```
Comment (deepu105) [inline generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs]: dont we need to pass the ex for stacktrace?

Comment (ruddell) [reply generators/server/templates/src/main/java/package/security/oauth2/OAuth2AuthenticationService.java.ejs]: The printed stack trace looks mostly the same, main difference is at the end where it returns the correct exception.  

[Logs from before change](https://gist.githubusercontent.com/ruddell/f5a8c406307bf92b231a6a5a93f1c04f/raw/dcd74aa83810534b8d8283060535a8191cc5a53a/gistfile1.txt) 
[Logs from after change](https://gist.githubusercontent.com/ruddell/b6c38a9b84958e5e351563cc72ede523/raw/b4309503930945911eb1f4dd2d071f7abf8d9db1/After%2520Changes%2520StackTrace%2520PR%25208108)
