### PR TITLE
Fix vue.js constants usage for outputPathCustomizer

### LINKED ISSUE #12346: Improve Vue.js integration on blueprint
##### **Overview of the issue**

Vue.js use directly const like 
`mkdirp(MAIN_SRC_DIR)`
with this we can override path in blueprints with outputPathCustomizer

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by nicolas63**
---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

fix #12346

### CODE REVIEW

**Comment by nicolas63** [comment]
@mshima can you review this ?

File: generators/client/files-vue.js [hunk 1]
```diff
@@ -370,7 +370,7 @@ const vueFiles = {
 };
 
 function writeFiles() {
-    mkdirp(MAIN_SRC_DIR);
+    mkdirp(this.CLIENT_MAIN_SRC_DIR);
```
Comment (mshima) [inline generators/client/files-vue.js:373]: mkdirp isn't required.
```suggestion
```

Comment (nicolas63) [reply generators/client/files-vue.js:373]: Without modification the folder main/webapp was created =/ 
The writeFiles funtion in file-angular and file-react use `mkdirp(this.CLIENT_MAIN_SRC_DIR);`

Comment (mshima) [reply generators/client/files-vue.js:373]: `mkdirp(this.CLIENT_MAIN_SRC_DIR)` should be removed from every file-*.
We shouldn't do any manipulation on the disc at this point.
The dir will be created by mem-fs when committing the files to the disc.

Comment (mshima) [reply generators/client/files-vue.js:373]: This is unlikely to cause problems, but I prefer to try removing.
Your call.

Comment (nicolas63) [reply generators/client/files-vue.js:373]: i'm ok to removed mkdirp at this point, this will be done for jhispster v7 ?

Comment (nicolas63) [reply generators/client/files-vue.js:373]: or i can remove it in this PR i have try without it and it's ok (for .net blueprint)

Comment (mshima) [reply generators/client/files-vue.js:373]: > i'm ok to removed mkdirp at this point, this will be done for jhispster v7 ?

What will be done for jhipster v7? We are on the jhipster v7 branch now.

Comment (mshima) [reply generators/client/files-vue.js:373]: > or i can remove it in this PR i have try without it and it's ok (for .net blueprint)

I prefer that you remove it.

Comment (nicolas63) [reply generators/client/files-vue.js:373]: done

Comment (mshima) [reply generators/client/files-vue.js]: Great.

**Comment by mshima** [comment]
@nicolas63 you don't want to update the others CLIENT_MAIN_SRC_DIR uses?

**Comment by nicolas63** [comment]
which others need to be changed ?

**Comment by mshima** [comment]
There are 4 uses in the same file related to page generator.
https://github.com/jhipster/generator-jhipster/blob/f1b0a539c3d245acf4d077da37ec4339f0d1acbf/generators/utils.js#L729

**Comment by nicolas63** [comment]
> constants.CLIENT_MAIN_SRC_DIR
done

**Comment by mshima** [comment]
Thanks @nicolas63
