### PR TITLE
restrict aspect logging to Service, Repository and Resource beans

### LINKED ISSUE #5715: LoggingAspect causing OutOfMemoryError
##### **Overview of the issue**

`LoggingAspect` logs all method calls in the .repository..*, .service..* and .rest..* packages. However, this is not limited to the actual repositories, services and resources but also includes all helper classes. This is particularly bad for DTOs and MapStruct mappers that can potentially be called a lot for REST endpoints with arrays.

This clogs up the logs with setters and - in our case - even caused an `OutOfMemoryError` from all the logging burden

##### **Motivation for or Use Case**

Not only is it undesirable to have every getter and setter on a DTO in the logs, but the memory consumption can be a serious issue.

##### **Reproduce the error**

Create a REST Resource that takes a retrieves a fairly large array of entities from the database and maps it to DTOs. Calls on DTOs and Mappers trigger the pointcut and either flood the trace or even cause an `OutOfMemoryError`.

	2017-05-05 12:06:38.557 ERROR 16504 --- [  XNIO-2 task-2] c.u.p.c.s.aop.logging.LoggingAspect      : Exception in com.unycom.platform.csp.service.web.rest.mapper.LineItemMapperImpl.lineItemsToLineItemDTOs() with cause = 'NULL' and exception = 'Java heap space'

	java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:3332)
		at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
		at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
		at java.lang.StringBuilder.append(StringBuilder.java:136)
		at java.lang.StringBuilder.append(StringBuilder.java:131)
		at java.util.AbstractCollection.toString(AbstractCollection.java:462)
		at java.lang.String.valueOf(String.java:2994)
		at java.util.Arrays.toString(Arrays.java:4571)
		at com.unycom.platform.csp.service.aop.logging.LoggingAspect.logAround(LoggingAspect.java:70)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
		at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
		at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
		at com.unycom.platform.csp.service.web.rest.mapper.LineItemMapperImpl$$EnhancerBySpringCGLIB$$2c93b379.lineItemsToLineItemDTOs(<generated>)
		at com.unycom.platform.csp.service.service.database.DatabaseReminderService.getLineItems(DatabaseReminderService.java:59)
		at com.unycom.platform.csp.service.service.database.DatabaseReminderService$$FastClassBySpringCGLIB$$a211aef0.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
		at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
		at com.unycom.platform.csp.service.aop.logging.LoggingAspect.logAround(LoggingAspect.java:73)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

##### **Related issues**

n/a

##### **Suggest a Fix**

The pointcut should include bean names so only *Service, *Repository and *Resource are affected.

So, in _LoggingAspect.java, the @Pointcut shall be changed from

    @Pointcut("within(<%=packageName%>.repository..*) || within(<%=packageName%>.service..*) || within(<%=packageName%>.web.rest..*)")

to

    @Pointcut("(within(<%=packageName%>.repository..*) && bean(*Repository))"+
                  " || (within(<%=packageName%>.service..*) && bean(*Service))"+
                  " || (within(<%=packageName%>.web.rest..*) && bean(*Resource))")

##### **JHipster Version(s)**

4.3.0

##### **JHipster configuration**

n/a since LoggingAspect gets picked up for all configurations

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

n/a

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by Metavirulent**
LoggingAspect no longer logs every single bean in the affect packages but only those complying with the naming convention.

Fixes #5715

### CODE REVIEW

File: generators/server/templates/src/main/java/package/aop/logging/_LoggingAspect.java [hunk 1]
```diff
@@ -51,7 +51,9 @@ public LoggingAspect(Environment env) {
     /**
      * Pointcut that matches all repositories, services and Web REST endpoints.
      */
-    @Pointcut("within(<%=packageName%>.repository..*) || within(<%=packageName%>.service..*) || within(<%=packageName%>.web.rest..*)")
+    @Pointcut("(within(io.github.jhipster.travis.repository..*) && @annotation(org.springframework.stereotype.Repository))"+
```
Comment (pascalgrimaud) [inline generators/server/templates/src/main/java/package/aop/logging/_LoggingAspect.java]: you should keep `<%=packageName%>` instead of using fixed `io.github.jhipster.travis`

**Comment by pascalgrimaud** [comment]
FYI, Travis failed on Cassandra and MongoDB

**Comment by gzsombor** [comment]
👍  from me!
