### PR TITLE
Fix cache header

### LINKED ISSUE #11575: Cache-Control from CachingHttpHeadersFilter overwritten by WebMvcAutoConfiguration
It seems that Cache-Control Headers added by `io.github.jhipster.web.filter.CachingHttpHeadersFilter` are just overwritten/discarded due to SpringMvcAutoConfig.

Not sure if I am not seeing something, but 6.8.0, 6.7.1 and 6.6.0 show this behaviour.

##### **Overview of the issue**

Any config/added "Cache-Control" by following block in `WebConfigurer` 

```
 @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        ...
        if (env.acceptsProfiles(Profiles.of(JHipsterConstants.SPRING_PROFILE_PRODUCTION))) {
            initCachingHttpHeadersFilter(servletContext, disps);
        }
       ...
    }
```

Following this method call:

```

    private void initCachingHttpHeadersFilter(ServletContext servletContext,
                                              EnumSet<DispatcherType> disps) {
        log.debug("Registering Caching HTTP Headers Filter");
        FilterRegistration.Dynamic cachingHttpHeadersFilter =
            servletContext.addFilter("cachingHttpHeadersFilter",
                new CachingHttpHeadersFilter(jHipsterProperties));

        cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/i18n/*");
        cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/content/*");
        cachingHttpHeadersFilter.addMappingForUrlPatterns(disps, true, "/app/*");
        cachingHttpHeadersFilter.setAsyncSupported(true);
    }
```

**Is not affecting cached resources in "prod" at all.**

Assets will still have `Cache-Control: no-store`.

It seems that the filter itself works, but `WebMvcAutoConfiguration` will set its own cache-strategy here:

```
@Override
public void addResourceHandlers(ResourceHandlerRegistry registry) {
...
customizeResourceHandlerRegistration(registry.addResourceHandler(staticPathPattern)
		.addResourceLocations(getResourceLocations(this.resourceProperties.getStaticLocations()))
		.setCachePeriod(getSeconds(cachePeriod)).setCacheControl(cacheControl));
```

And then override any cache headers when serving static content.

##### **Motivation for or Use Case**

`CachingHttpHeadersFilter` cannot be used, any sign of "if in PRD, following assets are cached" is wrong.

##### **Reproduce the error**

* Use a blank JHipster project configured as monolith.

* add code "if(true||" to the if around "com.mycompany.myapp.config.WebConfigurer#initCachingHttpHeadersFilter(..)">

* add 
```
jhipster:
  http:
    cache: # Used by the CachingHttpHeadersFilter
      timeToLiveInDays: 1461
``` 
to `application.yml` to enable this setting on all env.

* start mvnw
```
$ ./mvnw
....
----------------------------------------------------------
        Application 'testFreshJhipster' is running! Access URLs:
        Local:          http://localhost:8080/
        External:       http://192.168.178.40:8080/
        Profile(s):     [dev, swagger]
----------------------------------------------------------
```

* Open website on `localhost:8080`

* Inspect response-headers of js/css `/app/*`

* see that it still says `Cache-Control: no-store`

```

http://localhost:8080/app/main.bundle.js

HTTP/1.1 200 OK
Expires: 
Cache-Control: no-store
Pragma: 
Accept-Ranges: bytes
Date: Sat, 11 Apr 2020 18:31:59 GMT
Connection: keep-alive
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Last-Modified: Sat, 11 Apr 2020 18:01:09 GMT
Content-Length: 10454712
Content-Type: application/javascript
```

I am not sure whenthis was introcued. I can reproduce this with 6.8.0, 6.7.1, 6.6.0

##### **Suggest a Fix**

I have been debugging this for a while and not come up with a solution yet.

So far I found out that:

* `spring.resources.chain.period: -1s` will disable the caching, so that the headers are not overwritten
  * but then **no** resources at all receive any cache-headers.
* `spring.resources.chain.period: 1s` will change it from "no-store" to "1". But still override it.

The code to set headers will probably either have to follow this pattern:

```
@Configuration
public class HttpCacheControlConfiguration implements WebMvcConfigurer {

    @Autowired
    private ResourceProperties resourceProperties;


    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {

        registry.addResourceHandler("/app/**")
            .addResourceLocations(resourceProperties.getStaticLocations())
            .setCachePeriod(12222);

    }
}

```
(altough I have not got it to work yet, assets in /app hit a 404)

Or the `CachingHttpHeadersFilter` has to filter **after** whatever Spring MVC is doing with the headers.

##### **JHipster Version(s)**

```
test-fresh-jhipster@0.0.1-SNAPSHOT C:\projects\xxx\testFreshJhipster
`-- generator-jhipster@6.8.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "testFreshJhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1586613662092,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

git version 2.25.0.windows.1

node: v12.15.0

npm: 6.14.4

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

Firefox 75 & Windows 10

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by monxxi**
Fix #11575 
Removing the usage of CachingHttpHeadersFilter for "/i18n/** ", "/content/** ", "/app/** " paths

I replace it by the usage of ResourceHandler  Configured in a specific WebConfigurer

Headers "Cache-Control","Pragma","Expires" put by CachingHttpHeadersFilter are overwriting by The ResourceHttpRequestHandler

-   Please make sure the below checklist is followed for Pull Requests.

-   [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [X] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@monxxi converted to a draft until development is done.
I remove also the WIP in the title

**Comment by monxxi** [comment]
Ok sorry for that,
Thanks

File: generators/server/templates/src/main/java/package/config/StaticResourcesWebConfiguration.java.ejs [hunk 1]
```diff
@@ -0,0 +1,51 @@
+package
```
Comment (DanielFran) [inline generators/server/templates/src/main/java/package/config/StaticResourcesWebConfiguration.java.ejs:1]: Remove breack line for package and add license header

File: generators/server/templates/src/test/java/package/config/StaticResourceWebConfigurerTest.java.ejs [hunk 2]
```diff
@@ -0,0 +1,82 @@
+package <%= packageName %>.config;
```
Comment (DanielFran) [inline generators/server/templates/src/test/java/package/config/StaticResourceWebConfigurerTest.java.ejs:1]: add license header

File: generators/server/templates/src/test/java/package/config/StaticResourceWebConfigurerTest.java.ejs [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+    @BeforeEach
+    void setUp() {
+        servletContext = spy(new MockServletContext());
+        applicationContext = mock(WebApplicationContext.class);
+        resourceHandlerRegistry = spy(new ResourceHandlerRegistry(applicationContext, servletContext));
+        props = new JHipsterProperties();
+        staticResourcesWebConfiguration = spy(new StaticResourcesWebConfiguration(props));
+
+    }
+
```
Comment (DanielFran) [inline generators/server/templates/src/test/java/package/config/StaticResourceWebConfigurerTest.java.ejs:36]: remove line

File: generators/server/templates/src/test/java/package/config/StaticResourceWebConfigurerTest.java.ejs [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+        when(staticResourcesWebConfiguration.getCacheControl()).thenReturn(ccExpected);
+        ResourceHandlerRegistration resourceHandlerRegistration = spy(new ResourceHandlerRegistration(RESOURCE_PATHS));
+
+        staticResourcesWebConfiguration.initializeResourceHandler(resourceHandlerRegistration);
+
+        verify(staticResourcesWebConfiguration, times(1)).getCacheControl();
+        verify(resourceHandlerRegistration, times(1)).setCacheControl(ccExpected);
+        verify(resourceHandlerRegistration, times(1)).addResourceLocations(RESOURCE_LOCATIONS);
+    }
+
```
Comment (DanielFran) [inline generators/server/templates/src/test/java/package/config/StaticResourceWebConfigurerTest.java.ejs:64]: remove line

**Comment by monxxi** [comment]
thanks for review, i fix it today

**Comment by DRoppelt** [comment]
I think that any cache-setting that is not `/app/*` should be removed. For instance, caching i18n for 5 years does not make sense since these assets are not "stamped" with their hash in the filename. Unlike contents of /app/.

Additionally, there is `global.css` and `app.css` (stamped with hash) that are put into root, that can be moved into `/app` since they are cachable for X years (as they are stamped with a hash).

**Comment by monxxi** [comment]
@DRoppelt , it may be interesting to put the paths and locations settings under jhipster properties control and use /app/* as default values?

**Comment by ruddell** [comment]
@DRoppelt The i18n resources should be cached.  They are loaded with the build timestamp in a query parameter, so they are cachebusted every time a new build is released in prod.  For example, [Angular](https://github.com/jhipster/generator-jhipster/blob/d3cc5f6b8e021422bbab6d8151172ececb0eaf2d/generators/client/templates/angular/src/main/webapp/app/shared/constants/i18n.constants.ts.ejs#L27), [React](https://github.com/jhipster/generator-jhipster/blob/d3cc5f6b8e021422bbab6d8151172ececb0eaf2d/generators/client/templates/react/src/main/webapp/app/shared/reducers/locale.ts.ejs#L51), [Vue](https://github.com/jhipster/jhipster-vuejs/blob/9078e565971b754de03703dd3af1e28b3326d07c/generators/client/templates/vue/src/main/webapp/app/locale/translation.service.ts.ejs#L20)

**Comment by DRoppelt** [comment]
> They are loaded with the build timestamp in a query parameter, so they are cachebusted every time a new build is released in prod.

When I used i18n with vue last time (blueprint version `1.7.0`), it seemed that there were no query params added. I am not confident with frontend stuff, so maybe there is an issue on my side. But maybe someone could verify? Additionally, the code you linked seems to suggest that the timestamp is only added when switching languages.

But `/content/**` should not be inlcuded IMO, as they are not cachebusted. Since caching did not work, it was not an issue that it was configured with `/content/**`.

It would be interesting to find out since when this bug was introduced and see what was configured back then (maybe it was just `/app/**` only back then).

While this is fixing something, the change is quite severe if things are now cached for several years when it was not cached at all before.

**Comment by ruddell** [comment]
@DRoppelt For the Vue issue, the v1.7.0 release is from March 15 and the commit fixing that issue is from March 25, so it is not released yet.  It is working if you use the master branch.

Regarding the content folder, css files should definitely be cached but that would need further testing to ensure things like images are not cached (or hashed then cached). This would have been fine previously since only the hashed CSS files were in `content/*` but with the new change it does use `content/**`

**Comment by monxxi** [comment]
@ruddell & @DRoppelt , Indeed the `content/**`,'i18n/**' and 'app/**' don't respect the previous declaration done with the cache filter, i gonna change it

**Comment by DRoppelt** [comment]
You might also want to change following path for the vue `webpack.prod.js`

```
    // extract css into its own file
    new MiniCssExtractPlugin({
      filename: '[name].[contenthash].css',
      chunkFilename: '[id].css'
    }),
    // Compress extracted CSS. We are using this plugin so that possible
    // duplicated CSS from different components can be deduped.
```

From
```
      filename: '[name].[contenthash].css',
      chunkFilename: '[id].css'
```

To

```
      filename: 'app/[name].[contenthash].css',
      chunkFilename: 'app/[id].css'
```

`app.[hash].css`, `global.[hash].css` and `vendor.[hash].css` are all put into `/` and could be put into `/app/` to make use of the caching, since they are hashed anyways.

**Comment by monxxi** [comment]
@DRoppelt , yes i should change the location of these prod files in the vuejs project, but i'm not sure that the 'app/' directory is the good place
Why  not use the 'content/' directory which contains others css? (it seems to be the case for angular & react client)

**Comment by DRoppelt** [comment]
@monxxi anywhere else than `/` would be good IMO. I suggested `/app` purely on the fact that everything in there is already hashed and thus can be cached practically indefinitely.

If the other two clients use `/content`, then there is not reason to do it differently for vue.

**Comment by pascalgrimaud** [comment]
@DanielFran @ruddell : can one of you have a last quick look plz ? Then we should merge this before the next release. Thanks a lot !

FYI, I already review the Vue.js part and merged it.

**Comment by pascalgrimaud** [comment]
thanks @monxxi @DanielFran and @ruddell !

**Comment by DanielFran** [comment]
Forget to thanks @monxxi for his contribution.

**Comment by monxxi** [comment]
Thanks for your reviews and your messages and thanks @pascalgrimaud for the bounty added on #11575 

bounty claimed: https://opencollective.com/generator-jhipster/expenses/17656

**Comment by jdubois** [comment]
Congrats @monxxi 
@pascalgrimaud this is typically the kind of file that I would like to move to our jhipster-framework in JHipster 7, as people will complain that what we generate is "too complex". Of course it should be possible to disable it, and reconfigure the static directories paths, so that means more JHipster Spring Boot configuration.

**Comment by DanielFran** [comment]
@jdubois I can take care of the migration to jhipster lib project for v7, if you agree
