### PR TITLE
fix the handling of falsy values in field annotations

### LINKED ISSUE #28751: Field annotations with falsy values are not correctly handled
##### **Overview of the issue**

annotating an entity field with falsy values, like:
`@isEnabled(false)`
creates the following field options object:
`field.options == { isEnabled: true }`

##### **JHipster JDL**

  <details>
  <summary>JDL definitions</summary>
  <pre>
entity SampleEntity {
  @isEnabled(false)
  @isOpen(0)
  @isHappy("")
  sampleField String
}
  </pre>
  </details>

- [X] JDL is mandatory for bug reports. This will allow us to use automated tests and genarate the broken sample using `jhipster from-issue` command.

##### **Motivation for or Use Case**

I'm writing a custom generator that uses entities from a JDL file.

##### **Reproduce the error**

create a JDL file with an entity and annotate a field with falsy values, e.g.:
```
entity SampleEntity {
  @isEnabled(false)
  @isOpen(0)
  @isHappy("")
  sampleField String
}
```

run the JDL parser, you'll end up with a parsed entity config like:
```
{
  "applications": "*",
  "fields": [
    {
      "fieldName": "sampleField",
      "fieldType": "String",
      "options": {
        "isEnabled": true,
        "isHappy": true,
        "isOpen": true
      }
    }
  ],
  "name": "SampleEntity",
  "relationships": []
}
```

##### **Related issues**

I think that issue https://github.com/jhipster/generator-jhipster/issues/28312 may be related to this problem

##### **Suggest a Fix**

I'll open a pull request with a fix

##### **JHipster Version(s)**

8.9.0

##### **Browsers and Operating System**

Windows

- [X] Tickets opened without reproduction steps or that doesn't follows the template recommendation will be **closed**.
- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by francesco-carusi-zupit**
Fix #28751

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: lib/jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.ts [hunk 1]
```diff
@@ -159,7 +159,7 @@ function convertAnnotationsToOptions(
   const result = {};
   annotations.forEach(annotation => {
     const annotationName = lowerFirst(annotation.optionName);
-    const value = annotation.optionValue ? annotation.optionValue : true;
+    const value = annotation.optionValue !== undefined ? annotation.optionValue : true;
```
Comment (mshima) [inline lib/jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.ts:162]: I think we can use nullish coalescing

```suggestion
    const value = annotation.optionValue ?? true;
```

Comment (francesco-carusi-zupit) [reply lib/jdl/converters/parsed-jdl-to-jdl-object/parsed-jdl-to-jdl-object-converter.ts]: changed, thanks

**Review by DanielFran — APPROVED** [review]
