### PR TITLE
fix microservice proxy path

### LINKED ISSUE #8021: Incorrect casing is used for gateway service urls when using JHipster entity generator in Microservice Mode
##### **Overview of the issue**

Generating an entity in a Microservice Gateway using `jhipster entity [entityName]`, and selecting `Yes` when asked "Do you want to generate this entity from an existing microservice?" uses the wrong alpha-casing for the `resourceUrl` and `resourceSearchUrl` (if elasticsearch is turned on).

Note: This may only be the case when using **Consul**. I have not tested all iterations of the jhipster generator for this setup.

##### **Motivation for or Use Case**

If my Microservice Application is called "TestApi", and it has an entity called "Author", when I run `jhipster entity author` in my Gateway and connect it to the Microservice App's Author entity, it tries to make calls to `/testapi/api/authors`, which returns a 404 Not Found. If, in the Gateway app, I go into `author.service.ts` and change `private resourceUrl = SERVER_API_URL + 'testapi/api/authors';` to `private resourceUrl = SERVER_API_URL + 'TestApi/api/authors';`, it works fine.

##### **Reproduce the error**

* Use start.jhipster.tech to generate a microservice gateway and microservice application.
* Gateway:
  * Application Name: TestGateway
  * Repository Name: test-gateway
  * Application Type: Microservice gateway
  * Default Java Package Name: io.github.jhipster.application
  * Port: 8080
  * JHipster Registry: No, Use Consul
  * Auth: JWT
  * DB Type: SQL
  * Prod DB: Postgres
  * Dev DB: H2 with disk-based
  * Spring Cache: HazelCast
  * Hibernate 2nd level cache: Yes
  * Maven or Gradle: Gradle
  * Other Technologies: Api First, WebSockets, ElasticSearch
  * Framework: Angular 6
  * LibSass: Yes
  * I18N: Yes
  * Native Language: English
  * Additional languages: None (English only)
  * Testing Options: Cucumber, Protractor
* Microservice Application:
  * Application Name: TestApi
  * Repo Name: test-api
  * Default Java Package Name: io.github.jhipster.application
  * Port: 8081
  * JHipster Registry: No, Use Consul
  * Auth: JWT
  * DB Type: SQL
  * Prod DB: Postgres
  * Dev DB: H2 disk-based
  * Spring Cache: HazelCast
  * Hibernate 2nd Level: Yes
  * Maven or Gradle: Gradle
  * Other Technologies: Api First, WebSockets, ElasticSearch
  * I18N: Yes
  * Additional Languages: None
  * Testing Options: Cucumber
* In TestApi, Run `jhipster entity author`, do whatever you want for the options
* In TestGateway, Run `jhipster entity author`, say Yes for if you want to generate from Microservice, Point to Microservice path (../test-api)
* Run everything
* Go to the Authors page
* Get 404 Not Found because it is looking for /testapi/authors rather than /TestApi/authors

##### **Related issues**

As far as I can see, this has not been reported

##### **Suggest a Fix**

Change the hard coded strings in the in entityName.service.ts to use the same casing that the microservice uses

##### **JHipster Version(s)**

Gateway:
```
$ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-gateway@0.0.0 C:\Users\rotha\source\test-gateway
`-- generator-jhipster@5.1.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "gateway",
    "gitCompany": "",
    "baseName": "TestGateway",
    "packageName": "io.github.jhipster.application",
    "packageFolder": "io/github/jhipster/application",
    "serverPort": 8080,
    "serviceDiscoveryType": "consul",
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "enableSwaggerCodegen": "true",
    "messageBroker": false,
    "buildTool": "gradle",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "promptValues": {
      "microservicePath": "../test-api"
    }
  },
  "git-provider": "GitHub",
  "git-company": "REDACTED",
  "repository-name": "test-gateway"
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0.windows.1

node: v8.11.3

npm: 5.6.0

yeoman: 2.0.4

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 7641a569

Congratulations, JHipster execution is complete!
```

Microservice:
```
$ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-api@0.0.0 C:\Users\rotha\source\test-api
`-- generator-jhipster@5.1.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "gitCompany": "",
    "baseName": "TestApi",
    "packageName": "io.github.jhipster.application",
    "packageFolder": "io/github/jhipster/application",
    "serverPort": 8081,
    "serviceDiscoveryType": "consul",
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "enableSwaggerCodegen": "true",
    "messageBroker": false,
    "buildTool": "gradle",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "cucumber"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi"
  },
  "git-provider": "GitHub",
  "git-company": "REDACTED",
  "repository-name": "test-api"
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Author (author) {
  name String required minlength(1) maxlength(50) pattern(/^[a-zA-Z0-9 ]*$/),
  birthDate LocalDate required
}
entity Book (book) {
  title String required minlength(1) maxlength(100),
  description String required minlength(1) maxlength(500),
  publicationDate LocalDate required,
  price BigDecimal required min(0)
}
relationship OneToMany {
  Author{book} to Book{author(name) required}
}

dto Author, Book with mapstruct
paginate Author, Book with infinite-scroll
service Author, Book with serviceImpl
search Author, Book with elasticsearch
microservice Author, Book with TestApi
filter Author, Book

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.18.0.windows.1

node: v8.11.3

npm: 5.6.0

yeoman: 2.0.4

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 7641a569

Congratulations, JHipster execution is complete!
```

##### **JHipster configuration**

See above

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Author:
```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "book",
            "otherEntityName": "book",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "author"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength",
                "pattern"
            ],
            "fieldValidateRulesMinlength": "1",
            "fieldValidateRulesMaxlength": "50",
            "fieldValidateRulesPattern": "^[a-zA-Z0-9 ]*$"
        },
        {
            "fieldName": "birthDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20180725125736",
    "dto": "mapstruct",
    "searchEngine": "elasticsearch",
    "service": "serviceImpl",
    "entityTableName": "author",
    "jpaMetamodelFiltering": true,
    "pagination": "infinite-scroll",
    "microserviceName": "TestApi"
}
```

Book:
```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [
        {
            "relationshipName": "author",
            "otherEntityName": "author",
            "relationshipType": "many-to-one",
            "relationshipValidateRules": [
                "required"
            ],
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "1",
            "fieldValidateRulesMaxlength": "100"
        },
        {
            "fieldName": "description",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "1",
            "fieldValidateRulesMaxlength": "500"
        },
        {
            "fieldName": "publicationDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "price",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required",
                "min"
            ],
            "fieldValidateRulesMin": "0"
        }
    ],
    "changelogDate": "20180725130253",
    "dto": "mapstruct",
    "searchEngine": "elasticsearch",
    "service": "serviceImpl",
    "entityTableName": "book",
    "jpaMetamodelFiltering": true,
    "pagination": "infinite-scroll",
    "microserviceName": "TestApi"
}
```

##### **Browsers and Operating System**

Windows 10 Pro, I've only tried with Firefox 61.0.1

- [x ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ruddell**
Fix #8021

Also added tests for generating microservice entities on the gateway to ensure the expected files are generated.

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: test/utils/expected-files.js [hunk 1]
```diff
@@ -83,15 +83,33 @@ const expectedFiles = {
...
         ],
+        clientNg2GatewayMicroserviceEntity: [
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar.component.html`,
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar-detail.component.html`,
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar-update.component.html`,
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar-delete-dialog.component.html`,
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar.route.ts`,
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar.component.ts`,
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar-update.component.ts`,
+            `${CLIENT_MAIN_SRC_DIR}app/entities/sampleMicroservice/bar/bar-delete-dialog.component.ts`,
```
Comment (ruddell) [inline test/utils/expected-files.js]: We should probably use `sample-microservice` for the directory instead of `sampleMicroservice`, it's been this way since v5.  I can change this if we want.

**Comment by ruddell** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/5017
