### PR TITLE
Fix entity pagination in Angular

### LINKED ISSUE #10931: Angular - Pagination - Default input for pageChange event has weird behavior
##### **Overview of the issue**
I apologize if this is already tracked.
Very quickly, the default ngb-pagination component jhipster generates is builded with the following configuration:

~~~html
<ngb-pagination (pageChange)="loadPage(page)" [(page)]="page" [boundaryLinks]="true"
                            [collectionSize]="totalItems" [maxSize]="5" [pageSize]="itemsPerPage"
                            [rotate]="true"></ngb-pagination>
~~~

Now what happen is that the `pageChange` event sends to `loadPage` the current page **before** the change. This means that if I am on page 1 and I try to navigate to page 2 I will still see page 1. Then if I try to navigate to page 4 I will see page 2, etc...

##### **Motivation for or Use Case**
This way it is just unusable.

##### **Reproduce the error**
Create a new entity with pagination enabled.

##### **Suggest a Fix**
I was able to fix this putting `$event` as input instead of `page`:

~~~html
<ngb-pagination #pagination (pageChange)="loadPage($event)" [(page)]="page [boundaryLinks]="true" [collectionSize]="totalItems" [maxSize]="5" [pageSize]="itemsPerPage [rotate]="true"></ngb-pagination>
~~~

##### **JHipster Version(s)**

```
jhiptest@0.0.1-SNAPSHOT C:\Users\user\jhiptest
+-- generator-jhipster@6.5.1
`-- generator-jhipster-elasticsearch-reindexer-2@1.2.2
  `-- generator-jhipster@6.5.1  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitCompany": "",
    "baseName": "jhiptest",
    "packageName": "com.jhiptest.admin",
    "packageFolder": "com/jhiptest/admin",
    "serverPort": 8080,
    "serviceDiscoveryType": "eureka",
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "protractor"
    ],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "en",
      "it"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "6.5.1",
    "jwtSecretKey": "-",
    "embeddableLaunchScript": false,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": []
  },
  "git-provider": "-",
  "git-company": "-",
  "repository-name": "-"
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Tag {
  description String required minlength(1) maxlength(255)
}
dto Tag with mapstruct
paginate Tag with pagination
service Tag with serviceImpl
search Tag with elasticsearch

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

git version 2.23.0.windows.1

node: v10.16.3

npm: 6.9.0

yeoman: 3.1.0

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**
Tested on Windows 10 Home and Pro with Chrome and Firefox (latest versions)

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by kaidohallik**
Closes #10931 

Fixed all problems and replaced suspicious code described in https://github.com/jhipster/generator-jhipster/issues/10931#issuecomment-565909336

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs [hunk 1]
```diff
@@ -103,16 +105,32 @@ export class <%= entityAngularName %>Component implements OnInit, OnDestroy {
...
+        <%_ if (searchEngine === 'elasticsearch') { _%>
+        this.ngbPaginationPage = this.page;
         <%_ } _%>
-        if (data) {
-            this.<%= entityInstancePlural %> = data;
-        } else {
-            this.<%= entityInstancePlural %> = [];
-        }
+        this.router.navigate(['/<%= entityUrl %>'], {
+          queryParams: {
```
Comment (pascalgrimaud) [inline generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs]: minor comment: you switch here to 2 spaces instead of 4 ?

Comment (kaidohallik) [reply generators/entity-client/templates/angular/src/main/webapp/app/entities/entity-management.component.ts.ejs]: Good catch! I corrected indentation. This was caused by having different spacing in generator templates and in final generated app formatted by Prettier:
* in generator templates is used 4 space indentation
* Prettier formats indentation to 2 spaces

And in this place I missed fixing indentation after copying from tested sample application.

I also rebased with latest master to pass CI.

**Comment by kaidohallik** [comment]
After rebase was strict null check error which is fixed now.

I also removed all Cassandra checks `databaseType !== 'cassandra'` from pagination related template parts with separate commit, because if using Cassandra then `pagination` is always `'no'`, look at:
* `checkForPaginationInAppWithCassandra` for JDL in jhipster-core: https://github.com/jhipster/jhipster-core/blob/master/lib/validators/business_error_checker.js#L235-L254
* entity prompts for pagination: https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L422-L424

This simplified entity component a lot.
