### PR TITLE
change equals method in entity template

### LINKED ISSUE #2543: Using Entity.id only on equals() lead to unexpected behavior when id = null
### SImple scenario:

when you have 2 entities with a OneToMany relationship and want to use the parent list to maintain the relationship using `CascadeType.ALL` (or persist, or update)

- [ ] Create the Father of the relationship
- [ ] Create 2 new childs of the same type and add them to the parent list.
- [ ] using `CascadeType.PERSIST` on the relationship call `repository.save()`

### Expected result

2 childs added to the database

### Actual result:
only the second child is added, as equals using id returned true when both were `null`.

### How to fix?

something like:
````
 @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        if (id == null || other.id == null) {
            return Objects.equals(field, other.field) && Objects.equals(anotherField, other.anotherField) && Objects.equals(yetAnother, other.yetAnother);
        }
        return Objects.equals(id, buildRequest.id);
    }
```

### PR DESCRIPTION
**Pull request by vbillard**
Add multiple entities with id null in a collection with cascade
persistence lead to persist only one entity, because they are
equals. Without business key, entites with null primary key
should be never equals with anything.

Fix #2543

### CODE REVIEW

**Comment by jdubois** [comment]
LGTM anyone has any comments on this?

It solves *part* of the issue (as you can still have the issue if you add twice the same un-saved entity), but for me it's the best we can do, without implementing business methods (which we can't, of course it's up to the developer to do that)

**Comment by gzsombor** [comment]
Seems to be a reasonable fix.

**Comment by jdubois** [comment]
Thanks @gzsombor so let's do this!

File: entity/templates/src/main/java/package/domain/_Entity.java [hunk 1]
```diff
@@ -224,6 +224,9 @@ public boolean equals(Object o) {
             return false;
         }
         <%= entityClass %> <%= entityInstance %> = (<%= entityClass %>) o;
+        if(<%= entityInstance %>.id == null || id == null) {
```
Comment (bitsal) [inline entity/templates/src/main/java/package/domain/_Entity.java]: Doesn't it break a contract?
Two objects with null IDs should be equal if ID is a part of equals and hashcode. With this implementation it is false.

Comment (gzsombor) [inline entity/templates/src/main/java/package/domain/_Entity.java]: No, there is no such contract which is needs to be fulfilled.
It needs to be symmetric:
  a.equals(b) == b.equals(a)
Transitive:
  (a.equals(b) && b.equals(c)) => a.equals(c)

Comment (bitsal) [inline entity/templates/src/main/java/package/domain/_Entity.java]: It is ok, but it is not obvious that a(id=null) != b(id=null)

Comment (gzsombor) [inline entity/templates/src/main/java/package/domain/_Entity.java]: The not obvious thing, is that if the ids are the same, then the entities are equals, but that is what Hibernate requires to function.
