### PR TITLE
Fix: Pagination not working on history back/forward

### LINKED ISSUE #11455: Pagination not working on history back/forward
##### **Overview of the issue**

Pagination of entity in React frontend does not work when using history back/forward, e.g. mouse back button.

##### **Reproduce the error**

Create a simple entity with pagination. Go to page > 1 by using the pagination component and try to navigate back and forth by using the mouse buttons.

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway-react@0.0.1-SNAPSHOT C:\gatewayReact
`-- generator-jhipster@6.7.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.foo",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "6.7.0",
    "applicationType": "gateway",
    "baseName": "gatewayReact",
    "packageName": "de.foo",
    "packageFolder": "de/foo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "secret",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "react",
    "clientTheme": "materia",
    "clientThemeVariant": "light",
    "creationTimestamp": 1581489638260,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": ["de", "en"],
    "blueprints": []
  }
}
</pre>
</details>

##### **Environment and Tools**

openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)

git version 2.15.0.windows.1

node: v12.4.0

npm: 6.9.0

yeoman: 3.1.1

Docker version 19.03.5, build 633a0ea

docker-compose version 1.25.4, build 8d51620a

##### **Browsers and Operating System**

Windows/Chrome, should be Browser independent.

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #11455

In this PR: 
-   [x] React: pagination not working on history back/forward
-   [x] React: if you refresh on a page greater than 1, it does not reset the page with the good parameter
-   [x] Angular: pagination not working on history back/forward

Checks:
-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs [hunk 1]
```diff
@@ -141,7 +160,7 @@ export const AuditsPage = (props: IAuditsPageProps) => {
           <Translate contentKey="audits.notFound">No audit found</Translate>
         </div>
       )}
-      <div className={audits && audits.length > 0 ? '' : 'd-none'}>
+      { props.totalItems && props.totalItems !== 0 ? (<div className={audits && audits.length > 0 ? '' : 'd-none'}>
```
Comment (chrisdns) [inline generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs:163]: `props.totalItems` is enough

File: generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs [hunk 2]
```diff
@@ -166,7 +185,7 @@ export const UserManagement = (props: IUserManagementProps) => {
         </tbody>
       </Table>
       <%_ if (databaseType !== 'cassandra') { _%>
-        <div className={ users && users.length > 0 ? '' : 'd-none' }>
+        { props.totalItems && props.totalItems !== 0 ? (<div className={ users && users.length > 0 ? '' : 'd-none' }>
```
Comment (chrisdns) [inline generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs:188]: same

File: generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs [hunk 3]
```diff
@@ -18,6 +18,7 @@
 -%>
     <%= entityInstancePlural %>?: I<%= entityAngularName %>[];
     eventSubscriber?: Subscription;
+    queryParamMapObs?: Subscription;
```
Comment (chrisdns) [inline generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs:21]: not needed since unsubscriptions from route observables are already managed

File: generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs (hunk 1 above)
Comment (qmonmert) [reply generators/client/templates/react/src/main/webapp/app/modules/administration/audits/audits.tsx.ejs:163]: ✅

File: generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs (hunk 2 above)
Comment (qmonmert) [reply generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.tsx.ejs:188]: ✅

File: generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs (hunk 3 above)
Comment (qmonmert) [reply generators/entity-client/templates/angular/src/main/webapp/app/entities/pagination-template.ejs:21]: ✅

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs [hunk 4]
```diff
@@ -404,7 +425,7 @@ export const <%= entityReactName %> = (props: I<%= entityReactName %>Props) => {
       </div>
       <%_ if (databaseType !== 'cassandra') { _%>
         <%_ if (pagination === 'pagination' || pagination === 'pager') { _%>
-        <div className={ <%= entityInstance %>List && <%= entityInstance %>List.length > 0 ? '' : 'd-none' }>
+        { props.totalItems && props.totalItems !== 0 ? (<div className={ <%= entityInstance %>List && <%= entityInstance %>List.length > 0 ? '' : 'd-none' }>
```
Comment (ruddell) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs:428]: Similar to the other review, this can just be `props.totalItems`
```suggestion
        { props.totalItems ? (<div className={ <%= entityInstance %>List && <%= entityInstance %>List.length > 0 ? '' : 'd-none' }>
```

Comment (qmonmert) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs:428]: @ruddell yes thanks 🙂

**Comment by pascalgrimaud** [comment]
it should be good. The failure with webflux is not related to this one !
Thanks for your hard work @qmonmert
