### PR TITLE
Fix enableHibernateCache in prompt

### LINKED ISSUE #12445: When the "cacheProvider" is set to "no", the "enableHibernateCache" is automatically set to "true"
##### **Overview of the issue**

When the "cacheProvider" is set to "no", the "enableHibernateCache" is automatically set to "true"

When the "cacheProvider" is set to "no", the option to select the  "enableHibernateCache" does not appear,
then the default value("true") is set.

##### **Reproduce the error**

- jhipster

? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? PostgreSQL
? Do you want to use the Spring cache abstraction? No - Warning, when using an SQL database, this will disable the Hibernate 2nd level cache!

##### **Suggest a Fix**

- Set default value of "enableHibernateCache" to "false"

or

- Set value of "enableHibernateCache" to "false" when  "cacheProvider" is set to "no"
 

##### **JHipster Version(s)**

master
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "master",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1599995426806,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "clientThemeVariant": "primary",
    "useSass": true,
    "enableHibernateCache": true,
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1, mixed mode, sharing)

git version 2.28.0

node: v12.18.3

npm: 6.14.8

Docker version 19.03.12, build 48a6621

docker-compose version 1.25.0, build unknown

### PR DESCRIPTION
**Pull request by MarlonLuan**
Fixes #12445
---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/server/prompts.js [hunk 1]
```diff
@@ -309,7 +309,9 @@ function askForServerSideOpts() {
         this.packageName = this.jhipsterConfig.packageName = props.packageName;
         this.serverPort = this.jhipsterConfig.serverPort = props.serverPort || '8080';
         this.cacheProvider = this.jhipsterConfig.cacheProvider = !reactive ? props.cacheProvider : 'no';
-        this.enableHibernateCache = this.jhipsterConfig.enableHibernateCache = !['no', 'memcached'].includes(this.cacheProvider) ? props.enableHibernateCache : false;
+        this.enableHibernateCache = this.jhipsterConfig.enableHibernateCache = !['no', 'memcached'].includes(this.cacheProvider)
+            ? props.enableHibernateCache
+            : false;
```
Comment (mshima) [inline generators/server/prompts.js:314]: @MarlonLuan can you try this instead?
The condition is not complete, so let's force false instead of undefined.
```suggestion
        this.enableHibernateCache = this.jhipsterConfig.enableHibernateCache = !!props.enableHibernateCache;
```

**Review by mshima — CHANGES_REQUESTED** [review]

File: generators/server/prompts.js (hunk 1 above)
Comment (MarlonLuan) [reply generators/server/prompts.js:314]: Replace all the current code? And in relation to the condition
```javascript
cacheProvider == 'no'
```
, where it should be considered?

Comment (mshima) [reply generators/server/prompts.js:314]: When cacheProvider is `no`, enableHibernateCache should be `undefined`, double negate should convert `undefined` to `false`.

Comment (MarlonLuan) [reply generators/server/prompts.js:314]: I didn't understand the need for the change, according to the current code,:

when "cacheProvider == no" --> "enableHibernateCache == false", 

when "cacheProvider !== no" --> "enableHibernateCache ==  value of props.enableHibernateCache (informed by the prompt)", 

props.enableHibernateCache will not be undefined

Comment (mshima) [reply generators/server/prompts.js:314]: The condition to skip enableHibernateCache question is more complex then your condition.
https://github.com/jhipster/generator-jhipster/blob/8a1f652d2e1ad127631a8dc23a42cbc4ae460d07/generators/server/prompts.js#L278-L281.

In some cases, the answered value will be overridden by the condition.

**Comment by mshima** [comment]
@MarlonLuan can you confirm this new approach fixes the bug?

**Comment by MarlonLuan** [comment]
> @MarlonLuan can you confirm this new approach fixes the bug?

Yes, the bug was fixed

**Review by mshima — APPROVED** [review]

**Comment by mshima** [comment]
Thanks @MarlonLuan
