### PR TITLE
fix generation of non-Long pk fields in various places and added support for custom id generation in reactive stack

### LINKED ISSUE #17835: UUID id fields generate autoincrement attribute which fails application startup
##### **Overview of the issue**

For id fields having UUID type, the generator generates `autoIncrement="true"` in my configuration, even though during startup of such an application, an error is being produced:

This is produced in the liquibase entity changelog for adding the field
```
            <column name="uuid" type="${uuidType}" autoIncrement="true">
                <constraints primaryKey="true" nullable="false"/>
            </column>
```

even though in master.xml a varchar field is produced. 

```
    <property name="uuidType" value="varchar(36)" dbms="h2, mysql, mariadb"/>
```

So during startup, such an error is produced:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [de/mt/dataview/config/LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: Property [autoIncrement] was not found for object type [liquibase.datatype.core.VarcharType]
```

##### **Motivation for or Use Case**

Application will not start up. 

##### **Related issues**
#17833

##### **Suggest a Fix**
I think, it is related to the reactive branch in this if-else statement:

https://github.com/jhipster/generator-jhipster/blob/2dc5a892a8fbf216f78372058974c663078c822f/utils/field.js#L279-L284

where the liquibaseAutoIncrement value is statically set to true. Seems to be just not considered in d63b9d695573433977473e6503df7e7fc14704f3 

##### **JHipster Version(s)**
7.6.0 (latest SNAPSHOT now, since other bugs in the last release cover up this one, e.g. #17833, #17823)

##### **JHipster Version(s)**

```
dataview@0.0.1-SNAPSHOT C:\Users\jwedding\git\mt\demo3
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "oauth2",
    "baseName": "dataview",
    "blueprints": [],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1639736978010,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": ["DataStream"],
    "entitySuffix": "",
    "incrementalChangelog": true,
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.6.0",
    "languages": ["de", "en"],
    "lastLiquibaseTimestamp": 1644410794000,
    "messageBroker": false,
    "nativeLanguage": "de",
    "otherModules": [],
    "packageName": "de.mt.dataview",
    "pages": [],
    "prodDatabaseType": "mysql",
    "reactive": true,
    "rememberMeKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "searchEngine": false,
    "serverPort": "8080",
    "serverSideOptions": [],
    "serviceDiscoveryType": "no",
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipJhipsterDependencies": true,
    "skipUserManagement": true,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity DataStream {
  @Id uuid UUID
}
paginate DataStream with pagination
service DataStream with serviceImpl

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode)

git version 2.35.1.windows.2

node: v14.18.2

npm: 6.14.15

Docker version 20.10.9, build c2ea9bc

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by OmarHawk**
fixes #17835 

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

**Review by mshima — CHANGES_REQUESTED** [review]
Really nice.

**Comment by OmarHawk** [comment]
> Really nice.

Will finish tomorrow. 😅

File: generators/entity-server/templates/src/main/java/package/domain/EntityCallback.java.jhi.spring_data_reactive.ejs [hunk 1]
```diff
@@ -0,0 +1,37 @@
+<%#
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/templates/src/main/java/package/domain/EntityCallback.java.jhi.spring_data_reactive.ejs:1]: And put it into te persistable Template? I still think, it makes sense to have the Callbacks to support the pepole who do "more" with the generated applications.

File: generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.spring_data_reactive.ejs [hunk 2]
```diff
@@ -112,3 +121,28 @@ import org.springframework.data.relational.core.mapping.Table;
...
+  <&_ if (fragment.classAdditionalFieldsSection) { -&>
+    @Transient
+    private boolean isNew;
+  <&_ } -&>
+  <&_ if (fragment.classAdditionalFieldsMethodsSection) { -&>
+
+    @Override
+    public <%= primaryKey.type %> getId() {
+        return this.<%= primaryKey.name %>;
+    }
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.spring_data_reactive.ejs:135]: Changed. Thanks for the hint. :-)

File: generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs [hunk 3]
```diff
@@ -253,6 +253,11 @@ public class <%= entityClass %>Resource {
       <%_ } _%>
     <% } %>
   <%_ } _%>
+  <%_ if (requiresPersistableImplementation) { _%>
+
+      <%= entityInstance %>.setIsNew();
+
+  <%_ } _%>
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs:260]: This will then also be called for normal save operations (creating new entity) and not just for updates - which would then produce an error as it will try to perform an UPDATE command instead...

File: generators/entity-server/files.js [hunk 4]
```diff
@@ -78,6 +78,16 @@ const serverFiles = {
         },
       ],
     },
+    {
+      condition: generator => generator.databaseTypeSql && generator.reactive && generator.requiresPersistableImplementation,
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/files.js:92]: Extracted into own template

File: generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.spring_data_reactive.ejs [hunk 5]
```diff
@@ -21,6 +21,9 @@
  EJS fragments will process % delimiter tags in template and & delimiter tags in the merge process.
 -%>
 <&_ if (fragment.importSection) { -&>
+  <%_ if (requiresPersistableImplementation) { _%>
+    import org.springframework.data.domain.Persistable;
+  <%_ } _%>
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.spring_data_reactive.ejs]: Extracted into own template

File: generators/entity-server/files.js [hunk 6]
```diff
@@ -78,6 +78,16 @@ const serverFiles = {
...
+      path: SERVER_MAIN_SRC_DIR,
+      templates: [
+        {
+          file: 'package/domain/EntityCallback.java.jhi.spring_data_reactive',
+          renameTo: generator => `${generator.entityAbsoluteFolder}/domain/${generator.persistClass}Callback.java`,
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/files.js:97]: Extracted into own template

File: generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs (hunk 3 above)
[the remark this answers is not in the document]
Comment (mshima) [reply generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs:260]: You won’t manage to access the persistable object from here using dto.
0B519680-6B55-4161-A2B1-F6490036D945

[the remark this answers is not in the document]
Comment (mshima) [reply generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs:260]: Adjusted the suggestion

File: generators/entity-server/templates/src/main/java/package/domain/EntityCallback.java.jhi.spring_data_reactive.ejs (hunk 1 above)
[the remark this answers is not in the document]
Comment (mshima) [reply generators/entity-server/templates/src/main/java/package/domain/EntityCallback.java.jhi.spring_data_reactive.ejs:1]: If it’s not needed, we should not generate.
I don’t think it’s useful enough, and can be done using aspect only once instead of once per entity.

[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/templates/src/main/java/package/domain/EntityCallback.java.jhi.spring_data_reactive.ejs:1]: OK, understood. Will remove it again. :-)

File: generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs [hunk 7]
```diff
@@ -112,7 +112,7 @@ public class <%= serviceClassName %><% if (serviceImpl) { %> implements <%= enti
 <%_ } _%>
     public <% if (reactive) { %>Mono<<% } %><%= instanceType %><% if (reactive) { %>><% } %> save(<%= instanceType %> <%= instanceName %>) {
         log.debug("Request to save <%= entityClass %> : {}", <%= instanceName %>);
-<%- include('/partials/save_template', {asEntity, asDto, viaService: false, returnDirectly: true, isUsingMapsId: isUsingMapsId, mapsIdAssoc: mapsIdAssoc, isController: false}); -%>
+<%- include('/partials/save_template', {asEntity, asDto, viaService: false, returnDirectly: true, isUsingMapsId: isUsingMapsId, mapsIdAssoc: mapsIdAssoc, isController: false, isPersisted: false}); -%>
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs:115]:
```suggestion
<%- include('/partials/save_template', {asEntity, asDto, viaService: false, returnDirectly: true, isUsingMapsId: isUsingMapsId, mapsIdAssoc: mapsIdAssoc, isController: false, isPersisted: requiresPersistableImplementation}); -%>
```

File: generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs [hunk 8]
```diff
@@ -253,7 +253,7 @@ public class <%= entityClass %>Resource {
       <%_ } _%>
     <% } %>
   <%_ } _%>
-<%- include('/partials/save_template', {asEntity, asDto, viaService: viaService, returnDirectly: false, isUsingMapsId: false, mapsIdAssoc: mapsIdAssoc}); -%>
+<%- include('/partials/save_template', {asEntity, asDto, viaService: viaService, returnDirectly: false, isUsingMapsId: false, mapsIdAssoc: mapsIdAssoc, isPersisted: requiresPersistableImplementation}); -%>
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs:256]:
```suggestion
<%- include('/partials/save_template', {asEntity, asDto, viaService: viaService, returnDirectly: false, isUsingMapsId: false, mapsIdAssoc: mapsIdAssoc, isPersisted: !viaService && requiresPersistableImplementation}); -%>
```

**Review by mshima — COMMENTED** [review]
I will edit a file directly because a review will not be easy.

File: generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs (hunk 7 above)
Comment (OmarHawk) [reply generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs:115]: thank you :-)

**Comment by OmarHawk** [comment]
There is a bit of back and forth, hope that's OK, as this is my first bigger getting into touch with the code

**Comment by mshima** [comment]
This will require more work, there is only save at the service layer.
I will think about this a little more.

**Comment by OmarHawk** [comment]
> This will require more work, there is only save at the service layer. I will think about this a little more.

You mean, there is no actual update method, therefore in some cases (dto based branch), it will always create a new entity. Ideally, we could somehow pass the information regarding isPersisted together with the dto, but we also would need to make sure, it is nothing a user can actually set. Or, we would always have to override the value on the DTO, so that the value that may be set from the frontend isalways ignored.

**Comment by OmarHawk** [comment]
> > This will require more work, there is only save at the service layer. I will think about this a little more.
> 
> You mean, there is no actual update method, therefore in some cases (dto based branch), it will always create a new entity.
> 
> Ideally, we could somehow pass the information regarding isPersisted together with the dto, but we also would need to make sure, it is nothing a user can actually set. Or, we would always have to override the value on the DTO, so that the value that may be set from the frontend isalways ignored.
> 
> Or an actual update method would be needed in the service layer, where the setPersisted() call is then being performed...

@mshima - What do you think, does making use of a separate update method make sense for you? If so, I'd try to take care of that and enhance the PR to save the time on your side.

**Comment by mshima** [comment]
> What do you think, does making use of a separate update method make sense for you?

Yes, it does.
I think this is the best approach.
We have different methods for reactive too.

**Comment by OmarHawk** [comment]
FYI: I'll try to go on with this this week and introduce a separate update method that allows us to distinguish whether we need to set isPersisted or not

**Review by mshima — CHANGES_REQUESTED** [review]

File: generators/entity-server/files.js [hunk 9]
```diff
@@ -78,6 +78,36 @@ const serverFiles = {
...
+          renameTo: generator => `${generator.entityAbsoluteFolder}/domain/${generator.persistClass}.java.jhi.spring_data_persistable`,
+        },
+      ],
+    },
+    {
+      condition: generator => generator.databaseTypeSql && generator.reactive && generator.requiresPersistableImplementation,
+      path: SERVER_MAIN_SRC_DIR,
+      templates: [
+        {
+          file: 'package/domain/EntityCallback.java.jhi.spring_data_reactive',
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/files.js]: Changed

File: generators/entity-server/templates/partials/update_template.ejs [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+
+if (isUsingMapsId) {
+    mapsIdEntityInstance = mapsIdAssoc.otherEntityNameCapitalized.charAt(0).toLowerCase() + mapsIdAssoc.otherEntityNameCapitalized.slice(1);
+    mapsIdRepoInstance = `${mapsIdEntityInstance}Repository`;
+    otherEntityName = mapsIdAssoc.otherEntityName;
+  if (isController) { _%>
+        if (Objects.isNull(<%= instanceName %>.get<%= mapsIdAssoc.relationshipNameCapitalized %>())) {
+            throw new BadRequestAlertException("Invalid association value provided", ENTITY_NAME, "null");
+        }
+  <%_ } _%>
```
[the remark this answers is not in the document]
Comment (OmarHawk) [reply generators/entity-server/templates/partials/update_template.ejs:39]: true. I just used the save_template as a base - so, ideally, we would do similar changes in a separate PR then as well. Will change it for the update template

**Comment by OmarHawk** [comment]
very nice. That test discovered some more compilation errors. :-)

**Comment by OmarHawk** [comment]
meh, there where even more bugs behind those compilation errors - so unexpected (not) :(

**Comment by OmarHawk** [comment]
I already reduced the amounts of test failures in the reactive area (custom id was not implemented at all there!), but I seemed to have caused in the Angular area some issues. Will check that as well, but want to let you know, that I'm still on it.

**Comment by OmarHawk** [comment]
Hi @mshima (and other jhipsters) the currently failing tests (BadSQLGrammar and all the others in my added test case) are due the following issue:

https://github.com/spring-projects/spring-data-relational/issues/777

We have various Entities, that are having solely null values during initial INSERT, and such a save operation currently produces INSERT statements like 

`INSERT INTO entity_custom_id_dto_rel VALUES()`

The only way to get this resolved will be an update of dependencies, once this will be released with spring-data-r2dbc and  especially with the transitive dependency spring-data-relational which has the actual issue. So, this Pull request will live for a little longer and probably will require also a Spring Boot update then, as this is in the end a transitive dependency.  :(

grafik


I will keep it up-to-date from time to time.

**Comment by mshima** [comment]
I think is error happens with postgresql only.
Maybe related to this workaround:
https://github.com/jhipster/generator-jhipster/blob/ceef7340d4b2b2c1827a4c043b13dd1f95c4edf3/generators/entity-client/index.js#L84-L85

Switched to mysql to test.

**Comment by mshima** [comment]
Close/reopen for a new merge point with react fixed.

**Comment by mshima** [comment]
@OmarHawk we could drop the ci test and review to get merged without it.
If you agree I can review it.

**Comment by OmarHawk** [comment]
Mh, sure, but in the end, I would rather have the test case green, also to avoid future regressions. ;-)

**Review by mshima — CHANGES_REQUESTED** [review]
We should prefer prepared join column names over calculating it at the template.
It allow us to apply rules like database max column name length.

**Comment by mraible** [comment]
Please resolve conflicts.

**Comment by OmarHawk** [comment]
@mshima : that method _getJoinColumnName is not used anywhere anymore. Can't we just remove it overall (and not only in v8)? Rest of the review comments have been integrated & conflicts have been resolved.

**Comment by mshima** [comment]
Keep the method, blueprints sometimes duplicates the templates.
Let’s not break them.
Just revert the changes.

File: .github/workflows/webflux.yml [hunk 11]
```diff
@@ -87,6 +87,7 @@ jobs:
           - webflux-psql-additional
           - webflux-gradle-session-mariadb-es
           - webflux-couchbase
+          - webflux-react
```
Comment (mshima) [inline .github/workflows/webflux.yml:90]:
```suggestion
```

File: .github/workflows/webflux.yml [hunk 12]
```diff
@@ -125,6 +126,14 @@ jobs:
...
             e2e: 1
             testcontainers: 1
+          - suite: webflux-react
+            app-sample: webflux-react
+            jdl-entity: '*'
+            environment: prod
+            war: 0
+            e2e: 1
+            testcontainers: 1
+            sonar-analyse: 'false'
```
Comment (mshima) [inline .github/workflows/webflux.yml:136]:
```suggestion
```

File: .github/workflows/webflux.yml [hunk 13]
```diff
@@ -140,6 +149,7 @@ jobs:
         with:
           entities-sample: ${{ matrix.entity || 'none' }}
           jdl-sample: ${{ matrix.jdl-sample || '' }}
+          jdl-entities-sample: ${{ matrix.jdl-entity }}
```
Comment (mshima) [inline .github/workflows/webflux.yml:152]:
```suggestion
```

**Review by mshima — COMMENTED** [review]
Drop failing workflow for now

**Review by mshima — DISMISSED** [review]
Drop the test from the workflow, the sample can be kept.
I think it can be merged once CI passes.

**Comment by OmarHawk** [comment]
I have rebased once more and then reverted the failing workflow in a separate commit, so we may be able to revert this commit once it is supposed to work (Spring Boot 2.7.x)

**Comment by mshima** [comment]
Still needs some adjusts with updatable entities. Will do it soon.

File: generators/entity-server/templates/partials/update_template.ejs [hunk 14]
```diff
@@ -0,0 +1,79 @@
...
+-%>
+<%_ const instanceType = restClass;
+const instanceName = restInstance;
+const mapper = entityInstance  + 'Mapper';
+const dtoToEntity = mapper + '.' + 'toEntity';
+const entityToDto = mapper + '.' + 'toDto';
+const entityToDtoReference = mapper + '::' + 'toDto';
+const returnPrefix = (returnDirectly && !searchEngineElasticsearch) ? 'return' : instanceType + ' result =';
+// if the entity has no fields except the id a call to save will produce an exception
+const needsSaveCall = fields.filter(field => !field.id && !field.transient).length > 0;
```
Comment (mshima) [inline generators/entity-server/templates/partials/update_template.ejs:27]:
```suggestion
```

File: generators/entity-server/templates/partials/update_template.ejs [hunk 15]
```diff
@@ -0,0 +1,79 @@
...
+    <%_ resultEntity = persistInstance; _%>
+        <%= persistClass %> <%= persistInstance %> = <%= dtoToEntity %>(<%= instanceName %>);
+    <%_ if (isPersisted) { _%>
+        <%= persistInstance %>.setIsPersisted();
+    <%_ } _%>
+    <%_ if (isUsingMapsId) { _%>
+        <%= mapsIdAssoc.otherEntity.primaryKey.type %> <%= otherEntityName %>Id = <%= instanceName %>.get<%= mapsIdAssoc.relationshipNameCapitalized %>().get<%= primaryKey.nameCapitalized %>();
+        <%= mapsIdRepoInstance %>.findById(<%= otherEntityName %>Id).ifPresent(<%= persistInstance %>::<%_ if (!fluentMethods) { _%>set<%= mapsIdAssoc.relationshipNameCapitalized %> <%_ } else { _%><%= mapsIdAssoc.relationshipName %><%_ } _%>);
+    <%_ } _%>
+    <%_ if (needsSaveCall) { _%>
```
Comment (mshima) [inline generators/entity-server/templates/partials/update_template.ejs:49]:
```suggestion
    <%_ if (updatableEntity) { _%>
```

File: generators/entity-server/templates/partials/update_template.ejs [hunk 16]
```diff
@@ -0,0 +1,79 @@
...
+  <%_ } else {
+      resultEntity = 'result'; _%>
+    <%_ if (isUsingMapsId) { _%>
+        <%= mapsIdAssoc.otherEntity.primaryKey.type %> <%= otherEntityName %>Id = <%= instanceName %>.get<%= mapsIdAssoc.relationshipNameCapitalized %>().get<%= primaryKey.nameCapitalized %>();
+        <%= mapsIdRepoInstance %>.findById(<%= otherEntityName %>Id).ifPresent(<%= instanceName %>::<%_ if (!fluentMethods) { _%>set<%= mapsIdAssoc.relationshipNameCapitalized %> <%_ } else { _%><%= otherEntityName %><%_ } _%>);
+    <%_ } _%>
+    <%_ if (isPersisted) { _%>
+        <%= persistInstance %>.setIsPersisted();
+    <%_ } _%>
+    <%_ if (needsSaveCall) { _%>
```
Comment (mshima) [inline generators/entity-server/templates/partials/update_template.ejs:64]:
```suggestion
    <%_ if (updatableEntity) { _%>
```

File: generators/entity-server/templates/reactive/partials/update_template.ejs [hunk 17]
```diff
@@ -0,0 +1,43 @@
...
+ See the License for the specific language governing permissions and
+ limitations under the License.
+-%>
+<%_ const instanceType = restClass;
+const instanceName = restInstance;
+const mapper = entityInstance  + 'Mapper';
+const dtoToEntity = mapper + '.' + 'toEntity';
+const entityToDtoReference = mapper + '::' + 'toDto';
+// if the entity has no fields except the id a call to save will produce an exception
+const needsSaveCall = fields.filter(field => !field.id && !field.transient).length > 0;
```
Comment (mshima) [inline generators/entity-server/templates/reactive/partials/update_template.ejs:25]:
```suggestion
```

File: generators/entity-server/templates/reactive/partials/update_template.ejs [hunk 18]
```diff
@@ -0,0 +1,43 @@
...
+_%>
+<%_ if (viaService) { _%>
+        return <%= entityInstance %>Service.update(<%= instanceName %>)
+<%_ } else { _%>
+    <%_ if (needsSaveCall) { _%>
```
Comment (mshima) [inline generators/entity-server/templates/reactive/partials/update_template.ejs:30]:
```suggestion
    <%_ if (updatableEntity) { _%>
```

File: generators/entity-server/templates/src/main/java/package/common/patch_template.ejs [hunk 19]
```diff
@@ -49,7 +49,11 @@ _%>
   <% } %>
     return existing<%= entityClass %>;
     })
-    .<%= mapOrFlatMap %>(<%= entityInstance %>Repository::save)
+  <%_
+    // avoid exception if no fields need to be saved (as nothing is to be updated)
+    const hasUpdatableFields = fields.filter(field => !field.id && !field.transient).length > 0;
+  _%>
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/common/patch_template.ejs:55]:
```suggestion
```

File: generators/entity-server/templates/src/main/java/package/common/patch_template.ejs [hunk 20]
```diff
@@ -49,7 +49,11 @@ _%>
...
+  <% if (!hasUpdatableFields) { %>// <%} %>.<%= mapOrFlatMap %>(<%= entityInstance %>Repository::save)
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/common/patch_template.ejs:56]:
```suggestion
  <% if (!updatableEntity) { %>// <%} %>.<%= mapOrFlatMap %>(<%= entityInstance %>Repository::save)
```

File: generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs [hunk 21]
```diff
@@ -112,7 +112,23 @@ public class <%= serviceClassName %><% if (serviceImpl) { %> implements <%= enti
...
+     * @param <%= instanceName %> the entity to save.
+     * @return the persisted entity.
+    */
+<%_ } _%>
+<%_ if (serviceImpl) { _%>
+    @Override
+<%_ } _%>
+    public <% if (reactive) { %>Mono<<% } %><%= instanceType %><% if (reactive) { %>><% } %> update(<%= instanceType %> <%= instanceName %>) {
+        log.debug("Request to save <%= entityClass %> : {}", <%= instanceName %>);
+<%- include('/partials/update_template', {asEntity, asDto, viaService: false, returnDirectly: true, isUsingMapsId: isUsingMapsId, mapsIdAssoc: mapsIdAssoc, isController: false, isPersisted: requiresPersistableImplementation}); -%>
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/service/impl/EntityServiceImpl.java.ejs:131]:
```suggestion
<%- include('/partials/update_template', {updatableEntity, viaService: false, returnDirectly: true, isUsingMapsId: isUsingMapsId, mapsIdAssoc: mapsIdAssoc, isController: false, isPersisted: requiresPersistableImplementation}); -%>
```

File: generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs [hunk 22]
```diff
@@ -253,7 +255,7 @@ public class <%= entityClass %>Resource {
       <%_ } _%>
     <% } %>
   <%_ } _%>
-<%- include('/partials/save_template', {asEntity, asDto, viaService: viaService, returnDirectly: false, isUsingMapsId: false, mapsIdAssoc: mapsIdAssoc}); -%>
+<%- include('/partials/update_template', {asEntity, asDto, viaService: viaService, returnDirectly: false, isUsingMapsId: false, mapsIdAssoc: mapsIdAssoc, isController: true, isPersisted: requiresPersistableImplementation}); -%>
```
Comment (mshima) [inline generators/entity-server/templates/src/main/java/package/web/rest/EntityResource.java.ejs:258]:
```suggestion
<%- include('/partials/update_template', {updatableEntity, viaService: viaService, returnDirectly: false, isUsingMapsId: false, mapsIdAssoc: mapsIdAssoc, isController: true, isPersisted: requiresPersistableImplementation}); -%>
```

**Comment by OmarHawk** [comment]
now, everythings green

thanks a lot @mshima for your help :-)

**Comment by OmarHawk** [comment]
@mshima : I think, there was a bug bounty on this one. 
What do you think, would you be OK with sharing that? You probably spent also quite some time on it. I myself would donate my part anyway, as I didn't do it for the bug bounty. ;-)

**Comment by mshima** [comment]
@OmarHawk please take the full bounty and fell free to donate or use it.
It's a pleasure to review PRs, and this may keep the contributor motivated to contribute more.

**Comment by OmarHawk** [comment]
> @OmarHawk please take the full bounty and fell free to donate or use it. It's a pleasure to review PRs, and this may keep the contributor motivated to contribute more.

Ok, I did so  ;-). Thanks a lot.

https://opencollective.com/generator-jhipster/expenses/69673

**Comment by mshima** [comment]
cc @pascalgrimaud

**Comment by pascalgrimaud** [comment]
@OmarHawk : approved :)

**Comment by yelhouti** [comment]
@OmarHawk @mshima I have been rebasing a blueprint, and found all these changes, could any of you please explain why this was added instead of relying on the default behavior of spring data (checking if exists by checking the cache/db using the key).
