### PR TITLE
wrap non long ids with ' to have valid sql where clause

### LINKED ISSUE #18804: Bad SQL grammar is thrown for all entities with string ID types
Hello everyone,

##### **Overview of the issue**
Due to the fix for [SQL Injection in Reactive project](https://github.com/jhipster/generator-jhipster/issues/18269) included with Release 7.8.1 (2022-04-07) where jhipster has replaced the Criteria with Condition in the EntityManager bean. E.g. 

Prior to version 7.8.1

```java
public class EntityManager {
(...)	
    /**
     * Creates an SQL select statement from the given fragment and pagination parameters.
     * @param selectFrom a representation of a select statement.
     * @param entityType the entity type which holds the table name.
     * @param pageable page parameter, or null, if everything needs to be returned
     * @return sql select statement
     */
    public String createSelect(SelectFromAndJoin selectFrom, Class<?> entityType, Pageable pageable, Criteria criteria) {
        if (pageable != null) {
            if (criteria != null) {
                return createSelectImpl(
                        selectFrom.limitOffset(pageable.getPageSize(), pageable.getOffset()).where(Conditions.just(criteria.toString())),
                        entityType,
                        pageable.getSort()
                );
            } else {
                return createSelectImpl(
                        selectFrom.limitOffset(pageable.getPageSize(), pageable.getOffset()),
                        entityType,
                        pageable.getSort()
                );
            }
        } else {
            if (criteria != null) {
                return createSelectImpl(selectFrom.where(Conditions.just(criteria.toString())), entityType, null);
            } else {
                return createSelectImpl(selectFrom, entityType, null);
            }
        }
    }
(...)
```

And now
```java
public class EntityManager {
(...)
    /**
     * Creates an SQL select statement from the given fragment and pagination parameters.
     * @param selectFrom a representation of a select statement.
     * @param entityType the entity type which holds the table name.
     * @param pageable page parameter, or null, if everything needs to be returned.
     * @param where condition or null. The condition to apply as where clause.
     * @return sql select statement
     */
    public String createSelect(SelectFromAndJoin selectFrom, Class<?> entityType, Pageable pageable, Condition where) {
        if (pageable != null) {
            if (where != null) {
                return createSelectImpl(
                    selectFrom.limitOffset(pageable.getPageSize(), pageable.getOffset()).where(where),
                    entityType,
                    pageable.getSort()
                );
            } else {
                return createSelectImpl(
                    selectFrom.limitOffset(pageable.getPageSize(), pageable.getOffset()),
                    entityType,
                    pageable.getSort()
                );
            }
        } else {
            if (where != null) {
                return createSelectImpl(selectFrom.where(where), entityType, null);
            } else {
                return createSelectImpl(selectFrom, entityType, null);
            }
        }
    }
(...)
```
the application will throw BadSqlGrammarException each time an entity is accessed by its ID.

##### **Motivation for or Use Case**
n.a.

##### **Reproduce the error**
Generate project with reactive with Spring WebFlux and set the database type to SQL

##### **Related issues**
[SQL Injection in Reactive project](https://github.com/jhipster/generator-jhipster/issues/18269)

##### **Suggest a Fix**
We could generate ExampleRepositoryInternalImpl to wrap with single quote all entities with string type IDs, something like this:
```java
class ExampleRepositoryInternalImpl extends...
(...)
    @Override
    public Mono<Example> findById(String id) {
        Comparison whereClause = Conditions.isEqual(entityTable.column("id"), Conditions.just("'" + id.toString() + "'"));
        return createQuery(null, whereClause).one();
    }
(...)
```
Despite the idea, we cannot forget that whenever we use the Condition API to filter a string type, we have to wrap the field with single quotes.

##### **JHipster Version(s)**
7.8.1 (2022-04-07)

##### **JHipster configuration**

```
reactive with Spring WebFlux? Yes
type of database? SQL
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
JDL
```
entity Example {
    id String
    name String
}
```

##### **Browsers and Operating System**
n.a.

### PR DESCRIPTION
**Pull request by atomfrede**
This PR ensures non long ids are correctly wrapper with `'`. Used following entities to test it out:

```
entity Example {
    id String
    name String
}

entity Example2 {
    name String
}

entity Example3 {
    id UUID
    name String
}
```

Both `Example` and `Example3` need the wrapping.

closes #18804

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs [hunk 1]
```diff
@@ -148,7 +149,11 @@ _%>
 
     @Override
     public Mono<<%= persistClass %>> findById(<%= primaryKey.type %> id) {
-        Comparison whereClause = Conditions.isEqual(entityTable.column("<%= primaryKey.fields[0].columnName %>"), Conditions.just(id.toString()));
+<%_ if (primaryKey.type != 'Long') {  _%>
+    Comparison whereClause = Conditions.isEqual(entityTable.column("<%= primaryKey.fields[0].columnName %>"), Conditions.just(StringUtils.wrap(id.toString(), "'")));
```
Comment (DanielFran) [inline generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs:153]: indentation

File: generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs [hunk 2]
```diff
@@ -148,7 +149,11 @@ _%>
...
+<%_ } else { _%>
+    Comparison whereClause = Conditions.isEqual(entityTable.column("<%= primaryKey.fields[0].columnName %>"), Conditions.just(id.toString()));
```
Comment (DanielFran) [inline generators/entity-server/templates/src/main/java/package/repository/EntityRepositoryInternalImpl_reactive.java.ejs:155]: indentation

**Review by DanielFran — APPROVED** [review]
Just somes indentation to fix

**Comment by atomfrede** [comment]
bounty claimed https://opencollective.com/generator-jhipster/expenses/90918

**Comment by DanielFran** [comment]
@atomfrede approved
