### PR TITLE
Fix the --skip-server option

### LINKED ISSUE #6389: skip-server option and missing code in security module
Overview of the issue

When I am trying to use `--skip-server` option many issues happen in Security model when trying to build the system.

~~~
ERROR in [at-loader] ./src/main/webapp/app/blocks/interceptor/http.provider.ts:23:17
TS2304: Cannot find name 'AuthExpiredInterceptor'.

ERROR in [at-loader] ./src/main/webapp/app/shared/login/login.service.ts:19:18
TS2339: Property 'authServerProvider' does not exist on type 'LoginService'.

ERROR in [at-loader] ./src/main/webapp/app/shared/login/login.service.ts:38:21
TS2339: Property 'authServerProvider' does not exist on type 'LoginService'.

ERROR in [at-loader] ./src/main/webapp/app/shared/login/login.service.ts:42:14
TS2339: Property 'authServerProvider' does not exist on type 'LoginService'.**
~~~

After some debugging, I found that we are using some Services thas should not be in the code if we are 

using --skip-server option like below in 'login-service.ts':

`if (this.principal.isAuthenticated()) { this.authServerProvider.logout().subscribe(); }`

because we have condition that will remove authServerProvider from the class :

`<%_ if (!skipServer) { _%> private authServerProvider: AuthServerProvider <%_ } _%>`

P.S : not only this file there are other files which have the same issue.

##### **Reproduce the error**
`jhipster --skip-server --auth=jwt --db=sql `

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/5429

##### **Suggest a Fix**
none

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
koptan@0.0.0 C:\JS\jh-frontend
+-- generator-jhipster@4.8.2
`-- UNMET PEER DEPENDENCY popper.js@^1.11.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.8.2",
    "baseName": "koptan",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "npm",
    "authenticationType": "jwt",
    "databaseType": "sql",
    "devDatabaseType": "sql",
    "prodDatabaseType": "sql",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipServer": true,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ar-ly"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>
<pre>
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.1.windows.1

node: v6.10.2

npm: 3.10.10

bower: 1.8.0

yeoman: 2.0.0

##### **Browsers and Operating System**
Windows 10 , Chrome

### PR DESCRIPTION
**Pull request by clarenced**
Fix #6389
remove the `skipServer` test in http.provider.ts and login.service.ts
Also set to true the default condition for `generator.skipServer`

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/client/files-angular.js [hunk 1]
```diff
@@ -150,7 +150,7 @@ const files = {
             ]
         },
         {
-            condition: generator => !generator.skipServer,
+            condition: generator => generator.skipServer,
```
Comment (ruddell) [inline generators/client/files-angular.js]: This will only generate the file when skipServer is true.  I believe you always want to copy the file, so it should be moved [up to here with the other interceptors](https://github.com/clarenced/generator-jhipster/blob/92c600803e67f45ed64c12d33379d55546da9abf/generators/client/files-angular.js#L142)

Comment (clarenced) [reply generators/client/files-angular.js]: OK

File: generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_http.provider.ts [hunk 2]
```diff
@@ -33,9 +33,7 @@ import { LoginModalService } from '../../shared/login/login-modal.service';
     <%_ } _%>
 import { StateStorageService } from '../../shared/auth/state-storage.service';
 <%_ } _%>
-<%_ if (!skipServer) { _%>
 import { AuthExpiredInterceptor } from './auth-expired.interceptor';
```
Comment (deepu105) [inline generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_http.provider.ts]: Not very sure of this, Probabaly its better to add an abstract `auth-expired.interceptor` and `AuthServerProvider` or to skip the code calling these form the login service when skipServer is enabled. I would prefer the second option

Comment (clarenced) [reply generators/client/templates/angular/src/main/webapp/app/blocks/interceptor/_http.provider.ts]: Hi @deepu105 , thx for your reply. I may be missing something here, but do we still have authentication when `skipServer` is enabled. ? Because the form login is always generated when the `authenticationType ` is different `oauth2` and the `authServerProvider` is always used to perform the authentication.

If it is mandatory, I would go with the 1st option you proposed.

File: generators/client/files-angular.js (hunk 1 above)
Comment (clarenced) [reply generators/client/files-angular.js]: @ruddell done

**Comment by rachidoulasri** [comment]
I think you are missing the provider for "`AuthServerProvider`" in _app.module.ts

> generator-jhipster/generators/client/templates/angular/src/main/webapp/app/_app.module.ts


maybe you should add the following lines
```
<%_ if (authenticationType !== 'jwt') { _%>
import { AuthServerProvider } from './shared/auth/auth-jwt.service'
<%_ } _%>
```

```
providers: [
        ProfileService,
        customHttpProvider(),
        PaginationConfig,
        UserRouteAccessService,
       <%_ if (authenticationType !== 'jwt') { _%>
       AuthServerProvider
       <%_ } _%>
    ],

```

**Comment by clarenced** [comment]
@jdubois I will make the changes as requested

**Comment by clarenced** [comment]
Hi @oulasri, I am missing something here, should the authenticationType `===` 'jwt' instead of `!==` ?

**Comment by oulasri** [comment]
Hi @clarenced, Yes, you're right, sorry it's an error on my part !

File: generators/client/templates/angular/src/main/webapp/app/_app.module.ts [hunk 3]
```diff
@@ -28,8 +28,10 @@ import { <%=angularXAppName%>AdminModule } from './admin/admin.module';
 <%_ if (authenticationType !== 'oauth2') { _%>
 import { <%=angularXAppName%>AccountModule } from './account/account.module';
 <%_ } _%>
+<%_ if (authenticationType !== 'jwt') { _%>
```
Comment (ruddell) [inline generators/client/templates/angular/src/main/webapp/app/_app.module.ts]: AuthServerProvider is listed in [`shared/shared.module.ts`](https://github.com/clarenced/generator-jhipster/blob/e8324351d0fc6669338b4ff5d7c6c1323e9b35fa/generators/client/templates/angular/src/main/webapp/app/shared/_shared.module.ts#L26-L28) instead of `app.module.ts`.  This way you also don't have to check the authentication type either. So changes needed:

 - Remove changes to `app.module.ts`
 - Remove `<%_ if (!skipServer) { _%>` around `AuthServerProvider` in `shared/shared.module.ts`

Comment (clarenced) [reply generators/client/templates/angular/src/main/webapp/app/_app.module.ts]: @ruddell OK I will do it

**Comment by ruddell** [comment]
Just tested and it looks good to me.  This is a big improvement for people separating their client and server using the `skip-server`/`skip-client` flags

Previous behavior of apps using skip-server:
 - yarn fails to compile project on generation
 - can not authenticate even when specifying authentication type

New behavior apps using skip-server :
 - yarn compiles project correctly
 - can authenticate out-of-the-box

**Comment by Alan759** [comment]
I still get the above errors with jHipster 4.10.2. when I generate the app using: 
jhipster --skip-server --with-entities --skip-user-management --auth=jwt --db=sql

Which release(and when) will this fix go into?
