### PR TITLE
fix: Fix cors warning in the OIDC flow

### LINKED ISSUE #10642: CORS preflight to Keycloak fails for unauthenticated user
##### **Overview of the issue**

In a newly generated Gateway application, when I open the start page as an unauthenticated user I get this error on the JS console in the (Chrome-)Browser:

Access to XMLHttpRequest at 'http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?response_type=code&client_id=web_app&scope=openid%20address%20email%20jhipster%20offline_access%20phone%20profile%20roles%20web-origins&state=wjBewVjlplTH6Fc1bmbG0eLRcdinutWx-IEG014ADDc%3D&redirect_uri=http://localhost:9000/login/oauth2/code/oidc' (redirected from 'http://localhost:9000/api/account') from origin 'http://localhost:9000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

##### **Motivation for or Use Case**

I can still login and everything seems to work fine. However this error output on the JS console irritates me. Why does this error occur?

##### **Reproduce the error**

1.) Generate the Gateway (see below for .yo-rc.json file).
2.) run: docker-compose -f keycloak.yml up
3.) run: ./mvnw
4.) run: yarn start
5.) Check JS output on console.

##### **Related issues**

I found similar CORS issues but none had the exact same problem.

##### **Suggest a Fix**

As far as I understand the Keycloak answers to the preflight request with an empty header although the wildcard '*' is configured in Keycloak for web origins. So maybe it is a Keycloak issue? However it could also be a Spring configuration problem.  

##### **JHipster Version(s)**

6.3.1

We also have a project with version 4.14.1 where the same error occurs. In dev profile you need to add '/login' in webpack.dev.js for the dev server proxy.

##### **JHipster Version(s)**

```
gateway-test@0.0.1-SNAPSHOT 
└── generator-jhipster@6.3.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "gateway",
    "baseName": "gatewayTest",
    "packageName": "test",
    "packageFolder": "test",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "yarn",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "blueprints": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.17.1

node: v12.10.0

npm: 6.5.0

yeoman: 3.1.0

yarn: 1.17.3

Docker version 18.09.1, build 4c52b90

docker-compose version 1.23.2, build 1110ad0

##### **Browsers and Operating System**

OS: Windows 10 
Browser: Chrome 77, also occurs in Firefox 69, haven't checked other browsers

-   [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vishal423**
- Includes problem library authentication entry point in the OIDC flow to not redirect when an unauthenticated user tries to access a protected resource.
- Closes #10642 
---

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs [hunk 1]
```diff
@@ -217,10 +217,8 @@ public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
         <%_ } _%>
     <%_ } _%>
             .exceptionHandling()
-    <%_ if (authenticationType !== 'oauth2') { _%>
-            .authenticationEntryPoint(problemSupport)
-    <%_ } _%>
-            .accessDeniedHandler(problemSupport)
+                .authenticationEntryPoint(problemSupport)
```
Comment (pascalgrimaud) [inline generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs]: I think the indent is not correct

Comment (vishal423) [reply generators/server/templates/src/main/java/package/config/SecurityConfiguration.java.ejs]: `exceptionHandling()` method returns a reference of `ExceptionHandlingConfigurer` and `authenticationEntryPoint()` and `accessDeniedHandler()` are defined in that class. IMO, this is correct indentation.

**Comment by pascalgrimaud** [comment]
ok thanks @vishal423
