### PR TITLE
fix react microservice user relation request

### LINKED ISSUE #11792: User details are getting null || On React client
Hey @pascalgrimaud  ,  and @pascalgrimaud 

   I tried generate project with the JDL below, am facing an issue pulling the login "User" Details in "React + Gateway " microservices arch.
The User details are coming as **"null"**
 I discussed this issue [https://github.com/jhipster/jdl-samples/issues/24](url)  this morning, 

Mapping issue "one-to-one"  with React is still existing ..?

```
My local Jhipster version is
jhipster --version
INFO! Using JHipster version installed locally in current project's node_modules
6.8.0

```
Can you please help me in this.
--Thanks.

--JDL 

```
application {
  config {
    baseName gateway,
    packageName com.sample.gateway,
    applicationType gateway,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    serviceDiscoveryType eureka,
    testFrameworks [protractor],
    buildTool maven,
    clientFramework react,
    nativeLanguage en,
    languages [en, es] 
  }
  entities Members, Rewards, Address, Product, ProductCategory, ProductOrder, OrderItem, Invoice, Shipment
}

application {
  config {
    baseName school,
    packageName com.sample.users,
    applicationType microservice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    searchEngine elasticsearch,
    buildTool maven,
    serverPort 8081,
    serviceDiscoveryType eureka
  }
  entities Members, Rewards, Address
}

application {
  config {
    baseName store,
    packageName com.sample.store,
    applicationType microservice,
    authenticationType oauth2,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    searchEngine elasticsearch,
    buildTool maven,
    enableHibernateCache false,
    serverPort 8082,
    serviceDiscoveryType eureka
  }
 entities Product, ProductCategory, ProductOrder, OrderItem
}

application {
  config {
    baseName invoice,
    applicationType microservice,
    packageName com.sample.invoice,
    authenticationType oauth2,
    prodDatabaseType postgresql,
    buildTool maven,
    serverPort 8083,
    serviceDiscoveryType eureka
  }
  entities Invoice, Shipment
}


// Customer for the store
entity Members {
  firstName String required,
    lastName String required,
    gender Gender required,
    who Who required,
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
    age BigDecimal
}
// Address table for both Student and Faculty 
entity Address{
  addressLine1 String,
    addressLine2 String,
    city String,
    country String,
    primaryPhone String ,
    secondryPhone String
}
enum Gender {
  MALE, FEMALE, OTHER
}
enum Who {
  STUDENT, FACULTY, ADMIN
}
entity Rewards {
  facultyName String ,
        studentName String,
        timestamp ZonedDateTime required,
        rewardReceved BigDecimal,
        date Instant required,
        content TextBlob required
}
/**
 * Entities for store microservice
 */
// Product sold by the Online store 
entity Product {
  name String required
    description String
    price BigDecimal required min(0)
    size Size required
    image ImageBlob
}
enum Size {
  S, M, L, XL, XXL
}
entity ProductCategory {
  name String required,
    description String
}
entity ProductOrder {
  placedDate Instant required,
    email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/),
    status OrderStatus required,
    code String required,
    invoiceId Long,
    customer String required
}
enum OrderStatus {
  COMPLETED, PENDING, CANCELLED
}
entity OrderItem {
  quantity Integer required min(0)
    totalPrice BigDecimal required min(0)
    status OrderItemStatus required
}
enum OrderItemStatus {
  AVAILABLE, OUT_OF_STOCK, BACK_ORDER
}
/* Entities for Invoice microservice */
entity Invoice {
  code String required
    date Instant required
    details String
    status InvoiceStatus required
    paymentMethod PaymentMethod required
    paymentDate Instant required
    paymentAmount BigDecimal required
}
enum InvoiceStatus {
  PAID, ISSUED, CANCELLED
}
entity Shipment {
  trackingCode String
    date Instant required
    details String
}
enum PaymentMethod {
  CREDIT_CARD, CASH_ON_DELIVERY, PAYPAL
}
/* Entities for notification microservice */
entity Notification {
  date Instant required
    details String
    sentDate Instant required
    format NotificationType required
    userId Long required
    productId Long required
}
enum NotificationType {
  EMAIL, SMS, PARCEL
}
relationship ManyToOne {
  OrderItem{product(name) required} to Product
}
relationship OneToMany {
  Members{address} to Address{members(email) required} ,
  Members{rewards} to Rewards{members(email) required} ,
  ProductOrder{orderItem} to OrderItem{order(code) required} , 
  ProductCategory{product} to Product{productCategory(name)},
  Invoice{shipment} to Shipment{invoice(code) required}
}
relationship OneToOne {
  Members{user(login) required} to User
}
service Invoice, Shipment, Product, ProductCategory, ProductOrder, OrderItem with serviceClass
paginate Invoice, Shipment, Product, Members, ProductOrder, OrderItem with pagination
// MicroServices 
microservice Product, ProductOrder, ProductCategory, OrderItem with store
microservice Members, Address, Rewards with school
microservice Invoice, Shipment with invoice
microservice Notification with notification
// will be created under 'docker-compose' folder
deployment {
  deploymentType docker-compose
  appsFolders [gateway, school, store, invoice]
  dockerRepositoryName "govindraju9999"
  consoleOptions [zipkin]
}
```
 
**Exception in Logger**

`Bad Request: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<com.samplel.users.domain.Members> com.sample.users.web.rest.MembersResource.createMembers(com.sample.users.domain.Members) throws java.net.URISyntaxException: [Field error in object 'members' on field 'user': rejected value [null]; codes [NotNull.members.user,NotNull.user,NotNull.com.sample.users.domain.User,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [members.user,user]; arguments []; default message [user]]; default message [must not be null]]
`

### PR DESCRIPTION
**Pull request by ruddell**
Send the entire user object (including `login`) instead of just the `id` field

In Angular, we pass the whole User object `"user": {"id": "1", "login": "system", "firstName": "System" .... }`

In React we only pass the ID `"user":{"id":"1"}`, which results in an invalid User since login is a required field. This is because the value returned from the select box only returns the id.

Fixed by finding the `user` in `props.`user with the matching `id`.

Fix #11792

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
@ruddell I attempted to fix this in https://github.com/jhipster/generator-jhipster/pull/11317. Maybe I missed this part?

**Comment by MathieuAA** [comment]
This fails for a very simple app:
```
application {
  config {
    baseName testreact
    clientFramework react
  }
  entities Member
}

entity Member {
  firstName String required
  lastName String required
}

relationship OneToOne {
  Member{user(login) required} to User
}
```

**Comment by MathieuAA** [comment]
It won't work for monoliths because of the user id's type: we're comparing strings en numbers :(

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs [hunk 1]
```diff
@@ -204,7 +204,7 @@ export const <%= entityReactName %>Update = (props: I<%= entityReactName %>Updat
         <%_ }) _%>
       }
       <%_ if (uniqueRelationFields.has('users')) { _%>
-      entity.user = values.user;
+      entity.user = props.users.find(user => user.id === values.user.id);
```
Comment (MathieuAA) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:207]: `entity.user = users.find(user => user.id.toString() === values.user.id.toString());`

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs [hunk 2]
```diff
@@ -203,8 +203,8 @@ export const <%= entityReactName %>Update = (props: I<%= entityReactName %>Updat
         , <%= rel.relationshipFieldNamePlural %>: mapIdList(values.<%= rel.relationshipFieldNamePlural %>)
         <%_ }) _%>
       }
-      <%_ if (uniqueRelationFields.has('users')) { _%>
-      entity.user = values.user;
+      <%_ if (uniqueRelationFields.has('users') && dto !== 'mapstruct') { _%>
```
Comment (MathieuAA) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:206]: I don't get it, why `dto !== 'mapstruct'`?

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs [hunk 3]
```diff
@@ -203,8 +203,8 @@ export const <%= entityReactName %>Update = (props: I<%= entityReactName %>Updat
...
+      entity.user = users.find(user => user.id.toString() === entity.user.id.toString());
```
Comment (MathieuAA) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:207]: `entity.user` isn't set here, is it?

**Comment by ruddell** [comment]
@MathieuAA Thanks for catching that.

@mraible Your PR only changed the form when the relationship was not required, but the open issue has a required relationship.

With the latest changes, combos mostly work (there are a lot of them). I used the JDL:

<details>
<summary>JDL app/entity definitions</summary>

<pre>
application {
  config {
    baseName reactJwt
    clientFramework react
  }
  entities *
}

application {
  config {
    baseName reactOauth
    clientFramework react
    authenticationType oauth2
  }
  entities *
}

entity Member {
  firstName String
  lastName String
}
entity MemberDto {
  firstName String
  lastName String
}
entity MemberReq {
  firstName String
  lastName String
}
entity MemberDtoReq {
  firstName String
  lastName String
}

relationship OneToOne {
  Member{user(login)} to User
  MemberReq{user(login) required} to User

  MemberDto{user(login)} to User
  MemberDtoReq{user(login) required} to User
}

dto MemberDto, MemberDtoReq with mapstruct

</pre>
</details>

| Entity Info  | Works? |
| ------------- | ------------- |
| User Relation, Oauth2  | ✅  |
| User Relation, Oauth2, DTO  | ☑️   |
| User Relation required, Oauth2  | ✅  |
| User Relation required, Oauth2, DTO  | ✅ |
| User Relation, JWT  | ✅  |
| User Relation, JWT, DTO  | ✅  |
| User Relation required, JWT  | ✅  |
| User Relation required, JWT, DTO  | ✅  |

`User Relation, Oauth2, DTO` doesn't allow `""` as `userId` (comes from the form) so form submission fails. `null` has to be instead for it to work. Happens in `master`, so is unrelated to this PR

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs (hunk 3 above)
Comment (ruddell) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs]: That was an accidental change.  It should work either way but I reverted it

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs (hunk 2 above)
Comment (ruddell) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:206]: With DTOs, it uses a `userId` field rather than `user`.  It's not needed

**Comment by ruddell** [comment]
CI tests were failing because they use a different relationship name than `user` (for example, `oneToOneUser`). Also `TestTwoRelationshipsSameEntity.json` has two relations to `user`, but with different names ([code](https://github.com/jhipster/generator-jhipster/blob/bf70480d30f0be9e78280aac83f19cafdee1dc26/test-integration/samples/.jhipster/TestTwoRelationshipsSameEntity.json#L18-L29)), so we would need this line for both.  The only way I see to fix that is to loop through the relationships.

Since this is only needed for OAuth2 gateways, I added that as a condition as well.

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs [hunk 4]
```diff
@@ -203,8 +203,10 @@ export const <%= entityReactName %>Update = (props: I<%= entityReactName %>Updat
         , <%= rel.relationshipFieldNamePlural %>: mapIdList(values.<%= rel.relationshipFieldNamePlural %>)
         <%_ }) _%>
       }
-      <%_ if (uniqueRelationFields.has('users')) { _%>
-      entity.user = values.user;
+      <%_ if (uniqueRelationFields.has('users') && authenticationType === 'oauth2' && applicationType === 'gateway' && dto !== 'mapstruct') { _%>
+        <%_ relationships.filter(rel => rel.relationshipType === 'one-to-one' && rel.ownerSide === true && rel.otherEntityName === 'user').forEach(rel => { _%>
```
Comment (MathieuAA) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:207]: What about the case where we skip the user management? i.e. User <-> Whatever

Comment (MathieuAA) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:207]: `_%>\n<%_ ...`
There's no need for two tags in this case

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs [hunk 5]
```diff
@@ -203,8 +203,10 @@ export const <%= entityReactName %>Update = (props: I<%= entityReactName %>Updat
         , <%= rel.relationshipFieldNamePlural %>: mapIdList(values.<%= rel.relationshipFieldNamePlural %>)
         <%_ }) _%>
       }
-      <%_ if (uniqueRelationFields.has('users')) { _%>
-      entity.user = values.user;
+      <%_ if (uniqueRelationFields.has('users') && authenticationType === 'oauth2' && applicationType === 'gateway' && dto !== 'mapstruct') { _%>
```
Comment (MathieuAA) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:206]: Okay I'm lost. Why only a gateway app?

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs (hunk 4 above)
Comment (ruddell) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:207]: How would you have a relationship to User with skipUserManagement?  I tried adding `skipUserManagement true` and `entity User { login String }` to your monolith JDL above and the Java doesn't compile.

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs (hunk 5 above)
Comment (ruddell) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:206]: It's only necessary to send a valid `User` (which requires both the `login` and `id` fields) for OAuth2 Gateways because OAuth2 Microservice entities can have relationships with `User` 

This is not possible with JWT microservices.  For monoliths, only the `id` is needed.

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs (hunk 4 above)
Comment (MathieuAA) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:207]: Forget it... I must be tired because I actually believed that something like that:
```
<%_ ... { _% >
  <%_ ... { _% >
    ...
  <%_ ... } _% >
<%_ ... } _% >
```

was equal to
```
<%_ ... {
   ... { _% >
    ...
  <%_ ... }
... } _% >
```

apparently this isn't the case :/

Comment (MathieuAA) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity-update.tsx.ejs:207]: True. Bad example. Thanks!

**Comment by pascalgrimaud** [comment]
as there are 2 approvals, let's merge this
