### PR TITLE
Handle custom primary key names in entity filtering

### LINKED ISSUE #13695: Generated Query Services and Integration Tests do not use custom IDs given to Entites
##### **Overview of the issue**

When a importing an entity with the jhipster import-jdl command and with filtering turned on, the generated EntityQueryService does not use the correct id name.  The same thing is happening in entities that have relationships to entities with custom Ids.

For Example:
* I Created an entity with the following code given at the bottom of this ticket using the `jhipster import-jdl` command
* Then the following snippet is generated in the WorkoutSessionQueryService
`
            if (criteria.getRowidWorkoutSession() != null) {
                specification = specification.and(buildRangeSpecification(criteria.getRowidWorkoutSession(), WorkoutSession_.id));
            }
`

There is also an issue where the custom id is not being used when generating the rest Integration Tests. 

It is an easy workaround to manually change the code.  Though it gets tedious to do with many entities and if you extend an entity later and have to overwrite the files.

##### **Motivation for or Use Case**

I am currently integrating Jhipster with my API.  My data model is already created and I have a different name for my ids of my tables.  I need to use the custom Id feature in order to integrate Jhipster

##### **Reproduce the error**

* Create a jhipster appliation using the jdl file using the code I provided above

##### **Suggest a Fix**

Update the code that generates the EntityQueryService classes to use the custom Id if one is provided

##### **JHipster Version(s)**

Jhipster 7 Beta-1

##### **JHipster configuration**

`

##### **Environment and Tools**

openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

git version 2.22.0

node: v15.5.0

npm: 6.14.10

yeoman: 3.1.1

Docker version 19.03.12, build 48a66213fe

docker-compose version 1.26.2, build eefe0d31

`
To provide all information we need, you should run `jhipster info` in the project root folder, and
copy/paste the result here.
The `.yo-rc.json` file generated in the root folder is mandatory for bug reports. This will help us to replicate the scenario.
You should remove any sensitive information like the rememberMe key or the jwtSecretKey key.
{
  "generator-jhipster": {
    "blueprints": [],
    "applicationType": "monolith",
    "baseName": "drive",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "pages": [],
    "creationTimestamp": 1611354228721,
    "promptValues": {
      "packageName": "com.drive.fitness",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.drive.fitness",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["searchEngine:elasticsearch", "websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/drive/fitness",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"],
    "lastLiquibaseTimestamp": 1611359273000,
    "entities": [
       WorkoutSession
    ],
    "embeddableLaunchScript": false,
    "otherModules": []
  }
}

---
If you have a JDL please wrap it in below structure
  <details>
  <summary>JDL definitions</summary>
  <pre>
application {
  config {
    applicationType monolith
    authenticationType oauth2
    baseName drive
    blueprints []
    buildTool maven
    cacheProvider ehcache
    clientFramework angularX
    clientPackageManager npm
    clientTheme none
    creationTimestamp 1611354228721
    databaseType sql
    devDatabaseType h2Memory
    dtoSuffix DTO
    embeddableLaunchScript false
    enableHibernateCache false
    enableSwaggerCodegen false
    enableTranslation false
    jhiPrefix jhi
    jhipsterVersion "7.0.0-beta.1"
    languages [en, fr]
    messageBroker false
    nativeLanguage en
    otherModules []
    packageName com.drive.fitness
    prodDatabaseType postgresql
    reactive false
    searchEngine elasticsearch
    serverPort 8080
    serviceDiscoveryType false
    skipClient false
    skipServer false
    skipUserManagement true
    testFrameworks [cypress, gatling, cucumber]
    websocket spring-websocket
    withAdminUi true
  }
  entities WorkoutSession
}

entity WorkoutSession {
  @Id rowidWorkoutSession Long
  workoutSessionStartTime LocalDate
  workoutSessionEndTime LocalDate
}
dto WorkoutSession
paginate WorkoutSession
service WorkoutSession with serviceClass
filter WorkoutSession  </pre>
  </details>

##### **Browsers and Operating System**

MacOS 11.1

- [x] Checking this box is mandatory (this is just to show you read everything)

P.S. I love this product, your team has done a great job, thanks!

### PR DESCRIPTION
**Pull request by gzsombor**
Fix #13695 : Handle custom primary key names in the filtering impleme…

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/entity/index.js [hunk 1]
```diff
@@ -601,6 +601,10 @@ class EntityGenerator extends BaseBlueprintGenerator {
         this.context.entityContainsCollectionField = this.context.relationships.some(relationship => relationship.relationshipCollection);
       },
 
+      processPrimaryKeyTypesForRelations() {
+        this.context.otherEntityPrimaryKeyTypes = new Set(this.context.relationships.map(relationship => relationship.otherEntity.primaryKey.type));
```
Comment (mshima) [inline generators/entity/index.js:605]:
```suggestion
        this.context.otherEntityPrimaryKeyTypes = new Set(this.context.relationships.map(relationship => relationship.otherEntity.primaryKey && relationship.otherEntity.primaryKey.type));
```
- primaryKey doesn't exists for embedded entities.
- IMO you should add Set to `otherEntityPrimaryKeyTypes` or convert to back to array.
Every field is array, so it can be confusing to use has instead of includes.

**Review by mshima — CHANGES_REQUESTED** [review]
To prevent regressions would be nice to add a copy of https://github.com/mshima/generator-jhipster/blob/main/test-integration/samples/jdl-entities/custom-id.jdl with filtering.

**Review by mshima — APPROVED** [review]
LGTM

File: generators/entity/index.js [hunk 2]
```diff
@@ -601,6 +601,13 @@ class EntityGenerator extends BaseBlueprintGenerator {
         this.context.entityContainsCollectionField = this.context.relationships.some(relationship => relationship.relationshipCollection);
       },
 
+      processPrimaryKeyTypesForRelations() {
+        const types = this.context.relationships.map(
+          relationship => relationship.otherEntity.primaryKey && relationship.otherEntity.primaryKey.type
+        );
```
Comment (mshima) [inline generators/entity/index.js:607]:
```suggestion
        const types = this.context.relationships
            .filter(relationship => relationship.otherEntity.primaryKey)
            .map(relationship => relationship.otherEntity.primaryKey.type);
```
Making sure we are not adding `false` to the set.

File: generators/entity/index.js [hunk 3]
```diff
@@ -601,6 +601,13 @@ class EntityGenerator extends BaseBlueprintGenerator {
         this.context.entityContainsCollectionField = this.context.relationships.some(relationship => relationship.relationshipCollection);
       },
 
+      processPrimaryKeyTypesForRelations() {
+        const types = this.context.relationships
+            .filter(relationship => relationship.otherEntity.primaryKey)
+            .map(relationship => relationship.otherEntity.primaryKey.type);
```
Comment (mshima) [inline generators/entity/index.js:607]:
```suggestion
        const types = this.context.relationships.filter(rel => rel.otherEntity.primaryKey).map(rel => rel.otherEntity.primaryKey.type);
```

**Comment by gzsombor** [comment]
@mshima thanks for the fixes and for the merge!
