### PR TITLE
change to tcp appender

### LINKED ISSUE #6102: Migrate logstash appender from UDP to TCP
[_LoggingConfiguration.java#L92-L96](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java#L92-L96)

```java

        // Limit the maximum length of the forwarded stacktrace so that it won't exceed the 8KB UDP limit of logstash
        ShortenedThrowableConverter throwableConverter = new ShortenedThrowableConverter();
        throwableConverter.setMaxLength(7500);
        throwableConverter.setRootCauseFirst(true);
        logstashAppender.setThrowableConverter(throwableConverter);
```

the [logstash-plugins-inputs-udp.html#plugins-inputs-udp-buffer_size](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-udp.html#plugins-inputs-udp-buffer_size)
> **buffer_size**
> Value type is number
> Default value is 65536
> The maximum packet size to read from the network

`65536/1024=64K`

[logstash/issues/2111#domenkozar](https://github.com/elastic/logstash/issues/2111#issuecomment-63873253)
>Yes, I spend a few hours on chasing a bug. I've fixed the bug on the client side to split messages, but then logstash was parsing JSON in a weird way if it hit the 8k limit.

the logstash input json like this

```javascript
{
	"_index": "logstash-2017.07.07",
	"_type": "jhipster",
	"_id": "AV0d78jVDn-FIhloNkzA",
	"_version": 1,
	"_score": null,
	"_source": {
		"@timestamp": "2017-07-07T16:44:00.078Z",
		"instance_name": "%{app_name}-10.42.196.67:%{app_port}",
		"@version": "1",
		"host": "10.42.196.67",
		"message": "{\"@timestamp\":\"2017-07-08T00:44:00.063+08:00\",\"@version\":1,\"message\":\"....{long string}.....
```

### PR DESCRIPTION
**Pull request by anjia0532**
change to tcp appender,
see https://github.com/logstash/logstash-logback-encoder#tcp-appenders

Fix #6102

change logstash config see https://github.com/jhipster/jhipster-console/pull/69

my demo https://github.com/anjia0532/tcpappender

### CODE REVIEW

**Comment by PierreBesson** [comment]
Thanks for your PR @anjia !
I will do some testing on my side. And once I release the new version of the console with tcp setup, I will merge this.

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java [hunk 1]
```diff
@@ -84,16 +88,24 @@ public void addLogstashAppender(LoggerContext context) {
...
 
+		//More documentation is available at: https://github.com/logstash/logstash-logback-encoder
+        LogstashEncoder logstashEncoder=new LogstashEncoder();
         // Set the Logstash appender config from JHipster properties
-        logstashAppender.setSyslogHost(jHipsterProperties.getLogging().getLogstash().getHost());
-        logstashAppender.setPort(jHipsterProperties.getLogging().getLogstash().getPort());
-        logstashAppender.setCustomFields(customFields);
-
-        // Limit the maximum length of the forwarded stacktrace so that it won't exceed the 8KB UDP limit of logstash
+		logstashEncoder.setCustomFields(customFields);
```
Comment (pascalgrimaud) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: indent, should be 8 spaces

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java [hunk 2]
```diff
@@ -84,16 +88,24 @@ public void addLogstashAppender(LoggerContext context) {
...
+		// Set the Logstash appender config from JHipster properties
```
Comment (pascalgrimaud) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: indent, should be 8 spaces

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java [hunk 3]
```diff
@@ -84,16 +88,24 @@ public void addLogstashAppender(LoggerContext context) {
...
+        logstashAppender.addDestinations(new InetSocketAddress(jHipsterProperties.getLogging().getLogstash().getHost(),jHipsterProperties.getLogging().getLogstash().getPort()));
+        
+
```
Comment (pascalgrimaud) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: remove this additional line

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java [hunk 4]
```diff
@@ -84,16 +88,24 @@ public void addLogstashAppender(LoggerContext context) {
...
-
-        // Limit the maximum length of the forwarded stacktrace so that it won't exceed the 8KB UDP limit of logstash
+		logstashEncoder.setCustomFields(customFields);
+		// Set the Logstash appender config from JHipster properties
+        logstashAppender.addDestinations(new InetSocketAddress(jHipsterProperties.getLogging().getLogstash().getHost(),jHipsterProperties.getLogging().getLogstash().getPort()));
+        
+		
         ShortenedThrowableConverter throwableConverter = new ShortenedThrowableConverter();
-        throwableConverter.setMaxLength(7500);
+        //throwableConverter.setMaxLength(2048);
```
Comment (pascalgrimaud) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: if no need, you can remove this commented line

File: generators/server/templates/src/main/resources/_logback-spring.xml [hunk 5]
```diff
@@ -105,6 +105,9 @@
     <logger name="unknown.jul.logger" level="WARN"/>
     <%_ } _%>
 
+	<!-- https://logback.qos.ch/manual/configuration.html#shutdownHook and https://jira.qos.ch/browse/LOGBACK-1090 -->
+	<shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook"/>
```
Comment (pascalgrimaud) [inline generators/server/templates/src/main/resources/_logback-spring.xml]: indent, should be 8 spaces

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java (hunk 1 above)
Comment (anjia0532) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: sorry about this  stupid mistakes. fixed.

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java (hunk 2 above)
Comment (anjia0532) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: sorry about this  stupid mistakes. fixed.

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java (hunk 4 above)
Comment (anjia0532) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: fixed

File: generators/server/templates/src/main/resources/_logback-spring.xml (hunk 5 above)
Comment (anjia0532) [inline generators/server/templates/src/main/resources/_logback-spring.xml]: sorry about this  stupid mistakes. fixed.

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java (hunk 3 above)
Comment (anjia0532) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: fixed

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java [hunk 6]
```diff
@@ -84,16 +88,22 @@ public void addLogstashAppender(LoggerContext context) {
         String customFields = "{\"app_name\":\"" + appName + "\",\"app_port\":\"" + serverPort + "\"}";
         <%_ } _%>
 
+        //More documentation is available at: https://github.com/logstash/logstash-logback-encoder
+        LogstashEncoder logstashEncoder=new LogstashEncoder();
```
Comment (PierreBesson) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: Please be careful of the coding style, put a space after `//`, correctly space arount `=`.

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java [hunk 7]
```diff
@@ -84,16 +88,22 @@ public void addLogstashAppender(LoggerContext context) {
...
-        logstashAppender.setCustomFields(customFields);
-
-        // Limit the maximum length of the forwarded stacktrace so that it won't exceed the 8KB UDP limit of logstash
+        logstashEncoder.setCustomFields(customFields);
+        // Set the Logstash appender config from JHipster properties
+        logstashAppender.addDestinations(new InetSocketAddress(jHipsterProperties.getLogging().getLogstash().getHost(),jHipsterProperties.getLogging().getLogstash().getPort()));
+        
         ShortenedThrowableConverter throwableConverter = new ShortenedThrowableConverter();
-        throwableConverter.setMaxLength(7500);
+        throwableConverter.setMaxDepthPerThrowable(30);
```
Comment (PierreBesson) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: I'm not so keen on magic numbers. Please add config properties in https://github.com/jhipster/jhipster/blob/master/src/main/java/io/github/jhipster/config/JHipsterProperties.java#L797
by doing a PR on our server lib: https://github.com/jhipster/jhipster
Please add the following under `jhipster.logging.logstash`:
- maxDepthPerThrowable (default value 30)
- keepAliveDurationMinutes (default 5)
- reconnectionDelaySeconds (default 1)
Also you need to add those to application-dev.yml and application-prod.yml so that user can easily discover and customize those values.

Comment (anjia0532) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: i remove the special settings and use logstash-logback-encoder default value.

maxDepthPerThrowable (default [25](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L120))
reconnectionDelaySeconds (default [30](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L100))
keepAlive ( [When null (the default), no keepAlive messages will be sent.](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L224) )

File: generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java (hunk 6 above)
Comment (anjia0532) [inline generators/server/templates/src/main/java/package/config/_LoggingConfiguration.java]: fixed

**Comment by PierreBesson** [comment]
@anjia, I just tested it and it works great. I'm in the process of releasing the new Console and upgrading the dependency in JHipster.

**Comment by anjia0532** [comment]
: )
