### PR TITLE
fix "event" entity name

### LINKED ISSUE #6198: Use blacklist for entity names (e.g. event)
##### **Overview of the issue**

I am creating an application with an entity called **event**. This will cause problems within the JS code

##### **Reproduce the error**

Create an entity with the name **event** and compile. 

```
ERROR in ./src/main/webapp/app/entities/event/event-dialog.component.ts
Module parse failed: C:\dev\workspaces\github\jhipstermaps\node_modules\angular2-template-loader\index.js!C:\dev\workspaces\github\jhipstermaps\node_modules\awesome-typescript-loader\dist\entry.js!C:\dev\workspaces\github\jhipstermaps\node_modules\tslint-loader
\index.js!C:\dev\workspaces\github\jhipstermaps\src\main\webapp\app\entities\event\event-dialog.component.ts Argument name clash (35:66)
You may need an appropriate loader to handle this file type.
|         return this.dataUtils.openFile(contentType, field);
|     };
|     EventDialogComponent.prototype.setFileData = function (event, event, field, isImage) {
|         if (event && event.target.files && event.target.files[0]) {
|             var file_1 = event.target.files[0];
 @ ./src/main/webapp/app/entities/event/index.ts 9:9-44
 @ ./src/main/webapp/app/entities/event/event.module.ts
 @ ./src/main/webapp/app/entities/entity.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in [at-loader] ./src/main/webapp/app/entities/event/event-dialog.component.ts:43:17
    TS2300: Duplicate identifier 'event'.

ERROR in [at-loader] ./src/main/webapp/app/entities/event/event-dialog.component.ts:43:24
    TS2300: Duplicate identifier 'event'.
error Command failed with exit code 2.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

##### **Suggest a Fix**

Add an blacklist for reserved keywords (especially JS side)

##### **JHipster Version(s)**

4.6.2

### PR DESCRIPTION
**Pull request by ruddell**
If the entity's name was `event` (or `field`) and the entity contained a blob field, a TS error would occur because two variables in the function have the same name.  This makes it so the entity name doesn't matter

Fix #6198

- Please make sure the below checklist is followed for Pull Requests.

- [X] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [X] Tests are added where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts [hunk 1]
```diff
@@ -120,15 +120,15 @@ export class <%= entityAngularName %>DialogComponent implements OnInit {
         return this.dataUtils.openFile(contentType, field);
     }
 
-    setFileData(event, <%= entityInstance %>, field, isImage) {
+    setFileData(event, entity, field, isImage) {
```
Comment (deepu105) [inline generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts]: @ruddell I guess this method could be moved into dataUtils as well as its generic now
