### PR TITLE
React : bug fix of the regular gateway config

### LINKED ISSUE #7124: Fix issues with i18n for microservices
The new folder structure updates introduced in https://github.com/jhipster/generator-jhipster/pull/7079 cause a bug in i18n, when doing microservices, as per https://github.com/jhipster/generator-jhipster/pull/7079#issuecomment-365350893

This issue is so that I dont forget to fix it and any related issues

### PR DESCRIPTION
**Pull request by agaspardcilia**
Also happen to fix  #7124
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs [hunk 1]
```diff
@@ -69,6 +69,9 @@ export class ConfigurationPage extends React.Component<IConfigurationPageProps,
     });
   };
 
+  getContextList = contexts => Object.values(contexts).map(v => v['beans']).reduce((acc, e) => ({ ...acc, ...e }));
```
Comment (deepu105) [inline generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs]: why not just `v => v.beans`

Comment (agaspardcilia) [reply generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs]: It creates an error since `v` is just a regular `Object` at this point.

Comment (deepu105) [reply generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs]: what do you mean? if `v = { beans: ... }` then `v.beans` and `v['beans']` are the same

Comment (agaspardcilia) [reply generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs]: I know, but TS don't or at least that's what vscode is telling me. I don't like doing it that way too, so I wouldn't mind a suggestion on how to improve that.

Comment (deepu105) [reply generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs]: oh, TS issue, it's due to type missing. Try `(v: any) => v.beans`

Comment (agaspardcilia) [reply generators/client/templates/react/src/main/webapp/app/modules/administration/configuration/configuration.tsx.ejs]: It works, thanks :+1:
