### PR TITLE
Avoid isPersisted being saved in elasticsearch index

### LINKED ISSUE #27686: isPersisted ends up in elasticsearch index
##### **Overview of the issue**
Currently, when using elasticsearch as part of your application, the generated application does not only save actual payload fields into the corresponding index, but also fields like `isPersisted`. This is, because when generating this field, it is annotated with `@Transient` (jakarta.persistence.Transient) but not with `@org.springframework.data.annotation.Transient`.

##### **Motivation for or Use Case**
 As this field `isPersisted`is useless information for an elasticsearch index, we should also just generate the other `Transient` annotation as well.

##### **Reproduce the error**

https://github.com/jhipster/generator-jhipster/blob/89f377426892a987ab410687d121122a4950e17b/generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs#L38C18-L41

This is the place, where this field is currently generated. The second annotation is nowhere else to be found, but should be somewhere...
##### **JHipster Version(s)**
8.7.1

##### **JHipster configuration**

To provide all information we need, you should run `jhipster info` in the project root folder (or workspaces root for microservices), and
copy/paste the result here.
`jhipster info` removes sentitive information like rememberKey, jwtSecretKey. Double check if there is any other sensitive info.

As alternative you can add a JDL wrapped in below structure

  <details>
  <summary>JDL definitions</summary>
  <pre>
     JDL content here
  </pre>
  </details>

The information is mandatory for bug reports. This will allow us to use automated tests and genarate the broken sample using `jhipster from-issue` command.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by OmarHawk**
Fix #27686

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs [hunk 1]
```diff
@@ -36,7 +36,10 @@ import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
 <&_ } -&>
 
 <&_ if (fragment.classAdditionalFieldsSection) { -&>
+    @org.springframework.data.annotation.Transient
+<%_ if (!reactive) { _%>
```
Comment (mshima) [inline generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs:40]:
```suggestion
<%_ if (!reactive && databaseTypeSql) { _%>
```

Jakarta's Transient should be used in hibernate only?
Others databases should be compatible with Spring Data's Transient

File: generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs [hunk 2]
```diff
@@ -48,7 +51,10 @@ import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
     }
  <%_ } -%>
 
+    @org.springframework.data.annotation.Transient
+<%_ if (!reactive) { _%>
```
Comment (mshima) [inline generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs:55]: Same as above

File: generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs (hunk 1 above)
Comment (mshima) [reply generators/spring-data-relational/templates/src/main/java/_package_/_entityPackage_/domain/_persistClass_.java.jhi.spring_data_persistable.ejs:40]: Nevermind isPersistable is Sql only.

**Review by mshima — APPROVED** [review]
