### PR TITLE
fix build when using skipUserManagement

### LINKED ISSUE #7594: Webpack build failed when generating monolith with skipUserManagement
##### **Overview of the issue**

webpack build failed when generating monolith with skipUserManagement
```
ERROR in ./src/main/webapp/app/core/index.ts
Module not found: Error: Can't resolve './user/user.service' in '/Users/gongy/poc/workflow-app/app/src/main/webapp/app/core'
 @ ./src/main/webapp/app/core/index.ts 15:21-51
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts
```
mvn
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/gongy/poc/workflow-app/app/src/test/java/net/topikachu/caseapp/security/DomainUserDetailsServiceIntTest.java:[4,36] cannot find symbol
  symbol:   class User
  location: package net.topikachu.caseapp.domain
```
##### **Motivation for or Use Case**

I'd like to generate a monolith with an external IAM system. No user managment is required in this new app.

##### **Reproduce the error**

`jhipster --skip-user-management`
Choose monolith with other stuffs

##### **Suggest a Fix**

It seems there's a wrong config in the
webapp/app/core/index.ts

Also the DomainUserDetailsServiceIntTest should be removed from the generated app.
##### **JHipster Version(s)**

generator-jhipster@5.0.0-beta.1

##### **JHipster configuration**
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
app@0.0.0 /Users/gongy/poc/workflow-app/app
└── generator-jhipster@5.0.0-beta.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "net.topikachu.caseapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "app",
    "packageName": "net.topikachu.caseapp",
    "packageFolder": "net/topikachu/caseapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ],
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.10.1

node: v8.11.1

npm: 5.6.0

yarn: 1.3.2

Docker version 18.05.0-ce-rc1, build 33f00ce

docker-compose version 1.21.0, build 5920eb0

##### **Browsers and Operating System**

macOS Sierra
- [ X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ruddell**
Fix #7594

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [X] Documentation is added/updated where necessary
- [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/server/files.js [hunk 1]
```diff
@@ -925,7 +925,7 @@ const serverFiles = {
             ]
         },
         {
-            condition: generator => generator.applicationType === 'monolith' && generator.authenticationType !== 'oauth2',
+            condition: generator => !shouldSkipUserManagement(generator) && generator.authenticationType !== 'oauth2',
```
Comment (ruddell) [inline generators/server/files.js]: This uses the same condition for generating `DomainUserDetailsServiceIntTest` as it does for generating `DomainUserDetailsService`

**Comment by jdubois** [comment]
Thanks @ruddell !
