### PR TITLE
Fix initial text direction setting

### LINKED ISSUE #26400: JHipster Application Defaults to LTR Instead of RTL for Arabic Language
##### **Overview of the issue**

I'm working on a simple project using JHipster with React for the frontend and have set Arabic as the default language. However, I'm encountering an issue where the site initially loads in Arabic but with LTR (Left-to-Right) orientation. If I reselect Arabic from the language options (even though it's already set to Arabic), the orientation correctly switches to RTL (Right-to-Left).

To address this, I tried modifying the `index.html` file by setting `<html class="no-js" lang="ar-ly" dir="rtl">`, intending for the site to default to RTL on the first load. Despite this, when inspecting the page, I notice that it reverts to `<html class="no-js" lang="ar-ly" dir="ltr">`, suggesting something overrides my settings.

I suspect there might be JavaScript or a configuration within JHipster that dynamically sets the `dir` attribute based on the selected language, overriding my manual settings in `index.html`. I've set the title language in JHipster to Arabic, hoping it would enforce RTL, but the issue persists.

##### **Motivation for or Use Case**

This is a bug for me because I need the site to load with RTL orientation by default when Arabic is set as the default language. Manually reselecting the language every time to get the correct orientation is not user-friendly.

##### **Reproduce the error**

1. Generate a JHipster project with React as the frontend framework.
2. Set Arabic as the default language.
3. Run the project and observe that the site loads in Arabic but with LTR orientation.
4. Reselect Arabic from the language options to see the orientation switch to RTL.

##### **Related issues**

I have searched for similar issues but could not find any that address this exact problem.

##### **Suggest a Fix**

It seems that the language setting in JHipster dynamically sets the `dir` attribute. Ensuring that the correct `dir` attribute is set based on the default language in the initial load would solve this issue.

##### **JHipster Version(s)**

`8.5.0`

##### **JHipster configuration**

```bash
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.5.0

Welcome to the JHipster Information Sub-Generator



fin-manage@0.0.1-SNAPSHOT C:\Users\bader\OneDrive\Desktop\jHipster
`-- generator-jhipster@8.5.0



##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "XX",
    "buildTool": "maven",
    "cacheProvider": "caffeine",
    "clientFramework": "react",
    "clientTestFrameworks": [
      "cypress"
    ],
    "clientTheme": "darkly",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1718044006189,
    "cypressAudit": true,
    "cypressCoverage": null,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "enableHibernateCache": true,
    "enableSwaggerCodegen": true,
    "enableTranslation": true,
    "entities": [],
    "feignClient": null,
    "jhipsterVersion": "8.5.0",
    "languages": [
      "ar-ly",
      "en"
    ],
    "messageBroker": false,
    "microfrontend": null,
    "microfrontends": [],
    "nativeLanguage": "ar-ly",
    "packageName": "com.xx.project",
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": null,
    "serverSideOptions": [
      "enableSwaggerCodegen:true"
    ],
    "serviceDiscoveryType": false,
    "syncUserWithIdp": null,
    "testFrameworks": [
      "gatling",
      "cypress"
    ],
    "websocket": false,
    "withAdminUi": true
  }
}
</pre>
</details>


##### **Environment and Tools**

java version "17.0.10" 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.10+11-LTS-240, mixed mode, sharing)

git version 2.45.1.windows.1

node: v20.13.1
npm: 10.8.0

Docker version 26.1.1, build 4cf5afa

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>


</pre>
</details>


Congratulations, JHipster execution is complete!
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

without entities
##### **Browsers and Operating System**

- OS: Windows 10
- Browsers: Chrome, Firefox

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by emilpaw**
Fixes #26400
Closes https://github.com/jhipster/generator-jhipster/pull/26407

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs [hunk 1]
```diff
@@ -52,8 +52,13 @@ export interface IHeaderProps {
...
 const Header = (props: IHeaderProps) => {
   const [menuOpen, setMenuOpen] = useState(false);
+
 <%_ if (enableI18nRTL) { _%>
-  useEffect(() => document.querySelector('html').setAttribute('dir', isRTL(Storage.session.get('locale')) ? 'rtl' : 'ltr'));
+  const currentLocale = useAppSelector(state => state.locale.currentLocale);
+
+  useEffect(() => {
+    document.querySelector('html').setAttribute('dir', isRTL(currentLocale) ? 'rtl' : 'ltr');
+  }, [currentLocale]);
```
Comment (mshima) [inline generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs:61]: You are faster 😄.

I agree with you solution if the following are handled:
- the location looks wrong, since it will be more related to storage (generic solution) than it is related to the menu selection it should be in app.tsx.
- there is already a handler for locale rtl handling bellow, so the code will execute twice on each locale change.

Comment (emilpaw) [reply generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs]: I implemented the suggestions but now saw your solution and using templating to set the default is quite elegant and better than what I proposed.

What I definitely think still makes sense to add is the dependency array for the useEffect. Otherwise, it will run on every re-render, which is even worse than twice per language change. :smile:

Moving the effect to app.tsx and setting the HTML attribute like I suggested could still be worthwhile.

File: generators/react/templates/src/main/webapp/app/app.tsx.ejs [hunk 2]
```diff
@@ -54,6 +57,12 @@ export const App = () => {
   const isInProduction = useAppSelector(state => state.applicationProfile.inProduction);
   const isOpenAPIEnabled = useAppSelector(state => state.applicationProfile.isOpenAPIEnabled);
 
+<%_ if (enableI18nRTL) { _%>
+  useEffect(() => {
+    setTextDirection(currentLocale);
+  }, []);
+<%_ } _%>
```
Comment (mshima) [inline generators/react/templates/src/main/webapp/app/app.tsx.ejs:64]: `currentLocale` only exists if `enableTranslation`.
```suggestion
<%_ if (enableTranslation && enableI18nRTL) { _%>
  useEffect(() => {
    setTextDirection(currentLocale);
  }, [currentLocale]);
<%_ } _%>
```

File: generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs [hunk 3]
```diff
@@ -29,7 +29,7 @@ import {
 import LoadingBar from 'react-redux-loading-bar';
 
 <%_ if (enableTranslation && enableI18nRTL) { _%>
-import { isRTL } from 'app/config/translation';
+import { setTextDirection } from 'app/config/translation';
 <%_ } _%>
```
Comment (mshima) [inline generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs:33]:
```suggestion
```

File: generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs [hunk 4]
```diff
@@ -29,7 +29,7 @@ import {
 import LoadingBar from 'react-redux-loading-bar';
 
 <%_ if (enableTranslation && enableI18nRTL) { _%>
```
Comment (mshima) [inline generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs:31]:
```suggestion
```

File: generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs [hunk 5]
```diff
@@ -64,7 +61,7 @@ const Header = (props: IHeaderProps) => {
     Storage.session.set('locale', langKey);
     dispatch(setLocale(langKey));
   <%_ if (enableI18nRTL) { _%>
```
Comment (mshima) [inline generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs:63]:
```suggestion
```

File: generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs [hunk 6]
```diff
@@ -64,7 +61,7 @@ const Header = (props: IHeaderProps) => {
...
-    document.querySelector('html').setAttribute('dir', isRTL(langKey) ? 'rtl' : 'ltr');
+    setTextDirection(langKey);
   <%_ } _%>
```
Comment (mshima) [inline generators/react/templates/src/main/webapp/app/shared/layout/header/header.tsx.ejs:65]:
```suggestion
```

**Review by mshima — COMMENTED** [review]
Watch for currentLocale change only?

**Comment by mshima** [comment]
`index.html` should be updated like in https://github.com/jhipster/generator-jhipster/pull/26407/files.

**Comment by emilpaw** [comment]
> Watch for currentLocale change only?

Didn't you say in your first review comment that we don't want the attribute to be set twice? Or did I misunderstand your comment?



> `index.html` should be updated like in https://github.com/jhipster/generator-jhipster/pull/26407/files.

Done.

Sorry, but I am not sure what your change suggestions are about exactly. The asynchronous nature of PR communication makes this a bit confusing. :smile:

**Comment by mshima** [comment]
> > Watch for currentLocale change only?
> 
> Didn't you say in your first review comment that we don't want the attribute to be set twice? Or did I misunderstand your comment?

That’s why I’ve suggested to remove direction handling from header and keep only at the watch.

**Comment by emilpaw** [comment]
> > > Watch for currentLocale change only?
> > 
> > 
> > Didn't you say in your first review comment that we don't want the attribute to be set twice? Or did I misunderstand your comment?
> 
> That’s why I’ve suggested to remove direction handling from header and keep only at the watch.

Just to make sure I understand, you want that only the effect sets the HTML attribute? That would explain why you propose to add currentLocale to the dependency array.

File: generators/react/templates/src/main/webapp/app/app.tsx.ejs [hunk 7]
```diff
@@ -34,6 +34,9 @@ import { hasAnyAuthority } from 'app/shared/auth/private-route';
 import ErrorBoundary from 'app/shared/error/error-boundary';
 import { AUTHORITIES } from 'app/config/constants';
 import AppRoutes from 'app/routes';
+<%_ if (enableI18nRTL) { _%>
```
Comment (mshima) [inline generators/react/templates/src/main/webapp/app/app.tsx.ejs:37]: Completeness.
```suggestion
<%_ if (enableTranslation &&  enableI18nRTL) { _%>
```

**Review by mshima — APPROVED** [review]

**Comment by emilpaw** [comment]
@mshima Thanks for the quick review and patience. :smile:

**Comment by emilpaw** [comment]
@mshima Should we split the bounty?

**Comment by mshima** [comment]
@emilpaw you can claim the full bounty.

**Comment by emilpaw** [comment]
Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/219304

Thanks :)

**Comment by DanielFran** [comment]
@emilpaw approved
