### PR TITLE
Skip gway pages when skip service discovery

### LINKED ISSUE #7827: Redundant / broken gateway sub-module/component code without serviceDiscovery
##### **Overview of the issue**
If you generate a gateway without service discovery, then, on server side it doesn't generate the GatewayResource.java. However, no such checks are added on frontend layer and thus it generate gateway page/component code (along with associated service, routes, reducer etc) which are redundant as they will never work without backend API

##### **Suggest a Fix**
This change got introduced by below commit on server side. Either we should revert this or apply similar checks on frontend layer.
https://github.com/jhipster/generator-jhipster/commit/f3d100c6d624ac58157a6c72ee4c949da563e574

##### **JHipster Version(s)**
5.0.0-beta.3

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.0.0-beta.3",
    "applicationType": "gateway",
    "baseName": "rgtw5",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "4a95621ba2e00b566a6b5625a4304126fdc687e7",
    "clientFramework": "react",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by ruddell**
Fix #7827

- Skips gateway pages when no service discovery
- Don't copy gateway.json translation file into non-gateways or no service dsicovery
- Adds expected files tests for no service discovery

Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/client/index.js [hunk 1]
```diff
@@ -184,11 +184,6 @@ module.exports = class extends BaseGenerator {
                     this.baseName = baseName;
                 }
 
-                this.serviceDiscoveryType = configuration.get('serviceDiscoveryType') === 'no' ? false : configuration.get('serviceDiscoveryType');
```
Comment (deepu105) [inline generators/client/index.js]: why is this removed wouldn't this fail truthy checks as the default value will be `no` and would pass the check?

Comment (deepu105) [reply generators/client/index.js]: I guess this was code handling legacy .yo-rc files when we had 'no' as default option. Can you check with an old .yo-rc file before we changed from 'no' to false

Comment (ruddell) [reply generators/client/index.js]: Tested with `no` and fixed the language generator in that case.  Everything else looks good
