### PR TITLE
fix react websockets implementation

### LINKED ISSUE #12729: websocket Track Users works very partially - only after F5 and only for ADMIN_ROLE and the page name is not shown
The generated  app has a new websocket feature demonstrated by the "Track Users" options in the Admin menu.
When new users login to the web app, they are not shown in the "Track Users" screen.

The only way to see a new user is:
create a new user2. 
make user2 ADMIN_ROLE, 
login user2. 
go to any entity
press F5
user2 is now shown in the Tracker page, but still without the page name

##### **Reproduce the error**

Install latest jhipster 6.10.3
Create standard jhipster app - i use h2/jwt/react/postgres  
(I had to fix the enzyme 3.10.5 -> .7 dependency error)
 
Login with admin/admin
Go to Track Users page
Only admin is shown
On a different browser - register user2
Login user2
User2 is NOT shown in the Tracker Users page

I am attaching a log file ACCESS_DENIED exception which may be relevant
##### **Related issues**

ubuntu LTS 18
both chrome and firefox
jhipster 6.10.3
npm 6.14.6
node 10.21.1
standard generator : monolithic/h2/postgres/JW/react
Additional features : websocket and swagger enables

[X ] Checking this box is mandatory (this is just to show you read everything)

Attaching java-sprint log file

> 2020-10-11 22:09:30.175 ERROR 32249 --- [   XNIO-1 I/O-1] o.s.w.s.m.StompSubProtocolHandler        : Failed to send client message to application via MessageChannel in session 04mo10od. Sending STOMP ERROR to client.

> org.springframework.security.access.AccessDeniedException: Access is denied

> 2020-10-11 22:11:39.956 DEBUG 32249 --- [boundChannel-41] c.p.c.web.websocket.ActivityService      : Sending user tracking data
 
-----------------------------

2020-10-11 22:08:57.491 DEBUG 32249 --- [ XNIO-1 task-46] c.p.candycash.service.UserService        : Exit: getAllManagedUsers() with result = Page 1 of 1 containing com.privatepayout.candycash.service.dto.UserDTO instances
2020-10-11 22:08:57.492 DEBUG 32249 --- [ XNIO-1 task-46] c.p.candycash.web.rest.UserResource      : Exit: getAllUsers() with result = <200 OK OK,[UserDTO{login='system', firstName='System', lastName='System', email='system@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user2', firstName='user2', lastName='user2', email='user2@user2.user2', imageUrl='null', activated=true, langKey='en', createdBy=user, createdDate=2020-10-11T19:04:06.574283Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:04:59.767280Z, authorities=[ROLE_USER]}, UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER]}],[X-Total-Count:"5", Link:"<http://127.0.1.1:8080/api/users?page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/users?page=0&size=20>; rel="first""]>
2020-10-11 22:09:18.085 DEBUG 32249 --- [ XNIO-1 task-53] c.p.c.r.CustomAuditEventRepository       : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-10-11T19:09:18.085613Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2020-10-11 22:09:18.086 DEBUG 32249 --- [ XNIO-1 task-53] c.p.c.r.CustomAuditEventRepository       : Exit: add() with result = null
2020-10-11 22:09:18.087  WARN 32249 --- [ XNIO-1 task-53] o.z.problem.spring.common.AdviceTraits   : Unauthorized: Full authentication is required to access this resource
2020-10-11 22:09:18.088  WARN 32249 --- [ XNIO-1 task-53] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.security.authentication.InsufficientAuthenticationException: Full authentication is required to access this resource]
2020-10-11 22:09:29.774 DEBUG 32249 --- [ XNIO-1 task-55] c.p.c.web.rest.UserJWTController         : Enter: authorize() with argument[s] = [LoginVM{username='threethree', rememberMe=true}]
2020-10-11 22:09:29.774 DEBUG 32249 --- [ XNIO-1 task-55] c.p.c.security.DomainUserDetailsService  : Authenticating threethree
Hibernate: select user0_.id as id1_6_0_, authority2_.name as name1_3_1_, user0_.created_by as created_2_6_0_, user0_.created_date as created_3_6_0_, user0_.last_modified_by as last_mod4_6_0_, user0_.last_modified_date as last_mod5_6_0_, user0_.activated as activate6_6_0_, user0_.activation_key as activati7_6_0_, user0_.email as email8_6_0_, user0_.first_name as first_na9_6_0_, user0_.image_url as image_u10_6_0_, user0_.lang_key as lang_ke11_6_0_, user0_.last_name as last_na12_6_0_, user0_.login as login13_6_0_, user0_.password_hash as passwor14_6_0_, user0_.reset_date as reset_d15_6_0_, user0_.reset_key as reset_k16_6_0_, authoritie1_.user_id as user_id1_7_0__, authoritie1_.authority_name as authorit2_7_0__ from jhi_user user0_ left outer join jhi_user_authority authoritie1_ on user0_.id=authoritie1_.user_id left outer join jhi_authority authority2_ on authoritie1_.authority_name=authority2_.name where user0_.login=?
2020-10-11 22:09:29.889 DEBUG 32249 --- [ XNIO-1 task-55] c.p.c.r.CustomAuditEventRepository       : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-10-11T19:09:29.889420Z, principal=threethree, type=AUTHENTICATION_SUCCESS, data={}]]
2020-10-11 22:09:29.890 DEBUG 32249 --- [ XNIO-1 task-55] c.p.c.r.CustomAuditEventRepository       : Exit: add() with result = null
Hibernate: insert into jhi_persistent_audit_event (event_date, event_type, principal, event_id) values (?, ?, ?, ?)
2020-10-11 22:09:29.892 DEBUG 32249 --- [ XNIO-1 task-55] c.p.c.web.rest.UserJWTController         : Exit: authorize() with result = <200 OK OK,com.privatepayout.candycash.web.rest.UserJWTController$JWTToken@20160f9b,[Authorization:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aHJlZXRocmVlIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTYwNTAzNTM2OX0.A0H5fUm34yoHuf0m9WFWYljPXyfj6aLjRuFk7kRE_pDcnXFh42qdOC3HesbhBzDPUX3S3cZe5QI22q_VzQH5yw"]>
2020-10-11 22:09:30.003 DEBUG 32249 --- [ XNIO-1 task-56] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:09:30.003 DEBUG 32249 --- [ XNIO-1 task-56] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:09:30.004 DEBUG 32249 --- [ XNIO-1 task-56] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated='true', langKey='en', activationKey='OSB8Q88j9ga6883OtdgM'}]
2020-10-11 22:09:30.004 DEBUG 32249 --- [ XNIO-1 task-56] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER]}
2020-10-11 22:09:30.174 DEBUG 32249 --- [   XNIO-1 I/O-1] c.p.c.r.CustomAuditEventRepository       : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-10-11T19:09:30.174245Z, principal=threethree, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2020-10-11 22:09:30.174 DEBUG 32249 --- [   XNIO-1 I/O-1] c.p.c.r.CustomAuditEventRepository       : Exit: add() with result = null
2020-10-11 22:09:30.175 ERROR 32249 --- [   XNIO-1 I/O-1] o.s.w.s.m.StompSubProtocolHandler        : Failed to send client message to application via MessageChannel in session 04mo10od. Sending STOMP ERROR to client.

org.springframework.messaging.MessageDeliveryException: Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:146)
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:122)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageFromClient(StompSubProtocolHandler.java:306)
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:335)
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75)
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56)
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.delegateMessages(AbstractSockJsSession.java:384)
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.handleMessage(WebSocketServerSockJsSession.java:195)
	at org.springframework.web.socket.sockjs.transport.handler.SockJsWebSocketHandler.handleTextMessage(SockJsWebSocketHandler.java:93)
	at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82)
	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:286)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:600)
	at io.undertow.websockets.jsr.FrameHandler.invokeTextHandler(FrameHandler.java:266)
	at io.undertow.websockets.jsr.FrameHandler.onFullTextMessage(FrameHandler.java:317)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105)
	at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90)
	at io.undertow.websockets.jsr.FrameHandler.onText(FrameHandler.java:182)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:952)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:932)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
Caused by: org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.messaging.access.intercept.ChannelSecurityInterceptor.preSend(ChannelSecurityInterceptor.java:69)
	at org.springframework.messaging.support.AbstractMessageChannel$ChannelInterceptorChain.applyPreSend(AbstractMessageChannel.java:178)
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:132)
	... 37 common frames omitted

2020-10-11 22:09:33.289 DEBUG 32249 --- [ XNIO-1 task-58] c.p.candycash.web.rest.OffersResource    : Enter: getAllOffers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:09:33.292 DEBUG 32249 --- [ XNIO-1 task-58] c.p.candycash.web.rest.OffersResource    : REST request to get a page of Offers
2020-10-11 22:09:33.293 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.service.impl.OffersServiceImpl     : Enter: findAll() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:09:33.296 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.service.impl.OffersServiceImpl     : Request to get all Offers
Hibernate: select offers0_.id as id1_8_, offers0_.convex as convex2_8_, offers0_.distribution_type as distribu3_8_, offers0_.duration as duration4_8_, offers0_.hedge as hedge5_8_, offers0_.max_payout as max_payo6_8_, offers0_.max_queue as max_queu7_8_, offers0_.name as name8_8_, offers0_.risk as risk9_8_, offers0_.rollover as rollove10_8_ from offers offers0_ order by offers0_.id asc limit ?
2020-10-11 22:09:33.299 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.service.impl.OffersServiceImpl     : Exit: findAll() with result = Page 1 of 1 containing com.privatepayout.candycash.domain.Offers instances
2020-10-11 22:09:33.300 DEBUG 32249 --- [ XNIO-1 task-58] c.p.candycash.web.rest.OffersResource    : Exit: getAllOffers() with result = <200 OK OK,[Offers{id=2, name='Mexican Peso Mexican Unidad de Inversion (UDI) invoice', risk=27373, maxPayout=15431, distributionType='Ball', convex='false', rollover='false', hedge='false', duration=70751, maxQueue=23761}, Offers{id=3, name='circuit generating', risk=65075, maxPayout=73850, distributionType='front-end RSS', convex='false', rollover='false', hedge='false', duration=12749, maxQueue=59948}, Offers{id=4, name='Central navigating', risk=90457, maxPayout=1568, distributionType='productize holistic cohesive', convex='false', rollover='true', hedge='true', duration=27317, maxQueue=96888}, Offers{id=5, name='Table Customer Cape Verde', risk=66255, maxPayout=73332, distributionType='digital back-end Heard Island and McDonald Islands', convex='false', rollover='true', hedge='false', duration=59370, maxQueue=53059}, Offers{id=6, name='content Licensed Synergized', risk=91185, maxPayout=6245, distributionType='Dam Regional', convex='true', rollover='true', hedge='true', duration=77578, maxQueue=4286}, Offers{id=7, name='Frozen deliver Unions', risk=45356, maxPayout=2838, distributionType='Montana Sleek', convex='false', rollover='true', hedge='true', duration=56868, maxQueue=1037}, Offers{id=8, name='Refined', risk=8136, maxPayout=69488, distributionType='systems payment Gloves', convex='true', rollover='false', hedge='false', duration=1851, maxQueue=66253}, Offers{id=9, name='synthesize Future', risk=42263, maxPayout=60485, distributionType='Directives', convex='false', rollover='true', hedge='true', duration=88953, maxQueue=81205}, Offers{id=10, name='Canadian Dollar matrix', risk=4237, maxPayout=43399, distributionType='Bedfordshire superstructure experiences', convex='false', rollover='false', hedge='true', duration=94364, maxQueue=29438}],[X-Total-Count:"9", Link:"<http://127.0.1.1:8080/api/offers?sort=id%2Casc&cacheBuster=1602443373199&page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/offers?sort=id%2Casc&cacheBuster=1602443373199&page=0&size=20>; rel="first""]>
2020-10-11 22:09:48.335 DEBUG 32249 --- [ XNIO-1 task-60] c.p.candycash.web.rest.UserResource      : Enter: getAllUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:09:48.336 DEBUG 32249 --- [ XNIO-1 task-60] c.p.candycash.service.UserService        : Enter: getAllManagedUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
Hibernate: select user0_.id as id1_6_, user0_.created_by as created_2_6_, user0_.created_date as created_3_6_, user0_.last_modified_by as last_mod4_6_, user0_.last_modified_date as last_mod5_6_, user0_.activated as activate6_6_, user0_.activation_key as activati7_6_, user0_.email as email8_6_, user0_.first_name as first_na9_6_, user0_.image_url as image_u10_6_, user0_.lang_key as lang_ke11_6_, user0_.last_name as last_na12_6_, user0_.login as login13_6_, user0_.password_hash as passwor14_6_, user0_.reset_date as reset_d15_6_, user0_.reset_key as reset_k16_6_ from jhi_user user0_ where user0_.login<>? order by user0_.id asc limit ?
2020-10-11 22:09:48.338 DEBUG 32249 --- [ XNIO-1 task-60] c.p.candycash.service.UserService        : Exit: getAllManagedUsers() with result = Page 1 of 1 containing com.privatepayout.candycash.service.dto.UserDTO instances
2020-10-11 22:09:48.340 DEBUG 32249 --- [ XNIO-1 task-60] c.p.candycash.web.rest.UserResource      : Exit: getAllUsers() with result = <200 OK OK,[UserDTO{login='system', firstName='System', lastName='System', email='system@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user2', firstName='user2', lastName='user2', email='user2@user2.user2', imageUrl='null', activated=true, langKey='en', createdBy=user, createdDate=2020-10-11T19:04:06.574283Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:04:59.767280Z, authorities=[ROLE_USER]}, UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER]}],[X-Total-Count:"5", Link:"<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="first""]>
2020-10-11 22:09:52.695 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.web.rest.UserResource      : Enter: getUser() with argument[s] = [threethree]
2020-10-11 22:09:52.695 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.web.rest.UserResource      : REST request to get User : threethree
2020-10-11 22:09:52.695 DEBUG 32249 --- [ XNIO-1 task-62] c.p.candycash.web.rest.UserResource      : Enter: getAuthorities() with argument[s] = []
2020-10-11 22:09:52.696 DEBUG 32249 --- [ XNIO-1 task-62] c.p.candycash.service.UserService        : Enter: getAuthorities() with argument[s] = []
Hibernate: select authority0_.name as name1_3_ from jhi_authority authority0_
2020-10-11 22:09:52.697 DEBUG 32249 --- [ XNIO-1 task-62] c.p.candycash.service.UserService        : Exit: getAuthorities() with result = [ROLE_ADMIN, ROLE_USER]
2020-10-11 22:09:52.698 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.service.UserService        : Enter: getUserWithAuthoritiesByLogin() with argument[s] = [threethree]
2020-10-11 22:09:52.698 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.service.UserService        : Exit: getUserWithAuthoritiesByLogin() with result = Optional[User{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated='true', langKey='en', activationKey='OSB8Q88j9ga6883OtdgM'}]
2020-10-11 22:09:52.698 DEBUG 32249 --- [ XNIO-1 task-62] c.p.candycash.web.rest.UserResource      : Exit: getAuthorities() with result = [ROLE_ADMIN, ROLE_USER]
2020-10-11 22:09:52.700 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.web.rest.UserResource      : Exit: getUser() with result = <200 OK OK,UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER]},[]>
2020-10-11 22:09:57.424 DEBUG 32249 --- [ XNIO-1 task-63] c.p.candycash.web.rest.UserResource      : Enter: getAllUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:09:57.424 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.web.rest.UserResource      : Enter: updateUser() with argument[s] = [UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=null, createdDate=null, lastModifiedBy='null', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}]
2020-10-11 22:09:57.424 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.web.rest.UserResource      : REST request to update User : UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=null, createdDate=null, lastModifiedBy='null', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:09:57.425 DEBUG 32249 --- [ XNIO-1 task-63] c.p.candycash.service.UserService        : Enter: getAllManagedUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
Hibernate: select user0_.id as id1_6_, user0_.created_by as created_2_6_, user0_.created_date as created_3_6_, user0_.last_modified_by as last_mod4_6_, user0_.last_modified_date as last_mod5_6_, user0_.activated as activate6_6_, user0_.activation_key as activati7_6_, user0_.email as email8_6_, user0_.first_name as first_na9_6_, user0_.image_url as image_u10_6_, user0_.lang_key as lang_ke11_6_, user0_.last_name as last_na12_6_, user0_.login as login13_6_, user0_.password_hash as passwor14_6_, user0_.reset_date as reset_d15_6_, user0_.reset_key as reset_k16_6_ from jhi_user user0_ where upper(user0_.email)=upper(?)
Hibernate: select user0_.id as id1_6_, user0_.created_by as created_2_6_, user0_.created_date as created_3_6_, user0_.last_modified_by as last_mod4_6_, user0_.last_modified_date as last_mod5_6_, user0_.activated as activate6_6_, user0_.activation_key as activati7_6_, user0_.email as email8_6_, user0_.first_name as first_na9_6_, user0_.image_url as image_u10_6_, user0_.lang_key as lang_ke11_6_, user0_.last_name as last_na12_6_, user0_.login as login13_6_, user0_.password_hash as passwor14_6_, user0_.reset_date as reset_d15_6_, user0_.reset_key as reset_k16_6_ from jhi_user user0_ where user0_.login<>? order by user0_.id asc limit ?
Hibernate: select user0_.id as id1_6_, user0_.created_by as created_2_6_, user0_.created_date as created_3_6_, user0_.last_modified_by as last_mod4_6_, user0_.last_modified_date as last_mod5_6_, user0_.activated as activate6_6_, user0_.activation_key as activati7_6_, user0_.email as email8_6_, user0_.first_name as first_na9_6_, user0_.image_url as image_u10_6_, user0_.lang_key as lang_ke11_6_, user0_.last_name as last_na12_6_, user0_.login as login13_6_, user0_.password_hash as passwor14_6_, user0_.reset_date as reset_d15_6_, user0_.reset_key as reset_k16_6_ from jhi_user user0_ where user0_.login=?
2020-10-11 22:09:57.427 DEBUG 32249 --- [ XNIO-1 task-63] c.p.candycash.service.UserService        : Exit: getAllManagedUsers() with result = Page 1 of 1 containing com.privatepayout.candycash.service.dto.UserDTO instances
2020-10-11 22:09:57.429 DEBUG 32249 --- [ XNIO-1 task-63] c.p.candycash.web.rest.UserResource      : Exit: getAllUsers() with result = <200 OK OK,[UserDTO{login='system', firstName='System', lastName='System', email='system@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user2', firstName='user2', lastName='user2', email='user2@user2.user2', imageUrl='null', activated=true, langKey='en', createdBy=user, createdDate=2020-10-11T19:04:06.574283Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:04:59.767280Z, authorities=[ROLE_USER]}, UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER]}],[X-Total-Count:"5", Link:"<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="first""]>
2020-10-11 22:09:57.429 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.service.UserService        : Enter: updateUser() with argument[s] = [UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=null, createdDate=null, lastModifiedBy='null', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}]
2020-10-11 22:09:57.430 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.service.UserService        : Changed Information for User: User{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated='true', langKey='en', activationKey='OSB8Q88j9ga6883OtdgM'}
2020-10-11 22:09:57.431 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.service.UserService        : Exit: updateUser() with result = Optional[UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]}]
Hibernate: insert into jhi_user_authority (user_id, authority_name) values (?, ?)
2020-10-11 22:09:57.433 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.web.rest.UserResource      : Exit: updateUser() with result = <200 OK OK,UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]},[X-candycashApp-alert:"userManagement.updated", X-candycashApp-params:"threethree"]>
2020-10-11 22:09:57.703 DEBUG 32249 --- [  XNIO-1 task-1] c.p.candycash.web.rest.UserResource      : Enter: getAllUsers() with argument[s] = [Page request [number: 0, size 20, sort: UNSORTED]]
2020-10-11 22:09:57.704 DEBUG 32249 --- [  XNIO-1 task-1] c.p.candycash.service.UserService        : Enter: getAllManagedUsers() with argument[s] = [Page request [number: 0, size 20, sort: UNSORTED]]
Hibernate: select user0_.id as id1_6_, user0_.created_by as created_2_6_, user0_.created_date as created_3_6_, user0_.last_modified_by as last_mod4_6_, user0_.last_modified_date as last_mod5_6_, user0_.activated as activate6_6_, user0_.activation_key as activati7_6_, user0_.email as email8_6_, user0_.first_name as first_na9_6_, user0_.image_url as image_u10_6_, user0_.lang_key as lang_ke11_6_, user0_.last_name as last_na12_6_, user0_.login as login13_6_, user0_.password_hash as passwor14_6_, user0_.reset_date as reset_d15_6_, user0_.reset_key as reset_k16_6_ from jhi_user user0_ where user0_.login<>? limit ?
Hibernate: select authoritie0_.user_id as user_id1_7_1_, authoritie0_.authority_name as authorit2_7_1_, authority1_.name as name1_3_0_ from jhi_user_authority authoritie0_ inner join jhi_authority authority1_ on authoritie0_.authority_name=authority1_.name where authoritie0_.user_id=?
2020-10-11 22:09:57.706 DEBUG 32249 --- [  XNIO-1 task-1] c.p.candycash.service.UserService        : Exit: getAllManagedUsers() with result = Page 1 of 1 containing com.privatepayout.candycash.service.dto.UserDTO instances
2020-10-11 22:09:57.707 DEBUG 32249 --- [  XNIO-1 task-1] c.p.candycash.web.rest.UserResource      : Exit: getAllUsers() with result = <200 OK OK,[UserDTO{login='system', firstName='System', lastName='System', email='system@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user2', firstName='user2', lastName='user2', email='user2@user2.user2', imageUrl='null', activated=true, langKey='en', createdBy=user, createdDate=2020-10-11T19:04:06.574283Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:04:59.767280Z, authorities=[ROLE_USER]}, UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]}],[X-Total-Count:"5", Link:"<http://127.0.1.1:8080/api/users?page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/users?page=0&size=20>; rel="first""]>
2020-10-11 22:10:07.713 DEBUG 32249 --- [  XNIO-1 task-4] c.p.c.web.rest.PaymentMethodResource     : Enter: getAllPaymentMethods() with argument[s] = []
2020-10-11 22:10:07.713 DEBUG 32249 --- [  XNIO-1 task-4] c.p.c.web.rest.PaymentMethodResource     : REST request to get all PaymentMethods
2020-10-11 22:10:07.714 DEBUG 32249 --- [  XNIO-1 task-4] c.p.c.s.impl.PaymentMethodServiceImpl    : Enter: findAll() with argument[s] = []
2020-10-11 22:10:07.714 DEBUG 32249 --- [  XNIO-1 task-4] c.p.c.s.impl.PaymentMethodServiceImpl    : Request to get all PaymentMethods
Hibernate: select paymentmet0_.id as id1_10_, paymentmet0_.registration as registra2_10_, paymentmet0_.type as type3_10_ from payment_method paymentmet0_
2020-10-11 22:10:07.716 DEBUG 32249 --- [  XNIO-1 task-4] c.p.c.s.impl.PaymentMethodServiceImpl    : Exit: findAll() with result = [PaymentMethod{id=1, type='Garden', registration='2020-10-10T18:44:07Z'}, PaymentMethod{id=2, type='Pataca Shoals wireless', registration='2020-10-11T16:25:53Z'}, PaymentMethod{id=3, type='seamless Roads back-end', registration='2020-10-10T17:38:04Z'}, PaymentMethod{id=4, type='Trail Games', registration='2020-10-11T08:01:07Z'}, PaymentMethod{id=5, type='Michigan Avon', registration='2020-10-10T19:27:48Z'}, PaymentMethod{id=6, type='open-source model Village', registration='2020-10-11T05:24:40Z'}, PaymentMethod{id=7, type='Facilitator', registration='2020-10-11T13:20:32Z'}, PaymentMethod{id=8, type='digital', registration='2020-10-11T08:08:54Z'}, PaymentMethod{id=9, type='red Steel solid state', registration='2020-10-10T19:21:54Z'}, PaymentMethod{id=10, type='Bike Burundi', registration='2020-10-11T15:05:16Z'}]
2020-10-11 22:10:07.717 DEBUG 32249 --- [  XNIO-1 task-4] c.p.c.web.rest.PaymentMethodResource     : Exit: getAllPaymentMethods() with result = [PaymentMethod{id=1, type='Garden', registration='2020-10-10T18:44:07Z'}, PaymentMethod{id=2, type='Pataca Shoals wireless', registration='2020-10-11T16:25:53Z'}, PaymentMethod{id=3, type='seamless Roads back-end', registration='2020-10-10T17:38:04Z'}, PaymentMethod{id=4, type='Trail Games', registration='2020-10-11T08:01:07Z'}, PaymentMethod{id=5, type='Michigan Avon', registration='2020-10-10T19:27:48Z'}, PaymentMethod{id=6, type='open-source model Village', registration='2020-10-11T05:24:40Z'}, PaymentMethod{id=7, type='Facilitator', registration='2020-10-11T13:20:32Z'}, PaymentMethod{id=8, type='digital', registration='2020-10-11T08:08:54Z'}, PaymentMethod{id=9, type='red Steel solid state', registration='2020-10-10T19:21:54Z'}, PaymentMethod{id=10, type='Bike Burundi', registration='2020-10-11T15:05:16Z'}]
2020-10-11 22:10:18.835 DEBUG 32249 --- [  XNIO-1 task-2] c.p.candycash.web.rest.UserResource      : Enter: getAllUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:10:18.836 DEBUG 32249 --- [  XNIO-1 task-2] c.p.candycash.service.UserService        : Enter: getAllManagedUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
Hibernate: select user0_.id as id1_6_, user0_.created_by as created_2_6_, user0_.created_date as created_3_6_, user0_.last_modified_by as last_mod4_6_, user0_.last_modified_date as last_mod5_6_, user0_.activated as activate6_6_, user0_.activation_key as activati7_6_, user0_.email as email8_6_, user0_.first_name as first_na9_6_, user0_.image_url as image_u10_6_, user0_.lang_key as lang_ke11_6_, user0_.last_name as last_na12_6_, user0_.login as login13_6_, user0_.password_hash as passwor14_6_, user0_.reset_date as reset_d15_6_, user0_.reset_key as reset_k16_6_ from jhi_user user0_ where user0_.login<>? order by user0_.id asc limit ?
2020-10-11 22:10:18.838 DEBUG 32249 --- [  XNIO-1 task-2] c.p.candycash.service.UserService        : Exit: getAllManagedUsers() with result = Page 1 of 1 containing com.privatepayout.candycash.service.dto.UserDTO instances
2020-10-11 22:10:18.839 DEBUG 32249 --- [  XNIO-1 task-2] c.p.candycash.web.rest.UserResource      : Exit: getAllUsers() with result = <200 OK OK,[UserDTO{login='system', firstName='System', lastName='System', email='system@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user2', firstName='user2', lastName='user2', email='user2@user2.user2', imageUrl='null', activated=true, langKey='en', createdBy=user, createdDate=2020-10-11T19:04:06.574283Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:04:59.767280Z, authorities=[ROLE_USER]}, UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]}],[X-Total-Count:"5", Link:"<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="first""]>
2020-10-11 22:10:37.037 DEBUG 32249 --- [  XNIO-1 task-5] c.p.c.web.rest.UserJWTController         : Enter: authorize() with argument[s] = [LoginVM{username='threethree', rememberMe=false}]
2020-10-11 22:10:37.037 DEBUG 32249 --- [  XNIO-1 task-5] c.p.c.security.DomainUserDetailsService  : Authenticating threethree
Hibernate: select user0_.id as id1_6_0_, authority2_.name as name1_3_1_, user0_.created_by as created_2_6_0_, user0_.created_date as created_3_6_0_, user0_.last_modified_by as last_mod4_6_0_, user0_.last_modified_date as last_mod5_6_0_, user0_.activated as activate6_6_0_, user0_.activation_key as activati7_6_0_, user0_.email as email8_6_0_, user0_.first_name as first_na9_6_0_, user0_.image_url as image_u10_6_0_, user0_.lang_key as lang_ke11_6_0_, user0_.last_name as last_na12_6_0_, user0_.login as login13_6_0_, user0_.password_hash as passwor14_6_0_, user0_.reset_date as reset_d15_6_0_, user0_.reset_key as reset_k16_6_0_, authoritie1_.user_id as user_id1_7_0__, authoritie1_.authority_name as authorit2_7_0__ from jhi_user user0_ left outer join jhi_user_authority authoritie1_ on user0_.id=authoritie1_.user_id left outer join jhi_authority authority2_ on authoritie1_.authority_name=authority2_.name where user0_.login=?
2020-10-11 22:10:37.151 DEBUG 32249 --- [  XNIO-1 task-5] c.p.c.r.CustomAuditEventRepository       : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-10-11T19:10:37.151661Z, principal=threethree, type=AUTHENTICATION_SUCCESS, data={}]]
2020-10-11 22:10:37.152 DEBUG 32249 --- [  XNIO-1 task-5] c.p.c.r.CustomAuditEventRepository       : Exit: add() with result = null
Hibernate: insert into jhi_persistent_audit_event (event_date, event_type, principal, event_id) values (?, ?, ?, ?)
2020-10-11 22:10:37.154 DEBUG 32249 --- [  XNIO-1 task-5] c.p.c.web.rest.UserJWTController         : Exit: authorize() with result = <200 OK OK,com.privatepayout.candycash.web.rest.UserJWTController$JWTToken@1042c13f,[Authorization:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0aHJlZXRocmVlIiwiYXV0aCI6IlJPTEVfQURNSU4sUk9MRV9VU0VSIiwiZXhwIjoxNjAyNTI5ODM3fQ.N9p34xVmOJDqgYq-LiBRhqDzJX35pN5hL-tJLf1EHYsVSce4nVLCFusipUZWmTA-sdfWAxepkEM3SxpSvCc4NA"]>
2020-10-11 22:10:37.248 DEBUG 32249 --- [  XNIO-1 task-3] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:10:37.249 DEBUG 32249 --- [  XNIO-1 task-3] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:10:37.249 DEBUG 32249 --- [  XNIO-1 task-3] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated='true', langKey='en', activationKey='OSB8Q88j9ga6883OtdgM'}]
2020-10-11 22:10:37.249 DEBUG 32249 --- [  XNIO-1 task-3] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:11:38.047 DEBUG 32249 --- [ XNIO-1 task-13] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:11:38.048 DEBUG 32249 --- [ XNIO-1 task-13] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:11:38.049 DEBUG 32249 --- [ XNIO-1 task-13] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated='true', langKey='en', activationKey='null'}]
2020-10-11 22:11:38.050 DEBUG 32249 --- [ XNIO-1 task-13] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:11:38.796 DEBUG 32249 --- [boundChannel-49] c.p.c.web.websocket.ActivityService      : Sending user tracking data ActivityDTO{sessionId='fcmjguv3', userLogin='admin', ipAddress='/127.0.0.1:60078', page='', time='2020-10-11T19:11:38.796847Z'}
2020-10-11 22:11:39.527 DEBUG 32249 --- [ XNIO-1 task-29] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:11:39.528 DEBUG 32249 --- [ XNIO-1 task-29] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:11:39.528 DEBUG 32249 --- [ XNIO-1 task-29] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated='true', langKey='en', activationKey='null'}]
2020-10-11 22:11:39.529 DEBUG 32249 --- [ XNIO-1 task-29] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:11:39.956 DEBUG 32249 --- [boundChannel-41] c.p.c.web.websocket.ActivityService      : Sending user tracking data ActivityDTO{sessionId='skg1wwbp', userLogin='user', ipAddress='/127.0.0.1:60082', page='', time='2020-10-11T19:11:39.956955Z'}
2020-10-11 22:12:01.487 DEBUG 32249 --- [ XNIO-1 task-39] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:12:01.488 DEBUG 32249 --- [ XNIO-1 task-39] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:12:01.488 DEBUG 32249 --- [ XNIO-1 task-39] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated='true', langKey='en', activationKey='null'}]
2020-10-11 22:12:01.489 DEBUG 32249 --- [ XNIO-1 task-39] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:12:01.921 DEBUG 32249 --- [boundChannel-37] c.p.c.web.websocket.ActivityService      : Sending user tracking data ActivityDTO{sessionId='hvktvd4b', userLogin='user', ipAddress='/127.0.0.1:60092', page='', time='2020-10-11T19:12:01.921794Z'}
2020-10-11 22:12:05.811 DEBUG 32249 --- [ XNIO-1 task-51] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:12:05.812 DEBUG 32249 --- [ XNIO-1 task-51] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:12:05.813 DEBUG 32249 --- [ XNIO-1 task-51] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated='true', langKey='en', activationKey='null'}]
2020-10-11 22:12:05.815 DEBUG 32249 --- [ XNIO-1 task-51] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:12:06.319 DEBUG 32249 --- [boundChannel-50] c.p.c.web.websocket.ActivityService      : Sending user tracking data ActivityDTO{sessionId='k5twfu5s', userLogin='admin', ipAddress='/127.0.0.1:60094', page='', time='2020-10-11T19:12:06.319221Z'}
2020-10-11 22:12:12.078 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.web.rest.ActiveTargetsResource     : Enter: getAllActiveTargets() with argument[s] = []
2020-10-11 22:12:12.078 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.web.rest.ActiveTargetsResource     : REST request to get all ActiveTargets
2020-10-11 22:12:12.079 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.s.impl.ActiveTargetsServiceImpl    : Enter: findAll() with argument[s] = []
2020-10-11 22:12:12.079 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.s.impl.ActiveTargetsServiceImpl    : Request to get all ActiveTargets
Hibernate: select activetarg0_.id as id1_0_, activetarg0_.convex as convex2_0_, activetarg0_.distribution_type as distribu3_0_, activetarg0_.duration as duration4_0_, activetarg0_.hedge as hedge5_0_, activetarg0_.max_payout as max_payo6_0_, activetarg0_.max_queue as max_queu7_0_, activetarg0_.offer as offer8_0_, activetarg0_.risk as risk9_0_, activetarg0_.rollover as rollove10_0_ from active_targets activetarg0_
2020-10-11 22:12:12.080 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.s.impl.ActiveTargetsServiceImpl    : Exit: findAll() with result = [ActiveTargets{id=2, offer='Refined Rubber Chair Metal', risk=59598, maxPayout=16350, distributionType='Sausages Malaysia Accountability', convex='true', rollover='true', hedge='true', duration=41508, maxQueue=13694}, ActiveTargets{id=3, offer='bandwidth payment', risk=83594, maxPayout=34785, distributionType='tertiary', convex='true', rollover='true', hedge='true', duration=18002, maxQueue=40027}, ActiveTargets{id=4, offer='Wooden Advanced Developer', risk=68856, maxPayout=25539, distributionType='Serbia vortals', convex='true', rollover='false', hedge='true', duration=55007, maxQueue=45492}, ActiveTargets{id=5, offer='alarm Mauritania', risk=35906, maxPayout=84888, distributionType='reintermediate Solomon Islands', convex='true', rollover='false', hedge='false', duration=97580, maxQueue=25379}, ActiveTargets{id=6, offer='invoice zero tolerance', risk=90197, maxPayout=73383, distributionType='mobile synthesizing', convex='false', rollover='false', hedge='false', duration=61450, maxQueue=75520}, ActiveTargets{id=7, offer='Grocery multi-state Reunion', risk=43169, maxPayout=42943, distributionType='Pants maximize', convex='false', rollover='false', hedge='false', duration=63342, maxQueue=79865}, ActiveTargets{id=8, offer='Unbranded', risk=50074, maxPayout=26671, distributionType='overriding auxiliary hardware', convex='false', rollover='true', hedge='true', duration=11446, maxQueue=48147}, ActiveTargets{id=9, offer='Tactics aggregate', risk=73650, maxPayout=33265, distributionType='distributed Illinois', convex='true', rollover='false', hedge='true', duration=18689, maxQueue=21410}, ActiveTargets{id=10, offer='HTTP Squares California', risk=77313, maxPayout=36802, distributionType='Branding', convex='true', rollover='true', hedge='true', duration=32727, maxQueue=10387}]
2020-10-11 22:12:12.081 DEBUG 32249 --- [ XNIO-1 task-58] c.p.c.web.rest.ActiveTargetsResource     : Exit: getAllActiveTargets() with result = [ActiveTargets{id=2, offer='Refined Rubber Chair Metal', risk=59598, maxPayout=16350, distributionType='Sausages Malaysia Accountability', convex='true', rollover='true', hedge='true', duration=41508, maxQueue=13694}, ActiveTargets{id=3, offer='bandwidth payment', risk=83594, maxPayout=34785, distributionType='tertiary', convex='true', rollover='true', hedge='true', duration=18002, maxQueue=40027}, ActiveTargets{id=4, offer='Wooden Advanced Developer', risk=68856, maxPayout=25539, distributionType='Serbia vortals', convex='true', rollover='false', hedge='true', duration=55007, maxQueue=45492}, ActiveTargets{id=5, offer='alarm Mauritania', risk=35906, maxPayout=84888, distributionType='reintermediate Solomon Islands', convex='true', rollover='false', hedge='false', duration=97580, maxQueue=25379}, ActiveTargets{id=6, offer='invoice zero tolerance', risk=90197, maxPayout=73383, distributionType='mobile synthesizing', convex='false', rollover='false', hedge='false', duration=61450, maxQueue=75520}, ActiveTargets{id=7, offer='Grocery multi-state Reunion', risk=43169, maxPayout=42943, distributionType='Pants maximize', convex='false', rollover='false', hedge='false', duration=63342, maxQueue=79865}, ActiveTargets{id=8, offer='Unbranded', risk=50074, maxPayout=26671, distributionType='overriding auxiliary hardware', convex='false', rollover='true', hedge='true', duration=11446, maxQueue=48147}, ActiveTargets{id=9, offer='Tactics aggregate', risk=73650, maxPayout=33265, distributionType='distributed Illinois', convex='true', rollover='false', hedge='true', duration=18689, maxQueue=21410}, ActiveTargets{id=10, offer='HTTP Squares California', risk=77313, maxPayout=36802, distributionType='Branding', convex='true', rollover='true', hedge='true', duration=32727, maxQueue=10387}]
2020-10-11 22:13:36.575 DEBUG 32249 --- [ XNIO-1 task-60] c.p.candycash.web.rest.OffersResource    : Enter: getAllOffers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:13:36.576 DEBUG 32249 --- [ XNIO-1 task-60] c.p.candycash.web.rest.OffersResource    : REST request to get a page of Offers
2020-10-11 22:13:36.576 DEBUG 32249 --- [ XNIO-1 task-60] c.p.c.service.impl.OffersServiceImpl     : Enter: findAll() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:13:36.576 DEBUG 32249 --- [ XNIO-1 task-60] c.p.c.service.impl.OffersServiceImpl     : Request to get all Offers
Hibernate: select offers0_.id as id1_8_, offers0_.convex as convex2_8_, offers0_.distribution_type as distribu3_8_, offers0_.duration as duration4_8_, offers0_.hedge as hedge5_8_, offers0_.max_payout as max_payo6_8_, offers0_.max_queue as max_queu7_8_, offers0_.name as name8_8_, offers0_.risk as risk9_8_, offers0_.rollover as rollove10_8_ from offers offers0_ order by offers0_.id asc limit ?
2020-10-11 22:13:36.578 DEBUG 32249 --- [ XNIO-1 task-60] c.p.c.service.impl.OffersServiceImpl     : Exit: findAll() with result = Page 1 of 1 containing com.privatepayout.candycash.domain.Offers instances
2020-10-11 22:13:36.579 DEBUG 32249 --- [ XNIO-1 task-60] c.p.candycash.web.rest.OffersResource    : Exit: getAllOffers() with result = <200 OK OK,[Offers{id=2, name='Mexican Peso Mexican Unidad de Inversion (UDI) invoice', risk=27373, maxPayout=15431, distributionType='Ball', convex='false', rollover='false', hedge='false', duration=70751, maxQueue=23761}, Offers{id=3, name='circuit generating', risk=65075, maxPayout=73850, distributionType='front-end RSS', convex='false', rollover='false', hedge='false', duration=12749, maxQueue=59948}, Offers{id=4, name='Central navigating', risk=90457, maxPayout=1568, distributionType='productize holistic cohesive', convex='false', rollover='true', hedge='true', duration=27317, maxQueue=96888}, Offers{id=5, name='Table Customer Cape Verde', risk=66255, maxPayout=73332, distributionType='digital back-end Heard Island and McDonald Islands', convex='false', rollover='true', hedge='false', duration=59370, maxQueue=53059}, Offers{id=6, name='content Licensed Synergized', risk=91185, maxPayout=6245, distributionType='Dam Regional', convex='true', rollover='true', hedge='true', duration=77578, maxQueue=4286}, Offers{id=7, name='Frozen deliver Unions', risk=45356, maxPayout=2838, distributionType='Montana Sleek', convex='false', rollover='true', hedge='true', duration=56868, maxQueue=1037}, Offers{id=8, name='Refined', risk=8136, maxPayout=69488, distributionType='systems payment Gloves', convex='true', rollover='false', hedge='false', duration=1851, maxQueue=66253}, Offers{id=9, name='synthesize Future', risk=42263, maxPayout=60485, distributionType='Directives', convex='false', rollover='true', hedge='true', duration=88953, maxQueue=81205}, Offers{id=10, name='Canadian Dollar matrix', risk=4237, maxPayout=43399, distributionType='Bedfordshire superstructure experiences', convex='false', rollover='false', hedge='true', duration=94364, maxQueue=29438}],[X-Total-Count:"9", Link:"<http://127.0.1.1:8080/api/offers?sort=id%2Casc&cacheBuster=1602443616405&page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/offers?sort=id%2Casc&cacheBuster=1602443616405&page=0&size=20>; rel="first""]>
2020-10-11 22:13:42.407 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:13:42.408 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:13:42.408 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated='true', langKey='en', activationKey='OSB8Q88j9ga6883OtdgM'}]
2020-10-11 22:13:42.408 DEBUG 32249 --- [ XNIO-1 task-61] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:13:50.261 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.web.rest.UserResource      : Enter: getAllUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:13:50.262 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.service.UserService        : Enter: getAllManagedUsers() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
Hibernate: select user0_.id as id1_6_, user0_.created_by as created_2_6_, user0_.created_date as created_3_6_, user0_.last_modified_by as last_mod4_6_, user0_.last_modified_date as last_mod5_6_, user0_.activated as activate6_6_, user0_.activation_key as activati7_6_, user0_.email as email8_6_, user0_.first_name as first_na9_6_, user0_.image_url as image_u10_6_, user0_.lang_key as lang_ke11_6_, user0_.last_name as last_na12_6_, user0_.login as login13_6_, user0_.password_hash as passwor14_6_, user0_.reset_date as reset_d15_6_, user0_.reset_key as reset_k16_6_ from jhi_user user0_ where user0_.login<>? order by user0_.id asc limit ?
2020-10-11 22:13:50.264 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.service.UserService        : Exit: getAllManagedUsers() with result = Page 1 of 1 containing com.privatepayout.candycash.service.dto.UserDTO instances
2020-10-11 22:13:50.265 DEBUG 32249 --- [ XNIO-1 task-64] c.p.candycash.web.rest.UserResource      : Exit: getAllUsers() with result = <200 OK OK,[UserDTO{login='system', firstName='System', lastName='System', email='system@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}, UserDTO{login='user2', firstName='user2', lastName='user2', email='user2@user2.user2', imageUrl='null', activated=true, langKey='en', createdBy=user, createdDate=2020-10-11T19:04:06.574283Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:04:59.767280Z, authorities=[ROLE_USER]}, UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]}],[X-Total-Count:"5", Link:"<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/users?sort=id%2Casc&page=0&size=20>; rel="first""]>
2020-10-11 22:14:23.427 DEBUG 32249 --- [  XNIO-1 task-6] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:14:23.429 DEBUG 32249 --- [  XNIO-1 task-6] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:14:23.429 DEBUG 32249 --- [  XNIO-1 task-6] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated='true', langKey='en', activationKey='null'}]
2020-10-11 22:14:23.430 DEBUG 32249 --- [  XNIO-1 task-6] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:14:23.958 DEBUG 32249 --- [boundChannel-62] c.p.c.web.websocket.ActivityService      : Sending user tracking data ActivityDTO{sessionId='bbuzcptf', userLogin='admin', ipAddress='/127.0.0.1:60108', page='', time='2020-10-11T19:14:23.958595Z'}
2020-10-11 22:14:39.347 DEBUG 32249 --- [ XNIO-1 task-15] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:14:39.347 DEBUG 32249 --- [ XNIO-1 task-15] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:14:39.348 DEBUG 32249 --- [ XNIO-1 task-15] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated='true', langKey='en', activationKey='OSB8Q88j9ga6883OtdgM'}]
2020-10-11 22:14:39.348 DEBUG 32249 --- [ XNIO-1 task-15] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='threethree', firstName='aaa', lastName='', email='threethree@threethree.com', imageUrl='null', activated=true, langKey='en', createdBy=anonymousUser, createdDate=2020-10-11T19:06:11.789109Z, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:08:57.218275Z, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:15:15.820 DEBUG 32249 --- [ XNIO-1 task-16] c.p.c.web.rest.PaymentMethodResource     : Enter: getAllPaymentMethods() with argument[s] = []
2020-10-11 22:15:15.821 DEBUG 32249 --- [ XNIO-1 task-16] c.p.c.web.rest.PaymentMethodResource     : REST request to get all PaymentMethods
2020-10-11 22:15:15.821 DEBUG 32249 --- [ XNIO-1 task-16] c.p.c.s.impl.PaymentMethodServiceImpl    : Enter: findAll() with argument[s] = []
2020-10-11 22:15:15.821 DEBUG 32249 --- [ XNIO-1 task-16] c.p.c.s.impl.PaymentMethodServiceImpl    : Request to get all PaymentMethods
Hibernate: select paymentmet0_.id as id1_10_, paymentmet0_.registration as registra2_10_, paymentmet0_.type as type3_10_ from payment_method paymentmet0_
2020-10-11 22:15:15.822 DEBUG 32249 --- [ XNIO-1 task-16] c.p.c.s.impl.PaymentMethodServiceImpl    : Exit: findAll() with result = [PaymentMethod{id=1, type='Garden', registration='2020-10-10T18:44:07Z'}, PaymentMethod{id=2, type='Pataca Shoals wireless', registration='2020-10-11T16:25:53Z'}, PaymentMethod{id=3, type='seamless Roads back-end', registration='2020-10-10T17:38:04Z'}, PaymentMethod{id=4, type='Trail Games', registration='2020-10-11T08:01:07Z'}, PaymentMethod{id=5, type='Michigan Avon', registration='2020-10-10T19:27:48Z'}, PaymentMethod{id=6, type='open-source model Village', registration='2020-10-11T05:24:40Z'}, PaymentMethod{id=7, type='Facilitator', registration='2020-10-11T13:20:32Z'}, PaymentMethod{id=8, type='digital', registration='2020-10-11T08:08:54Z'}, PaymentMethod{id=9, type='red Steel solid state', registration='2020-10-10T19:21:54Z'}, PaymentMethod{id=10, type='Bike Burundi', registration='2020-10-11T15:05:16Z'}]
2020-10-11 22:15:15.823 DEBUG 32249 --- [ XNIO-1 task-16] c.p.c.web.rest.PaymentMethodResource     : Exit: getAllPaymentMethods() with result = [PaymentMethod{id=1, type='Garden', registration='2020-10-10T18:44:07Z'}, PaymentMethod{id=2, type='Pataca Shoals wireless', registration='2020-10-11T16:25:53Z'}, PaymentMethod{id=3, type='seamless Roads back-end', registration='2020-10-10T17:38:04Z'}, PaymentMethod{id=4, type='Trail Games', registration='2020-10-11T08:01:07Z'}, PaymentMethod{id=5, type='Michigan Avon', registration='2020-10-10T19:27:48Z'}, PaymentMethod{id=6, type='open-source model Village', registration='2020-10-11T05:24:40Z'}, PaymentMethod{id=7, type='Facilitator', registration='2020-10-11T13:20:32Z'}, PaymentMethod{id=8, type='digital', registration='2020-10-11T08:08:54Z'}, PaymentMethod{id=9, type='red Steel solid state', registration='2020-10-10T19:21:54Z'}, PaymentMethod{id=10, type='Bike Burundi', registration='2020-10-11T15:05:16Z'}]
2020-10-11 22:15:19.133 DEBUG 32249 --- [ XNIO-1 task-20] c.p.c.web.rest.PaymentMethodResource     : Enter: getAllPaymentMethods() with argument[s] = []
2020-10-11 22:15:19.133 DEBUG 32249 --- [ XNIO-1 task-20] c.p.c.web.rest.PaymentMethodResource     : REST request to get all PaymentMethods
2020-10-11 22:15:19.134 DEBUG 32249 --- [ XNIO-1 task-20] c.p.c.s.impl.PaymentMethodServiceImpl    : Enter: findAll() with argument[s] = []
2020-10-11 22:15:19.134 DEBUG 32249 --- [ XNIO-1 task-20] c.p.c.s.impl.PaymentMethodServiceImpl    : Request to get all PaymentMethods
Hibernate: select paymentmet0_.id as id1_10_, paymentmet0_.registration as registra2_10_, paymentmet0_.type as type3_10_ from payment_method paymentmet0_
2020-10-11 22:15:19.135 DEBUG 32249 --- [ XNIO-1 task-20] c.p.c.s.impl.PaymentMethodServiceImpl    : Exit: findAll() with result = [PaymentMethod{id=1, type='Garden', registration='2020-10-10T18:44:07Z'}, PaymentMethod{id=2, type='Pataca Shoals wireless', registration='2020-10-11T16:25:53Z'}, PaymentMethod{id=3, type='seamless Roads back-end', registration='2020-10-10T17:38:04Z'}, PaymentMethod{id=4, type='Trail Games', registration='2020-10-11T08:01:07Z'}, PaymentMethod{id=5, type='Michigan Avon', registration='2020-10-10T19:27:48Z'}, PaymentMethod{id=6, type='open-source model Village', registration='2020-10-11T05:24:40Z'}, PaymentMethod{id=7, type='Facilitator', registration='2020-10-11T13:20:32Z'}, PaymentMethod{id=8, type='digital', registration='2020-10-11T08:08:54Z'}, PaymentMethod{id=9, type='red Steel solid state', registration='2020-10-10T19:21:54Z'}, PaymentMethod{id=10, type='Bike Burundi', registration='2020-10-11T15:05:16Z'}]
2020-10-11 22:15:19.136 DEBUG 32249 --- [ XNIO-1 task-20] c.p.c.web.rest.PaymentMethodResource     : Exit: getAllPaymentMethods() with result = [PaymentMethod{id=1, type='Garden', registration='2020-10-10T18:44:07Z'}, PaymentMethod{id=2, type='Pataca Shoals wireless', registration='2020-10-11T16:25:53Z'}, PaymentMethod{id=3, type='seamless Roads back-end', registration='2020-10-10T17:38:04Z'}, PaymentMethod{id=4, type='Trail Games', registration='2020-10-11T08:01:07Z'}, PaymentMethod{id=5, type='Michigan Avon', registration='2020-10-10T19:27:48Z'}, PaymentMethod{id=6, type='open-source model Village', registration='2020-10-11T05:24:40Z'}, PaymentMethod{id=7, type='Facilitator', registration='2020-10-11T13:20:32Z'}, PaymentMethod{id=8, type='digital', registration='2020-10-11T08:08:54Z'}, PaymentMethod{id=9, type='red Steel solid state', registration='2020-10-10T19:21:54Z'}, PaymentMethod{id=10, type='Bike Burundi', registration='2020-10-11T15:05:16Z'}]
2020-10-11 22:15:21.078 DEBUG 32249 --- [ XNIO-1 task-18] c.p.candycash.web.rest.OrphansResource   : Enter: getAllOrphans() with argument[s] = []
2020-10-11 22:15:21.081 DEBUG 32249 --- [ XNIO-1 task-18] c.p.candycash.web.rest.OrphansResource   : REST request to get all Orphans
Hibernate: select orphans0_.id as id1_9_, orphans0_.amount as amount2_9_, orphans0_.instant as instant3_9_, orphans0_.method as method4_9_, orphans0_.payout as payout5_9_, orphans0_.risk as risk6_9_ from orphans orphans0_
2020-10-11 22:15:21.084 DEBUG 32249 --- [ XNIO-1 task-18] c.p.candycash.web.rest.OrphansResource   : Exit: getAllOrphans() with result = [Orphans{id=1, amount=62459, risk=40405, payout=15822, instant='2020-10-10T18:46:58Z', method='olive'}, Orphans{id=2, amount=42177, risk=59792, payout=17882, instant='2020-10-11T05:24:12Z', method='context-sensitive Credit Card Account system'}, Orphans{id=3, amount=99433, risk=92694, payout=34943, instant='2020-10-11T12:34:36Z', method='Stravenue'}, Orphans{id=4, amount=91891, risk=31976, payout=73282, instant='2020-10-11T11:57:11Z', method='Baby Distributed SMTP'}, Orphans{id=5, amount=9035, risk=3366, payout=69221, instant='2020-10-11T02:55:51Z', method='secured line'}, Orphans{id=6, amount=16467, risk=76379, payout=67513, instant='2020-10-10T18:50:30Z', method='Optimization Plaza'}, Orphans{id=7, amount=88953, risk=28324, payout=76766, instant='2020-10-11T15:06:07Z', method='Mouse compress Savings Account'}, Orphans{id=8, amount=18127, risk=29437, payout=66349, instant='2020-10-10T23:19:26Z', method='customer loyalty'}, Orphans{id=9, amount=50240, risk=45630, payout=70871, instant='2020-10-10T20:10:06Z', method='Rubber'}, Orphans{id=10, amount=26351, risk=21895, payout=5544, instant='2020-10-11T11:08:55Z', method='Nuevo Sol Martinique'}]
2020-10-11 22:15:35.674 DEBUG 32249 --- [ XNIO-1 task-19] c.p.c.web.rest.UserJWTController         : Enter: authorize() with argument[s] = [LoginVM{username='admin', rememberMe=false}]
2020-10-11 22:15:35.674 DEBUG 32249 --- [ XNIO-1 task-19] c.p.c.security.DomainUserDetailsService  : Authenticating admin
2020-10-11 22:15:35.772 DEBUG 32249 --- [ XNIO-1 task-19] c.p.c.r.CustomAuditEventRepository       : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-10-11T19:15:35.771813Z, principal=admin, type=AUTHENTICATION_SUCCESS, data={}]]
2020-10-11 22:15:35.772 DEBUG 32249 --- [ XNIO-1 task-19] c.p.c.r.CustomAuditEventRepository       : Exit: add() with result = null
Hibernate: insert into jhi_persistent_audit_event (event_date, event_type, principal, event_id) values (?, ?, ?, ?)
2020-10-11 22:15:35.773 DEBUG 32249 --- [ XNIO-1 task-19] c.p.c.web.rest.UserJWTController         : Exit: authorize() with result = <200 OK OK,com.privatepayout.candycash.web.rest.UserJWTController$JWTToken@21d90d4,[Authorization:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTYwMjUzMDEzNX0.ZmL-W1zk1BaM33ov6fr6beDJ4idEjD95sBmqlIE1rK_7vtf0poczBEgVZ6KPGUsa75HDynLnnLBYyjMQEgznJg"]>
2020-10-11 22:15:35.876 DEBUG 32249 --- [ XNIO-1 task-21] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:15:35.876 DEBUG 32249 --- [ XNIO-1 task-21] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:15:35.876 DEBUG 32249 --- [ XNIO-1 task-21] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated='true', langKey='en', activationKey='null'}]
2020-10-11 22:15:35.877 DEBUG 32249 --- [ XNIO-1 task-21] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:15:48.030 DEBUG 32249 --- [ XNIO-1 task-24] c.p.candycash.web.rest.HistoryResource   : Enter: getAllHistories() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:15:48.030 DEBUG 32249 --- [ XNIO-1 task-24] c.p.candycash.web.rest.HistoryResource   : REST request to get a page of Histories
2020-10-11 22:15:48.031 DEBUG 32249 --- [ XNIO-1 task-24] c.p.c.service.impl.HistoryServiceImpl    : Enter: findAll() with argument[s] = [Page request [number: 0, size 20, sort: id: ASC]]
2020-10-11 22:15:48.031 DEBUG 32249 --- [ XNIO-1 task-24] c.p.c.service.impl.HistoryServiceImpl    : Request to get all Histories
Hibernate: select history0_.id as id1_2_, history0_.cost as cost2_2_, history0_.offer as offer3_2_, history0_.payout as payout4_2_, history0_.jhi_when as jhi_when5_2_ from history history0_ order by history0_.id asc limit ?
2020-10-11 22:15:48.032 DEBUG 32249 --- [ XNIO-1 task-24] c.p.c.service.impl.HistoryServiceImpl    : Exit: findAll() with result = Page 1 of 1 containing com.privatepayout.candycash.domain.History instances
2020-10-11 22:15:48.033 DEBUG 32249 --- [ XNIO-1 task-24] c.p.candycash.web.rest.HistoryResource   : Exit: getAllHistories() with result = <200 OK OK,[History{id=2, offer='calculating modular', when='2020-10-11T08:32:12Z', cost=68068, payout=43185}, History{id=3, offer='International', when='2020-10-10T17:07:05Z', cost=81067, payout=31034}, History{id=4, offer='Customer composite', when='2020-10-10T18:15:59Z', cost=1386, payout=84756}, History{id=5, offer='Sleek Fresh Car Georgia', when='2020-10-11T10:38:11Z', cost=65539, payout=80888}, History{id=6, offer='Saint Pierre and Miquelon Planner bypass', when='2020-10-10T21:08:40Z', cost=81711, payout=33379}, History{id=7, offer='Awesome Rubber Sausages Realigned invoice', when='2020-10-11T09:12:54Z', cost=87283, payout=75745}, History{id=8, offer='green bifurcated Mountain', when='2020-10-10T18:49:40Z', cost=20177, payout=64072}, History{id=9, offer='Virginia', when='2020-10-10T22:18:52Z', cost=95191, payout=26519}, History{id=10, offer='discrete', when='2020-10-11T15:12:23Z', cost=24538, payout=93618}],[X-Total-Count:"9", Link:"<http://127.0.1.1:8080/api/histories?sort=id%2Casc&cacheBuster=1602443747927&page=0&size=20>; rel="last",<http://127.0.1.1:8080/api/histories?sort=id%2Casc&cacheBuster=1602443747927&page=0&size=20>; rel="first""]>
2020-10-11 22:15:58.259 DEBUG 32249 --- [ XNIO-1 task-23] c.p.c.web.rest.UserJWTController         : Enter: authorize() with argument[s] = [LoginVM{username='user', rememberMe=false}]
2020-10-11 22:15:58.259 DEBUG 32249 --- [ XNIO-1 task-23] c.p.c.security.DomainUserDetailsService  : Authenticating user
2020-10-11 22:15:58.347 DEBUG 32249 --- [ XNIO-1 task-23] c.p.c.r.CustomAuditEventRepository       : Enter: add() with argument[s] = [AuditEvent [timestamp=2020-10-11T19:15:58.347461Z, principal=user, type=AUTHENTICATION_SUCCESS, data={}]]
2020-10-11 22:15:58.348 DEBUG 32249 --- [ XNIO-1 task-23] c.p.c.r.CustomAuditEventRepository       : Exit: add() with result = null
Hibernate: insert into jhi_persistent_audit_event (event_date, event_type, principal, event_id) values (?, ?, ?, ?)
2020-10-11 22:15:58.353 DEBUG 32249 --- [ XNIO-1 task-23] c.p.c.web.rest.UserJWTController         : Exit: authorize() with result = <200 OK OK,com.privatepayout.candycash.web.rest.UserJWTController$JWTToken@74445f59,[Authorization:"Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiYXV0aCI6IlJPTEVfQURNSU4sUk9MRV9VU0VSIiwiZXhwIjoxNjAyNTMwMTU4fQ.6dS3MaM_FNCuUqjpLB1Ihlo_nh5WjLhQ_vW8Vg4AswmTW322V81hXdX4k_wSz23a6dMuh0zNEwPydNCJ3kQWrg"]>
2020-10-11 22:15:58.488 DEBUG 32249 --- [ XNIO-1 task-25] c.p.candycash.web.rest.AccountResource   : Enter: getAccount() with argument[s] = []
2020-10-11 22:15:58.488 DEBUG 32249 --- [ XNIO-1 task-25] c.p.candycash.service.UserService        : Enter: getUserWithAuthorities() with argument[s] = []
2020-10-11 22:15:58.488 DEBUG 32249 --- [ XNIO-1 task-25] c.p.candycash.service.UserService        : Exit: getUserWithAuthorities() with result = Optional[User{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated='true', langKey='en', activationKey='null'}]
2020-10-11 22:15:58.488 DEBUG 32249 --- [ XNIO-1 task-25] c.p.candycash.web.rest.AccountResource   : Exit: getAccount() with result = UserDTO{login='user', firstName='User', lastName='User', email='user@local.host', imageUrl='null', activated=true, langKey='en', createdBy=system, createdDate=null, lastModifiedBy='admin', lastModifiedDate=2020-10-11T19:02:00.082158Z, authorities=[ROLE_USER, ROLE_ADMIN]}
2020-10-11 22:16:02.171 DEBUG 32249 --- [ XNIO-1 task-28] c.p.c.web.rest.ActiveTargetsResource     : Enter: getAllActiveTargets() with argument[s] = []
2020-10-11 22:16:02.171 DEBUG 32249 --- [ XNIO-1 task-28] c.p.c.web.rest.ActiveTargetsResource     : REST request to get all ActiveTargets
2020-10-11 22:16:02.172 DEBUG 32249 --- [ XNIO-1 task-28] c.p.c.s.impl.ActiveTargetsServiceImpl    : Enter: findAll() with argument[s] = []
2020-10-11 22:16:02.172 DEBUG 32249 --- [ XNIO-1 task-28] c.p.c.s.impl.ActiveTargetsServiceImpl    : Request to get all ActiveTargets
Hibernate: select activetarg0_.id as id1_0_, activetarg0_.convex as convex2_0_, activetarg0_.distribution_type as distribu3_0_, activetarg0_.duration as duration4_0_, activetarg0_.hedge as hedge5_0_, activetarg0_.max_payout as max_payo6_0_, activetarg0_.max_queue as max_queu7_0_, activetarg0_.offer as offer8_0_, activetarg0_.risk as risk9_0_, activetarg0_.rollover as rollove10_0_ from active_targets activetarg0_
2020-10-11 22:16:02.174 DEBUG 32249 --- [ XNIO-1 task-28] c.p.c.s.impl.ActiveTargetsServiceImpl    : Exit: findAll() with result = [ActiveTargets{id=2, offer='Refined Rubber Chair Metal', risk=59598, maxPayout=16350, distributionType='Sausages Malaysia Accountability', convex='true', rollover='true', hedge='true', duration=41508, maxQueue=13694}, ActiveTargets{id=3, offer='bandwidth payment', risk=83594, maxPayout=34785, distributionType='tertiary', convex='true', rollover='true', hedge='true', duration=18002, maxQueue=40027}, ActiveTargets{id=4, offer='Wooden Advanced Developer', risk=68856, maxPayout=25539, distributionType='Serbia vortals', convex='true', rollover='false', hedge='true', duration=55007, maxQueue=45492}, ActiveTargets{id=5, offer='alarm Mauritania', risk=35906, maxPayout=84888, distributionType='reintermediate Solomon Islands', convex='true', rollover='false', hedge='false', duration=97580, maxQueue=25379}, ActiveTargets{id=6, offer='invoice zero tolerance', risk=90197, maxPayout=73383, distributionType='mobile synthesizing', convex='false', rollover='false', hedge='false', duration=61450, maxQueue=75520}, ActiveTargets{id=7, offer='Grocery multi-state Reunion', risk=43169, maxPayout=42943, distributionType='Pants maximize', convex='false', rollover='false', hedge='false', duration=63342, maxQueue=79865}, ActiveTargets{id=8, offer='Unbranded', risk=50074, maxPayout=26671, distributionType='overriding auxiliary hardware', convex='false', rollover='true', hedge='true', duration=11446, maxQueue=48147}, ActiveTargets{id=9, offer='Tactics aggregate', risk=73650, maxPayout=33265, distributionType='distributed Illinois', convex='true', rollover='false', hedge='true', duration=18689, maxQueue=21410}, ActiveTargets{id=10, offer='HTTP Squares California', risk=77313, maxPayout=36802, distributionType='Branding', convex='true', rollover='true', hedge='true', duration=32727, maxQueue=10387}]
2020-10-11 22:16:02.175 DEBUG 32249 --- [ XNIO-1 task-28] c.p.c.web.rest.ActiveTargetsResource     : Exit: getAllActiveTargets() with result = [ActiveTargets{id=2, offer='Refined Rubber Chair Metal', risk=59598, maxPayout=16350, distributionType='Sausages Malaysia Accountability', convex='true', rollover='true', hedge='true', duration=41508, maxQueue=13694}, ActiveTargets{id=3, offer='bandwidth payment', risk=83594, maxPayout=34785, distributionType='tertiary', convex='true', rollover='true', hedge='true', duration=18002, maxQueue=40027}, ActiveTargets{id=4, offer='Wooden Advanced Developer', risk=68856, maxPayout=25539, distributionType='Serbia vortals', convex='true', rollover='false', hedge='true', duration=55007, maxQueue=45492}, ActiveTargets{id=5, offer='alarm Mauritania', risk=35906, maxPayout=84888, distributionType='reintermediate Solomon Islands', convex='true', rollover='false', hedge='false', duration=97580, maxQueue=25379}, ActiveTargets{id=6, offer='invoice zero tolerance', risk=90197, maxPayout=73383, distributionType='mobile synthesizing', convex='false', rollover='false', hedge='false', duration=61450, maxQueue=75520}, ActiveTargets{id=7, offer='Grocery multi-state Reunion', risk=43169, maxPayout=42943, distributionType='Pants maximize', convex='false', rollover='false', hedge='false', duration=63342, maxQueue=79865}, ActiveTargets{id=8, offer='Unbranded', risk=50074, maxPayout=26671, distributionType='overriding auxiliary hardware', convex='false', rollover='true', hedge='true', duration=11446, maxQueue=48147}, ActiveTargets{id=9, offer='Tactics aggregate', risk=73650, maxPayout=33265, distributionType='distributed Illinois', convex='true', rollover='false', hedge='true', duration=18689, maxQueue=21410}, ActiveTargets{id=10, offer='HTTP Squares California', risk=77313, maxPayout=36802, distributionType='Branding', convex='true', rollover='true', hedge='true', duration=32727, maxQueue=10387}]

### PR DESCRIPTION
**Pull request by ruddell**
- add location hook to Routes component to send router location on change
- export sendActivity to enabling sending path from location hook
- only subscribe to tracker endpoint when user is an admin
- disconnect and unsubscribe on logout

Fix #12729

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@ruddell : if you feel confident, plz go ahead and merge it. So it will be included for JH v7 beta

File: generators/client/templates/react/src/main/webapp/app/routes.tsx.ejs [hunk 1]
```diff
@@ -39,6 +39,9 @@ import PrivateRoute from 'app/shared/auth/private-route';
 import ErrorBoundaryRoute from 'app/shared/error/error-boundary-route';
 import PageNotFound from 'app/shared/error/page-not-found';
 import { AUTHORITIES } from 'app/config/constants';
+<%_ if (websocket === 'spring-websocket') { _%>
+import { sendActivity } from "app/config/websocket-middleware";
```
Comment (qmonmert) [inline generators/client/templates/react/src/main/webapp/app/routes.tsx.ejs:43]:
``` diff
+ 'app/config/websocket-middleware'
- "app/config/websocket-middleware"
```
🙂

**Comment by ruddell** [comment]
Bug bounty claimed at https://opencollective.com/generator-jhipster/expenses/30309

**Comment by pascalgrimaud** [comment]
@ruddell : approved

**Comment by pascalgrimaud** [comment]
I restarted the daily builds for React, and it seems not working with Protractor e2e:
- react-websocket 
- gradle-react-websocket
- see https://github.com/hipster-labs/jhipster-daily-builds/actions/runs/435181928
