### PR TITLE
make users login and email to be unique during tests

### LINKED ISSUE #6521: Integration test fail with ConstraintViolationException when User is used twice
##### **Overview of the issue**

In `UserResourceIntTest` the default login is `johndoe` but because the login must be unique, creating a domain object with two relations on User fails with a `ConstraintViolationException`.

##### **Motivation for or Use Case**

The `UserResourceIntTest` sets the default login to a fix value (`johndoe`):

```
public class UserResourceIntTest {
    private static final String DEFAULT_LOGIN = "johndoe";
}
```
Login has a unique constraint defined in the Liquibase file (`unique="true"`):

```
<column name="login" type="varchar(50)">
    <constraints unique="true" nullable="false"/>
</column>
```
So when you have a domain that is related twice (indirectly) to User, two users `johndoe` are created, therefore, there is a `ConstraintViolationException`

##### **Reproduce the error**

Take a JHipster monolith and import the following JDL. Because we can't add extra information on `User`, here, I've created a `Representative` that has a one to one relation to `User`. Now, let's say that an `Invoice` is signed by a `Representative` (a `User`), an `Invoice` is related to a `Contract`, which can be signed by a different `Representative`.

```
entity Contract {
    price Integer,
    discountRate Float,
    vatRate Float,
    nbTicketsAttendee Integer,
    nbTicketsExhibitor Integer,
    additionalInformation String
    createdOn Instant
}

entity Invoice {
    limitPaymentDate LocalDate,
}

entity Representative {
    phoneArea String,
    phoneNumber String
}

relationship ManyToOne {
    Invoice{representativeSigning(lastName) required} to Representative,
    Contract{representativeSigning(lastName) required} to Representative
}

relationship OneToOne {
    Representative{user(lastName) required} to User
}

relationship OneToMany {
    Contract{invoices} to Invoice{contract required}
}
```

The `InvoiceResourceIntTest` creates an invoice, creates and persists the representative for the invoice (therefore, one `johndoe`), creates and persists the representative of the contract (that is the second `johndoe`).

##### **Suggest a Fix**

Because the login must be unique, instead of setting a fix value, it should be a random string. So, instead of:

```
public static User createEntity(EntityManager em) {
    User user = new User();
    user.setLogin(DEFAULT_LOGIN);
    user.setPassword(RandomStringUtils.random(60));
    ...
    return user;
}
```

It could be something like 

```
public static User createEntity(EntityManager em) {
    User user = new User();
    user.setLogin(DEFAULT_LOGIN + RandomStringUtils.random(10));
    user.setPassword(RandomStringUtils.random(60));
    ...
    return user;
}
```

And, instead of checking that the login is equal to `johndoe`:

```
assertThat(testUser.getLogin()).isEqualTo(DEFAULT_LOGIN);
```

Maybe just check that it's starts with `johndoe`:

```
assertThat(testUser.getLogin()).startsWith(DEFAULT_LOGIN);
```

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
##### **JHipster Version(s)**

```
sponsors@0.0.0 /Users/agoncal/Documents/Code/Temp/jhipster/sponsors
└── generator-jhipster@4.9.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.quantixx.sponsor"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "sponsors",
    "packageName": "io.quantixx.sponsor",
    "packageFolder": "io/quantixx/sponsor",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Contract (contract) {
  price Integer,
  discountRate Float,
  vatRate Float,
  nbTicketsAttendee Integer,
  nbTicketsExhibitor Integer,
  additionalInformation String,
  createdOn Instant
}
entity Representative (representative) {
  phoneArea String,
  phoneNumber String
}
entity Invoice (spn_invoice) {
  limitPaymentDate LocalDate
}

relationship OneToOne {
  Representative{user(lastName) required} to User
}
relationship OneToMany {
  Contract{invoices} to Invoice{contract required}
}
relationship ManyToOne {
  Contract{representativeSigning(lastName) required} to Representative,
  Contract{representativeAccepting(lastName) required} to Representative,
  Invoice{representativeSigning(lastName) required} to Representative
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.14.2

node: v8.7.0

npm: 5.4.2

bower: 1.8.0

gulp:
[16:58:25] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.2.1

Docker version 17.09.0-ce, build afdb6d4

### PR DESCRIPTION
**Pull request by duderoot**
sometimes the test are creating multiple users and hose need to have a
unique login and email.

Fixes #6521

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java [hunk 1]
```diff
@@ -192,12 +195,36 @@ public static User createEntity(<% if (databaseType === 'sql') { %>EntityManager
         return user;
     }
 
+    <%_ if (databaseType === 'sql') { _%>
+    /**
+     * Search for the last inserted user id.
+     */
+    public static String getLastInsertedId(EntityManager em){
+        String lastInsertedIdAsString = "";
+        List<User> userList = em.createQuery("select u from User u").getResultList();
```
Comment (gzsombor) [inline generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java]: We should use proper queries - even in tests : 
`Long maxId = em.createQuery("select max(u.id) from User u").getSingleResult()`

Comment (duderoot) [reply generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java]: 10x for the feedback. I totally agree with you on the sorting part. On the second point, regarding the use of singleResult, I want to overcome e NoResultException if  no user exist in the database. I will commit the requested changes.

**Comment by duderoot** [comment]
@gzsombor do you know if there is a way to restart the build, because on my branch all test on travis are passing and here not and I would like to restart the build?

**Comment by gmarziou** [comment]
I restarted the build.

**Comment by duderoot** [comment]
@gmarziou 10x for the support. Unfortunately the build it's still failing, now because of the last  [job](https://travis-ci.org/jhipster/generator-jhipster/jobs/291306512). It's looks like there was a network problem. 
grafik Can you please start again please 😃  10x

**Comment by jdubois** [comment]
No problem, I restarted the job :-)

**Comment by duderoot** [comment]
@jdubois 10x for the restart. Finally, it went green 😄

**Comment by deepu105** [comment]
@gzsombor can you take a look is this ok to merge?

File: generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java [hunk 2]
```diff
@@ -192,12 +192,24 @@ public static User createEntity(<% if (databaseType === 'sql') { %>EntityManager
         return user;
     }
 
+    <%_ if (databaseType === 'sql') { _%>
+    /**
+     * When createEntity is called from other classes is mandatory to create different
+     * login and mail since those have a unique constraint.
+     */
+    private static User createEntityWithDefaults(EntityManager em){
```
Comment (cbornet) [inline generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java]: Is this method really needed ? It could be inlined in the init() method.

Comment (duderoot) [reply generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java]: Sure thing 👍 it just happen 😉 . The method was having for me more of a documentation role, but indeed trough that the code was to verbose, so I just removed.

**Comment by cbornet** [comment]
LGTM

**Comment by deepu105** [comment]
@cbornet go into the travis build and restart the failing one alone to be faster :)

**Comment by gzsombor** [comment]
+1 !

**Comment by cbornet** [comment]
@deepu105 I did this because the CI didn't start at all !
