### PR TITLE
Fix application base name question in Windows Command Prompt

### LINKED ISSUE #13215: Application base name question is unstable in Windows Command Prompt
##### **Overview of the issue**

If in current main branch running linked `jhipster` then `askForModuleName` behaves inadequately in Windows Command Prompt. Question is asked but after entering answer new blank line is shown. After testing found out that must enter base name again into this blank line and this second input is used as application base name.

All works as expected in Git Bash in Windows.

Git bisect shows again first bad commit #13124 which upgraded Prettier to version 2.2.0 via `prettier-plugin-java` and for which solution in #13138 was to upgrade to Node.js LTS version.

If I remember correctly then upgrading Node.js to LTS version worked as expected for me when I was working with #13138. Maybe:
* I don't remember correctly
* or as meanwhile I updated npm to version npm@6.14.9 then this causes this problem
* or some transitive dependency meanwhile changed which causes this problem

I tried to upgrade node.js to v15.3.0 and npm to v7.1.0 but this didn't solve this issue.

##### **Motivation for or Use Case**

`jhipster` should be stable also in Windows Command Prompt.

##### **Reproduce the error**

Run `jhipster` in Windows Command Prompt.

##### **Related issues**

#13138

##### **Suggest a Fix**

While debugging I found out that `askForInsightOptIn` is not asked because condition is not met, but some `async` operation is done internally. After deleting `askForInsightOptIn` question, Windows Command Prompt started to work as expected.
So I try to do PR where condition `shouldWeAskForOptIn()` is moved from `async function askForInsightOptIn()` to constructing questions array (this question is not added to questions array if condition is not met).

##### **JHipster Version(s)**

Current main branch.

##### **Browsers and Operating System**

Windows 10.

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by kaidohallik**
Fixes #13215 

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/app/prompts.js [hunk 1]
```diff
@@ -31,7 +31,6 @@ module.exports = {
 
 async function askForInsightOptIn() {
     const answers = await this.prompt({
```
Comment (mshima) [inline generators/app/prompts.js:33]:
```suggestion
    if (!statistics.shouldWeAskForOptIn()) return;
    const answers = await this.prompt({
```

**Review by mshima — CHANGES_REQUESTED** [review]
Should be easier for blueprints.

**Comment by kaidohallik** [comment]
> Should be easier for blueprints.

Thanks for the suggestions @mshima. Tested and those worked and used suggestions.
