### PR TITLE
Check that upgrade is run from a JHipster project directory

### LINKED ISSUE #6596: jhipster update failed
##### **Overview of the issue**

I installed jhipster on my pc about a week ago (~20 of October 2017). Today I saw that new version released (4.10.1), so I decided to upgrade my installed version. I got an error during upgrate.

##### **Reproduce the error**

Following instructions from http://www.jhipster.tech/2017/10/25/jhipster-release-4.10.1.html  
I updated yarn to the latest version

```
C:\Users\Anatolii>yarn --version
1.2.1

```
and then I run upgrade

```
C:\Users\Anatolii>jhipster upgrade
Using JHipster version installed globally
Executing jhipster:upgrade
Options:
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
Looking for latest generator-jhipster version...
4.10.1
C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:279
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
    at new SemVer (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:279:11)
    at compare (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:566:10)
    at Function.lt (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\semver\semver.js:600:10)
    at shelljs.exec (C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\upgrade\index.js:149:32)
    at C:\Users\Anatolii\AppData\Local\Yarn\config\global\node_modules\shelljs\src\exec.js:199:9
    at ChildProcess.exithandler (child_process.js:189:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

```

Do not know for sure if it is installed correctly or not.
Then I checked current version of intalled jhipster: 

```
C:\Users\Anatolii>jhipster  --version
Using JHipster version installed globally
4.10.1
```

##### **Browsers and Operating System**

Windows 10 Enterprise
CMD application
- [ ] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by gmarziou**
Provide user with a helpful message when jhipster upgrade is run from a directory that is not a JHipster project.

Fix #6596

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/upgrade/index.js [hunk 1]
```diff
@@ -123,6 +123,16 @@ module.exports = class extends BaseGenerator {
 
     get configuring() {
         return {
+
+            assertJHipsterProject() {
+                const done = this.async();
+                if (!(shelljs.test('-f', '.yo-rc.json'))
+                    && !(shelljs.test('-d', '.jhipster'))) {
```
Comment (deepu105) [inline generators/upgrade/index.js]: the `.jhipster` directory will not be present if there are no entities I guess so probabaly just checking yo-rc is enough

Comment (gmarziou) [reply generators/upgrade/index.js]: I thought that looking only at .yo-rc.json would match also non JHipster projects using yeoman.
Though we could have a valid JHipster project without entities if no database.

Comment (deepu105) [reply generators/upgrade/index.js]: You could check if the yo-rc object has `generator-jhipster` as a key

Comment (gmarziou) [reply generators/upgrade/index.js]: Yes much better
