### PR TITLE
generated java tests now passes with unique validation

### LINKED ISSUE #9666: Generated java tests fails when a field has unique validation, entity has filter and is required
##### **Overview of the issue**

Generated java tests fails when a field has unique validation and filter:

```
[ERROR] Errors: 
[ERROR]   EmployeeResourceIT.getAllEmployeesByLocationIsEqualToSomething:324 » Persistence
[INFO] 
[ERROR] Tests run: 141, Failures: 0, Errors: 1, Skipped: 0
```
```
[ERROR] Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.312 s <<< FAILURE! - in com.mycompany.myapp.web.rest.EmployeeResourceIT
[ERROR] getAllEmployeesByLocationIsEqualToSomething  Time elapsed: 0.137 s  <<< ERROR!
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at com.mycompany.myapp.web.rest.EmployeeResourceIT.getAllEmployeesByLocationIsEqualToSomething(EmployeeResourceIT.java:324)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at com.mycompany.myapp.web.rest.EmployeeResourceIT.getAllEmployeesByLocationIsEqualToSomething(EmployeeResourceIT.java:324)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 
Unique index or primary key violation: "PUBLIC.UX_LOCATION_NAME_INDEX_9 ON PUBLIC.LOCATION(NAME) VALUES 4"; SQL statement:
insert into location (id, description, name) values (null, ?, ?) [23505-199]
	at com.mycompany.myapp.web.rest.EmployeeResourceIT.getAllEmployeesByLocationIsEqualToSomething(EmployeeResourceIT.java:324)
```

##### **Motivation for or Use Case**

The generated tests should be passing.

##### **Reproduce the error**

Create a new project with default settings `jhipster`, import JDL `jhipster import-jdl bug.jdl`, run `./mvnw clean install`.

##### **Related issues**

It was also happening in #9563 , but I hadn't identified the cause and it was also happening with other bugs.

##### **Suggest a Fix**

The createEntity shouldn't create entities that have the same value for the field if it is unique, as it could be created twice by other entities that require it.

Another simple solution is not to create a new entity if it was already created. I will try to make a PR to fix it.

##### **JHipster Version(s)**

```
teste-6-simples@0.0.0 /home/gabriel/projetos/teste6simples
└── generator-jhipster@6.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "6.0.0",
    "applicationType": "monolith",
    "baseName": "teste6simples",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": ["pt-br"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
```
entity Employee {
  name String required,
  age Integer required
}
entity Location {
  name String required unique,
  description String
}
relationship ManyToOne {
  Employee{location(name) required} to Location
}
filter Employee
```

##### **Environment and Tools**

<details>
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.11.0

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.6

yarn: 1.15.2

Docker version 18.09.5, build e8ff056dbc

docker-compose version 1.24.0, build 0aa59064
</details>

##### **Browsers and Operating System**

Debian 9

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by Gabrui**
Checks if a required entity is already created in the createEntity method,
adds the creatUpdatedEntity using the UPDATED_ constants and
adds the findAll method to TestUtils.

Fix #9666

-   Please make sure the below checklist is followed for Pull Requests.

-   [x] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs [hunk 1]
```diff
@@ -409,23 +409,24 @@ _%>
             .setValidator(validator).build();
     }
 
+<%_ ['DEFAULT_', 'UPDATED_'].forEach((fieldStatus) => { _%>
     /**
-     * Create an entity for this test.
+     * Create an <% if (fieldStatus === 'UPDATED_') { %>updated<% } %> entity for this test.
```
Comment (pascalgrimaud) [inline generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs]: Should be: `Create an <% if (fieldStatus === 'UPDATED_') { %>updated <% } %>entity for this test.`
Otherwise, we can have: `* Create an  entity for this test.`, with 2 spaces between `an` and `entity`

File: generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs [hunk 2]
```diff
@@ -164,5 +173,23 @@ public final class TestUtil {
         return dfcs;
     }
 
+<%_ if (databaseType === 'sql') { _%>
+    /**
+     * Makes a an executes a query to the EntityManager finding all stored objects.
+     * @param <T> The type of objects to be searched
+     * @param em The instance of the EntityManager
+     * @param clss The class type to be searched
+     * @return A list of all found objects of the
```
Comment (pascalgrimaud) [inline generators/server/templates/src/test/java/package/web/rest/TestUtil.java.ejs]: `A list of all found objects of the` -> ̀A list of all found objects`

File: generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs [hunk 3]
```diff
@@ -409,23 +409,24 @@ _%>
             .setValidator(validator).build();
     }
 
+<%_ ['DEFAULT_', 'UPDATED_'].forEach((fieldStatus) => { _%>
     /**
-     * Create an entity for this test.
+     * Create an <% if (fieldStatus === 'UPDATED_') { %>updated<% } %>entity for this test.
```
Comment (pascalgrimaud) [inline generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs]: ahh still missing 1 space: `%>updated <%`

Comment (pascalgrimaud) [reply generators/entity-server/templates/src/test/java/package/web/rest/EntityResourceIT.java.ejs]: Just fixed directly in your branch

**Comment by pascalgrimaud** [comment]
thanks for your fix @Gabrui !
