### PR TITLE
Fix constraints when customizing table name

### LINKED ISSUE #3723: Error in addForeignKeyConstraint when using overridden table names
##### **Overview of the issue**

Liquibase generated addForeignKeyConstraint seems to use the default entity-name-derived table name rather than the specified/ overridden tablename (using --table-name).

Consider 2 entities Criteria and Option with one-to-many relationship. Both entities are generated using --table-name option as pa_criteria and pa_option. The foreign key generated in pa_option has referencedTableName="criteria" (default table name of Criteria entity) instead of referencedTableName="pa_criteria" (specified table name).

Liquibase fails while creating the fk.

liquibase.exception.DatabaseException: Cannot add foreign key constraint [Failed SQL: ALTER TABLE atlas.pa_option ADD CONSTRAINT fk_option_criteria_id FOREIGN KEY (criteria_id) REFERENCES atlas.criteria (id)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:301)

##### **Motivation for or Use Case** 

Table names can be overridden using --table-name. However, there seem to be an issue when creating references to such entities - requiring manual intervention.

##### **JHipster Version(s)** 

3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 

[.yo-rc.json.txt](https://github.com/jhipster/generator-jhipster/files/317725/default.yo-rc.json.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

[Criteria.json.txt](https://github.com/jhipster/generator-jhipster/files/317728/Criteria.json.txt)
[Option.json.txt](https://github.com/jhipster/generator-jhipster/files/317727/Option.json.txt)

##### **Browsers and Operating System** 

Chrome on Win 8.1 with MySQL 5.7

##### **Reproduce the error** 

    save attached Criteria.json and Option.json in .jhipster/
    yo jhipster:entity criteria --table-name pa_criteria --regenerate
    yo jhipster:entity option --table-name pa_option --regenerate
    check the xxxx_added_entity_constraints_Option.xml - it will have the incorrect referencedTableName="criteria"
    launch the app
    Liquibase will throw an error while processing the xxxx_added_entity_constraints_Option.xml
    
##### **Related issues** 

Did not find any similar cases.

##### **Suggest a Fix** 

The issue could be with the below piece of code

    <addForeignKeyConstraint baseColumnNames="<%= getColumnName(relationshipName) %>_id"
                             baseTableName="<%= entityTableName %>"
                             constraintName="<%= constraintName %>"
                             referencedColumnNames="id"
                             referencedTableName="<%
                             var otherEntityTable = getTableName(otherEntityName);
                             if (otherEntityTable == 'user') { %>jhi_user<% } else { %><%=otherEntityTable %><% } %>"/>

in generator-jhipster/generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml which is using _otherEntityName_ for _getTableName()_. Perhaps, it should use the *'entityTableName'* attribute from the _otherEntity.json_

### PR DESCRIPTION
**Pull request by ruddell**
Fix #3723, this is Option 2 from @jdubois's post in the issue.  It also fixes relationships with user when using a customized jhiPrefix.

Only thing left is to add a test using custom table names to the entity generation step.

### CODE REVIEW

File: generators/entity/index.js [hunk 1]
```diff
@@ -347,6 +348,10 @@ module.exports = EntityGenerator.extend({
                 this.warning('service is missing in .jhipster/' + this.name + '.json, using no as fallback');
                 this.service = 'no';
             }
+            if (_.isUndefined(this.entityTableName)) {
+                this.warning('entityTableName is missing in .jhipster/' + this.name + '.json, using no as fallback');
```
Comment (deepu105) [inline generators/entity/index.js]: can we have message as `using entity name as fallback`?

File: generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml [hunk 2]
```diff
@@ -12,6 +12,14 @@
             relationshipName = relationships[idx].relationshipName,
             ownerSide = relationships[idx].ownerSide,
             otherEntityName = relationships[idx].otherEntityName;
+            if (otherEntityName === 'user') {
+                otherEntityTableName = jhiPrefix + '_user';
```
Comment (deepu105) [inline generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml]: I dont think we should prefix `jhiPrefix ` for user table as the table name for user will always be `jhi_user` see [this](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/liquibase/changelog/_initial_schema.xml#L23)
so if user sets a jhiPrefix then this will fail, it works only with default prefix which is `jhi`

File: generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml [hunk 3]
```diff
@@ -12,6 +12,14 @@
...
+            } else {
+                otherEntityTableName = getEntityProperty(otherEntityName, 'entityTableName');
+                if (otherEntityTableName === undefined) {
```
Comment (deepu105) [inline generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml]: you are returning null always from the method so this will not be undefined. plz change to `if (otherEntityTableName) {` so that null, undefined and empty is checked

Comment (deepu105) [inline generators/entity/templates/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml]: it should be `if (!otherEntityTableName) `

**Comment by ruddell** [comment]
Thanks for reviewing the changes.  You're right about the prefix, it's only used in the JS.  I will fix these and add the test in the morning.
