### PR TITLE
load initial UAA servers from discovery client if not using hazelcast

### LINKED ISSUE #4005: No instances available for uaa when start new microservice application
##### **Overview of the issue**

~~~
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tokenStore' defined in class path resource [it/seiton/turnigo/web/mobgateway/config/MicroserviceSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.TokenStore]: Factory method 'tokenStore' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAccessTokenConverter' defined in class path resource [it/seiton/turnigo/web/mobgateway/config/MicroserviceSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.IllegalStateException: No instances available for uaa
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1054)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1019)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
        ... 22 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.TokenStore]: Factory method 'tokenStore' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAccessTokenConverter' defined in class path resource [it/seiton/turnigo/web/mobgateway/config/MicroserviceSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.IllegalStateException: No instances available for uaa
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 35 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAccessTokenConverter' defined in class path resource [it/seiton/turnigo/web/mobgateway/config/MicroserviceSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.IllegalStateException: No instances available for uaa
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:381)
        at it.seiton.turnigo.web.mobgateway.config.MicroserviceSecurityConfiguration$$EnhancerBySpringCGLIB$$8a3a3561.jwtAccessTokenConverter(<generated>)
        at it.seiton.turnigo.web.mobgateway.config.MicroserviceSecurityConfiguration.tokenStore(MicroserviceSecurityConfiguration.java:60)
        at it.seiton.turnigo.web.mobgateway.config.MicroserviceSecurityConfiguration$$EnhancerBySpringCGLIB$$8a3a3561.CGLIB$tokenStore$1(<generated>)
        at it.seiton.turnigo.web.mobgateway.config.MicroserviceSecurityConfiguration$$EnhancerBySpringCGLIB$$8a3a3561$$FastClassBySpringCGLIB$$5c61a0cd.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
        at it.seiton.turnigo.web.mobgateway.config.MicroserviceSecurityConfiguration$$EnhancerBySpringCGLIB$$8a3a3561.tokenStore(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 36 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is java.lang.IllegalStateException: No instances available for uaa
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
        ... 57 common frames omitted
Caused by: java.lang.IllegalStateException: No instances available for uaa
        at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.execute(RibbonLoadBalancerClient.java:79)
~~~

##### **Motivation for or Use Case**

When start pure jhipster microservice application mobile gateway not working.

when i log all services : 

```java
private String getKeyFromAuthorizationServer() {

          List<String> services = discoveryClient.getServices();
          log.error("-----SERVICE------");
          for(String s: services){
              log.info("service : " + s + "");
          }

.........
```
i have got log : 

> 2016-08-18 21:38:21.868 ERROR 6346 --- [  restartedMain] .w.m.c.MicroserviceSecurityConfiguration : -----SERVICE------
2016-08-18 21:38:21.868  INFO 6346 --- [  restartedMain] .w.m.c.MicroserviceSecurityConfiguration : service : uaa

so its seems that service exist .

##### **Reproduce the error**

1. Install new Jhipster version
2. Create UAA service with cassandra
3. Create cassandra keyspace and tables
4. Create mobile-gateway
5. Copy jhipster-registry from github
6. Start jhipster-registry
7. Start uaa
8. Start mogile-gateway --- ERROR

##### **Suggest a Fix**

Something with mobile gateway configuration.
It't very weird because when i modify MicroserviceSecurityConfiguration : 

```java
private String getKeyFromAuthorizationServer() {
          List<String> services = discoveryClient.getServices();

          HttpEntity<Void> request = new HttpEntity<Void>(new HttpHeaders());
          String value = (String) this.keyUriRestTemplate
              .exchange("http://uaa/oauth/token_key", HttpMethod.GET, request, Map.class).getBody()
              .get("value");

          return value;
      }

```` 
It's working like a charm. Its seems that its lazy loading of something like that. 

So basically that one line fix issue : 

```java
List<String> services = discoveryClient.getServices();
```
 
##### **JHipster Version(s)**

"jhipsterVersion": "3.6.1",

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

~~~
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "turnigo_mobgateway",
    "packageName": "it.seiton.turnigo.web.mobgateway",
    "packageFolder": "it/seiton/turnigo/web/mobgateway",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": "no",
    "buildTool": "gradle",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ca",
      "zh-cn",
      "zh-tw",
      "cs",
      "da",
      "nl",
      "fr",
      "gl",
      "de",
      "el",
      "hi",
      "hu",
      "it",
      "ja",
      "ko",
      "mr",
      "pl",
      "pt-br",
      "pt-pt",
      "ro",
      "ru",
      "sk",
      "es",
      "sv",
      "tr",
      "ta"
    ]
  }
}
~~~
Hi here is uaa yo-rc configuration
~~~

`{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "uaa",
    "packageName": "it.seiton.turnigo.web.uaa",
    "packageFolder": "it/seiton/turnigo/web/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "no",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": "no",
    "buildTool": "gradle",
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ca",
      "zh-cn",
      "zh-tw",
      "cs",
      "da",
      "nl",
      "fr",
      "gl",
      "de",
      "el",
      "hi",
      "hu",
      "it",
      "ja",
      "ko",
      "mr",
      "pl",
      "pt-br",
      "pt-pt",
      "ro",
      "ru",
      "sk",
      "es",
      "sv",
      "tr",
      "ta"
    ]
  }
}`
~~~

##### **Browsers and Operating System**

This is my screen from jhipster-registry:
screen shot 2016-08-18 at 21 00 42

OSX EL Capitan version 10.11.6

### PR DESCRIPTION
**Pull request by ruddell**
Fix #4005

This was the cleanest way I could find to fix the issue.  Normally Hazelcast calls the discovery client in CacheConfiguration.  You can confirm the call to `discoveryClient.getInstances(serviceId)` is the reason the app works by commenting it out and the app won't find any UAA servers (the issue).   Without a call to the discovery client, the UAA route is never loaded.  Please let me know if there's a better way.

Pinging @xetys as he was the other person working on the issue.

### CODE REVIEW

File: generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java [hunk 1]
```diff
@@ -101,6 +104,11 @@ public SecurityEvaluationContextExtension securityEvaluationContextExtension() {
     @Inject
     JHipsterProperties jHipsterProperties;
 
+    <%_ if (hibernateCache !== 'hazelcast') { _%>
```
Comment (xetys) [inline generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java]: are you sure this has to be bound to hazelcast? the issue currently happens only, because spring loads hazelcast long enough to have the client fetched services onetime....

with this hack you just force to do this twice at this point, so the second request will have already service loaded

I think, if we do this, then for all....

one other consideration is to make this "token-key-fetch" thing optional for some profile, because this behavior is making a lot of trouble, not only that service fetch thing...

Comment (ruddell) [inline generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java]: You're right, I changed the PR to always load the discovery client because it isn't bound to Hazelcast.  

When does this cause other issues?  I didn't have any issues in dev/prod/test profiles.
