### PR TITLE
fix command path in upgrade/index.js for windows users

### LINKED ISSUE #6161: upgrade fail under windows
##### **Overview of the issue**

I tried to upgrade my code to 4.6.2 but encountered error:

$ jhipster upgrade
Executing jhipster:upgrade
Options:
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
Looking for latest generator-jhipster version...
New generator-jhipster version found: 4.6.2
Git repository detected
Checked out branch "jhipster_upgrade"
Updating generator-jhipster to 4.6.2 . This might take some time...
Updated generator-jhipster to version 4.6.2
Cleaned up directory
Regenerating application with JHipster 4.6.2...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Something went wrong while generating project! '$' is not recognized as an internal or external command,
operable program or batch file.

    at Environment.error (C:\Users\Powerful User\AppData\Local\Yarn\config\global\node_modules\yeoman-environment\lib\environment.js:140:40)
    at constructor.error (C:\Users\Powerful User\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\generator-base.js:1610:18)
    at shelljs.exec (C:\Users\Powerful User\AppData\Local\Yarn\config\global\node_modules\generator-jhipster\generators\upgrade\index.js:86:23)
    at C:\Users\Powerful User\AppData\Local\Yarn\config\global\node_modules\shelljs\src\exec.js:204:9
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

##### **Motivation for or Use Case**

To help who encounter same issue under windows when upgrading a jhipster generated project

##### **Reproduce the error**

Step 1: 
yarn global upgrade generator-jhipster

Step 2:
jhipster upgrade

This error occurs in power shell AND git bash.

##### **Related issues**

None

##### **JHipster Version(s)**

Upgraded jhipster generator to 4.6.2 then try to upgrade my code base from 4.5.6 to 4.6.2

##### **JHipster configuration**

$ jhipster info
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
C:\code\sibodell-hse\hse-backend
`-- generator-jhipster@4.6.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.bigcompany.hse",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "hse",
    "packageName": "com.bigcompany.hse",
    "packageFolder": "com/bigcompany/hse",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

git version 2.12.2.windows.2

node: v6.10.2

npm: 5.0.4

bower: 1.8.0

gulp:
[12:11:04] CLI version 1.3.0
[12:11:04] Local version 3.9.1

yeoman: 2.0.0

yarn: 0.27.5

Docker version 1.12.5, build 7392c3b

docker-compose version 1.9.0, build 2585387

Execution complete

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

NONE (We generated some entities then moved the .json files to other directory, this bug should have nothing to do with entities)

##### **Browsers and Operating System**

Windows 10 Pro

- [* ] Checking this box is mandatory (yes, I've read everything)

### PR DESCRIPTION
**Pull request by iconben**
Fix #6161

### CODE REVIEW

File: generators/upgrade/index.js [hunk 1]
```diff
@@ -79,7 +79,8 @@ module.exports = UpgradeGenerator.extend({
         this.log(`Regenerating application with JHipster ${version}...`);
         let generatorCommand = 'yo jhipster';
         if (semver.gte(version, FIRST_CLI_SUPPORTED_VERSION)) {
-            generatorCommand = this.clientPackageManager === 'yarn' ? '$(yarn bin)/jhipster' : '$(npm bin)/jhipster';
+            const generatorDir = this.clientPackageManager === 'yarn' ? shelljs.exec('yarn bin') : shelljs.exec('npm bin');
```
Comment (gmarziou) [inline generators/upgrade/index.js]: I would turn off console output:

`shelljs.exec('yarn bin', {silent: true})`

Comment (gmarziou) [inline generators/upgrade/index.js]: Also according to the [doc](https://github.com/shelljs/shelljs#execcommand--options--callback) sync exec should use stdout, though it seems to work without it.

shelljs.exec('yarn bin', {silent: true}).stdout;

Comment (iconben) [inline generators/upgrade/index.js]: Oh yes, forgot to do that, thanks.

**Comment by iconben** [comment]
@gmarziou thanks for review comments. Not sure if you mean you'll change the code by yourself or need my follow-up. Guess you guys are busy so anyway I did the change to save your time. 
Best Regards.

File: generators/upgrade/index.js [hunk 2]
```diff
@@ -79,7 +79,8 @@ module.exports = UpgradeGenerator.extend({
         this.log(`Regenerating application with JHipster ${version}...`);
         let generatorCommand = 'yo jhipster';
         if (semver.gte(version, FIRST_CLI_SUPPORTED_VERSION)) {
-            generatorCommand = this.clientPackageManager === 'yarn' ? '$(yarn bin)/jhipster' : '$(npm bin)/jhipster';
+            const generatorDir = this.clientPackageManager === 'yarn' ? shelljs.exec('yarn bin', { silent: true }).stdout : shelljs.exec('npm bin', { silent: true }).stdout;
```
Comment (ruddell) [inline generators/upgrade/index.js]: Please change ` { silent: true }` to ` { silent: this.silent }` so that the `--verbose` flag will print the result of the command (this is how the rest of the shelljs commands in this file are set up)
