### PR TITLE
parse ids as uuid in ui router states for mongo and cassandra, fix #2735

### LINKED ISSUE #2735: Edit entities when using mongo doesn't work
When using mongodb you can't edit entites at the moment. It looks like the id is not correctly transferred to to backend. The problem was not there with spring-boot 1.3.1 (worked on https://github.com/deepu105/generator-jhipster-entity-audit/issues/4 with 1.3.1 and I was able to edit entites)

Id shown in ui: 56ac73947338fd266c568d64
log looks like it just gets 56 as id (which doesn't work of course)

```
Enter: com.mycompany.myapp.web.rest.BookResource.getBook() with argument[s] = [56]
mycompany.myapp.web.rest.BookResource  : REST request to get Book : 56
Exit: com.mycompany.myapp.web.rest.BookResource.getBook() with result = <404 Not Found,{}>
```

### PR DESCRIPTION
**Pull request by andidev**

### CODE REVIEW

File: entity/templates/src/main/webapp/app/entities/_entity.js [hunk 1]
```diff
@@ -90,7 +90,7 @@ angular.module('<%=angularAppName%>')
             })
             .state('<%= entityInstance %>-management.edit', {
                 parent: '<%= entityInstance %>-management',
-                url: '/{id:int}/edit',
+                url: '/{id:<% if (databaseType == 'sql') { %>int<% } else if (databaseType == 'mongodb') { %>[0-9a-fA-F]{24}<% } else if (databaseType == 'cassandra') { %>[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}<% } %>}/edit',
```
Comment (deepu105) [inline entity/templates/src/main/webapp/app/entities/_entity.js]: @andidev may I suggest doing the conditional in the entity/index.js and assign to a var `this.idType` and then just assign it here?  It would be more efficient and less ugly.

Infact we should try to move more logic from templates to main js

Comment (andidev) [inline entity/templates/src/main/webapp/app/entities/_entity.js]: Yes good point! I'll fix this ASAP.
