### PR TITLE
Mongo reserved keywords

### LINKED ISSUE #2515: Creating an entity called Document when using mongodb leads to broken Application
Basically the Problem is this. When you create an Entity called Document and use MongoDB at the same time the keyword Document is used twice in the same java file once like
import org.springframework.data.mongodb.core.mapping.Document;
and once for the class. which makes it not working. It shouldnt be allowed to create an entity called document in the first place and there should be a message with an error
Basically the error is: Document is already defined in this compilation unit

### PR DESCRIPTION
**Pull request by atomfrede**
It just contains ``DOCUMENT`` right now to fix #2515, we need to agree on the complete list of reserved keywords for mongodb

### CODE REVIEW

File: entity/index.js [hunk 1]
```diff
@@ -158,6 +163,8 @@ EntityGenerator.prototype.askForFields = function askForFields() {
                     return 'Your field name cannot contain a Oracle reserved keyword';
                 } else if (prodDatabaseType == 'oracle' && input.length > 30) {
                     return 'The field name cannot be of more than 30 characters';
+                } else if (prodDatabaseType == 'mongo' && reservedWords_Mongo.indexOf(input.toUpperCase()) != -1) {
```
Comment (pascalgrimaud) [inline entity/index.js]: it should be 'mongodb', instead of 'mongo'
