### PR TITLE
Wrong config for microservices in .yo-rc.json

### LINKED ISSUE #13412: Not used config stored in .yo-rc.json
##### **Overview of the issue**

When generating a **microservice** application, there are some properties in `.yo-rc.json` which are incorrect:

```
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true
```

##### **Motivation for or Use Case**

As there is no front part, these properties should not be here.

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/18-micro
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "microservice",
    "baseName": "jhipster",
    "jhipsterVersion": "7.0.0-beta.0",
    "skipClient": true,
    "skipUserManagement": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1609832735305,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "serviceDiscoveryType": "eureka",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8081",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "languages": ["fr"],
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.30.0

node: v14.15.3

npm: 6.14.9

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.27.3, build 4092ae5d

INFO! Congratulations, JHipster execution is complete!

### PR DESCRIPTION
**Pull request by qmonmert**
Fix #13412 

---

Please make sure the below checklist is followed for Pull Requests.

-   [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [x] Tests are added where necessary
-   [x] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/generator-base.js [hunk 1]
```diff
@@ -2606,7 +2607,7 @@ templates: ${JSON.stringify(existingTemplates, null, 2)}`;
         return { ...defaultAppTypeConfig, ...defaultConfig };
     }
 
-    setConfigDefaults(defaults = defaultConfig) {
+    setConfigDefaults(defaults = this.jhipsterConfig.applicationType !== 'microservice' ? defaultConfig : defaultConfigMicroservice) {
```
Comment (Tcharl) [inline generators/generator-base.js:2610]: const { MONOLITH, MICROSERVICE, GATEWAY, UAA } = require('./application-types');

this.jhipsterConfig.applicationType !== MICROSERVICE

Comment (qmonmert) [reply generators/generator-base.js:2610]: yes you're right, I update that

**Review by mshima — APPROVED** [review]
