### PR TITLE
Fix for Console error in Angular x client #5985

### LINKED ISSUE #5985: Console error in Angular x client
##### **Overview of the issue**

The following console error is thrown when create entity dialog is opened in an angular app generated. Doesnt seem to cause any issue in functionality though, everything seems to work fine
```
BankAccountDialogComponent.html:1 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'jh4TestApp.bankAccount.home.createOrEditLabel'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at viewDebugError (vendor.dll.js:9018)
    at expressionChangedAfterItHasBeenCheckedError (vendor.dll.js:8996)
    at checkBindingNoChanges (vendor.dll.js:9160)
    at checkNoChangesNodeInline (vendor.dll.js:13013)
    at checkNoChangesNode (vendor.dll.js:12987)
    at debugCheckNoChangesNode (vendor.dll.js:13762)
    at debugCheckDirectivesFn (vendor.dll.js:13664)
    at Object.View_BankAccountDialogComponent_0._co [as updateDirectives] (BankAccountDialogComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (vendor.dll.js:13646)
    at checkNoChangesView (vendor.dll.js:12807)

BankAccountDialogComponent.html:1 ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 9, nodeDef: Object, elDef: Object, elView: Object}
```
Might be related to https://github.com/angular/angular/issues/17572

##### **Reproduce the error**

Create an app with given config (Just 1 entity is sufficient I guess), run `./mvnw` and open `localhost:8080` and go to an entity. Open entity create dialog and look at console

##### **Related issues**

https://github.com/angular/angular/issues/17572

##### **Suggest a Fix**

Not sure

##### **JHipster Version(s)**

master

##### **JHipster Version(s)**

```
jh-4-test@0.0.0 /home/deepu/workspace/temp/jh4test
└─┬ generator-jhipster@4.5.6  -> /home/deepu/workspace/jhipster/generator-jhipster
  └── UNMET PEER DEPENDENCY eslint@4.1.0 extraneous

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "jh4test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "afc8cb1c9375cae7b67dac3ba1abc4599d9e2d35",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-tw",
      "fa"
    ]
  }
}
```

<details>
<summary>
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
</summary>
<pre>
BankAccount.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login"
        },
        {
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "bankAccount"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bankNumber",
            "fieldType": "Integer"
        },
        {
            "fieldName": "agencyNumber",
            "fieldType": "Long"
        },
        {
            "fieldName": "lastOperationDuration",
            "fieldType": "Float"
        },
        {
            "fieldName": "meanOperationDuration",
            "fieldType": "Double"
        },
        {
            "fieldName": "balance",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "openingDay",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "lastOperationDate",
            "fieldType": "Instant"
        },
        {
            "fieldName": "active",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "accountType",
            "fieldType": "BankAccountType",
            "fieldValues": "CHECKING,SAVINGS,LOAN"
        },
        {
            "fieldName": "attachment",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "description",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        }
    ],
    "changelogDate": "20150805124838",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}

```

EntityWithDTO.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "emma",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123735",
    "entityTableName": "entity_with_dto",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "no"
}

```

EntityWithPagination.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "nathan",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123738",
    "entityTableName": "entity_with_pagination",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}

```

EntityWithPaginationAndDTO.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "lea",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123743",
    "entityTableName": "entity_with_pagination_and_dto",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "no"
}

```

EntityWithServiceClass.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "zoe",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123736",
    "entityTableName": "entity_with_service_class",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}

```

EntityWithServiceClassAndDTO.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "lucas",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123741",
    "entityTableName": "entity_with_service_class_and_dto",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceClass"
}

```

EntityWithServiceClassAndPagination.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "enzo",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123739",
    "entityTableName": "entity_with_service_class_and_pagination",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}

```

EntityWithServiceClassPaginationAndDTO.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "lena",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123744",
    "entityTableName": "entity_with_service_class_pagination_and_dto",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceClass"
}

```

EntityWithServiceImpl.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "clara",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123737",
    "entityTableName": "entity_with_service_impl",
    "dto": "no",
    "pagination": "no",
    "service": "serviceImpl"
}

```

EntityWithServiceImplAndDTO.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "louis",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123742",
    "entityTableName": "entity_with_service_impl_and_dto",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}

```

EntityWithServiceImplAndPagination.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "hugo",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123740",
    "entityTableName": "entity_with_service_impl_and_pagination",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceImpl"
}

```

EntityWithServiceImplPaginationAndDTO.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "theo",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160806123745",
    "entityTableName": "entity_with_service_impl_pagination_and_dto",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl"
}

```

FieldTestEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "stringTom",
            "fieldType": "String"
        },
        {
            "fieldName": "stringRequiredTom",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "stringMinlengthTom",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldName": "stringMaxlengthTom",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "stringPatternTom",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "integerTom",
            "fieldType": "Integer"
        },
        {
            "fieldName": "integerRequiredTom",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "integerMinTom",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "integerMaxTom",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "longTom",
            "fieldType": "Long"
        },
        {
            "fieldName": "longRequiredTom",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "longMinTom",
            "fieldType": "Long",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "longMaxTom",
            "fieldType": "Long",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "floatTom",
            "fieldType": "Float"
        },
        {
            "fieldName": "floatRequiredTom",
            "fieldType": "Float",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "floatMinTom",
            "fieldType": "Float",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "floatMaxTom",
            "fieldType": "Float",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "doubleRequiredTom",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "doubleMinTom",
            "fieldType": "Double",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "doubleMaxTom",
            "fieldType": "Double",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "bigDecimalRequiredTom",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bigDecimalMinTom",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "bigDecimalMaxTom",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "localDateTom",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "localDateRequiredTom",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "instantTom",
            "fieldType": "Instant"
        },
        {
            "fieldName": "instanteRequiredTom",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "zonedDateTimeTom",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "zonedDateTimeRequiredTom",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "booleanTom",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "booleanRequiredTom",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enumTom",
            "fieldType": "EnumFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3"
        },
        {
            "fieldName": "enumRequiredTom",
            "fieldType": "EnumRequiredFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "byteImageRequiredTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMinbytesTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteImageMaxbytesTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteAnyTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "byteAnyRequiredTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteAnyMinbytesTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteAnyMaxbytesTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteTextTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "byteTextRequiredTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteTextMinbytesTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteTextMaxbytesTom",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        }
    ],
    "changelogDate": "20160208184031",
    "dto": "no",
    "service": "no",
    "pagination": "no"
}

```

FieldTestInfiniteScrollEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "stringHugo",
            "fieldType": "String"
        },
        {
            "fieldName": "stringRequiredHugo",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "stringMinlengthHugo",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldName": "stringMaxlengthHugo",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "stringPatternHugo",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "integerHugo",
            "fieldType": "Integer"
        },
        {
            "fieldName": "integerRequiredHugo",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "integerMinHugo",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "integerMaxHugo",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "longHugo",
            "fieldType": "Long"
        },
        {
            "fieldName": "longRequiredHugo",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "longMinHugo",
            "fieldType": "Long",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "longMaxHugo",
            "fieldType": "Long",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "floatHugo",
            "fieldType": "Float"
        },
        {
            "fieldName": "floatRequiredHugo",
            "fieldType": "Float",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "floatMinHugo",
            "fieldType": "Float",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "floatMaxHugo",
            "fieldType": "Float",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "doubleRequiredHugo",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "doubleMinHugo",
            "fieldType": "Double",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "doubleMaxHugo",
            "fieldType": "Double",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "bigDecimalRequiredHugo",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bigDecimalMinHugo",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "bigDecimalMaxHugo",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "localDateHugo",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "localDateRequiredHugo",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "instantHugo",
            "fieldType": "Instant"
        },
        {
            "fieldName": "instanteRequiredHugo",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "zonedDateTimeHugo",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "zonedDateTimeRequiredHugo",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "booleanHugo",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "booleanRequiredHugo",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enumHugo",
            "fieldType": "EnumFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3"
        },
        {
            "fieldName": "enumRequiredHugo",
            "fieldType": "EnumRequiredFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "byteImageRequiredHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMinbytesHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteImageMaxbytesHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteAnyHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "byteAnyRequiredHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteAnyMinbytesHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteAnyMaxbytesHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteTextHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "byteTextRequiredHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteTextMinbytesHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteTextMaxbytesHugo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        }
    ],
    "changelogDate": "20160208184031",
    "dto": "no",
    "service": "no",
    "pagination": "infinite-scroll"
}

```

FieldTestMapstructEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "stringEva",
            "fieldType": "String"
        },
        {
            "fieldName": "stringRequiredEva",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "stringMinlengthEva",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldName": "stringMaxlengthEva",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "stringPatternEva",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "integerEva",
            "fieldType": "Integer"
        },
        {
            "fieldName": "integerRequiredEva",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "integerMinEva",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "integerMaxEva",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "longEva",
            "fieldType": "Long"
        },
        {
            "fieldName": "longRequiredEva",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "longMinEva",
            "fieldType": "Long",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "longMaxEva",
            "fieldType": "Long",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "floatEva",
            "fieldType": "Float"
        },
        {
            "fieldName": "floatRequiredEva",
            "fieldType": "Float",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "floatMinEva",
            "fieldType": "Float",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "floatMaxEva",
            "fieldType": "Float",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "doubleRequiredEva",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "doubleMinEva",
            "fieldType": "Double",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "doubleMaxEva",
            "fieldType": "Double",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "bigDecimalRequiredEva",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bigDecimalMinEva",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "bigDecimalMaxEva",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "localDateEva",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "localDateRequiredEva",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "instantEva",
            "fieldType": "Instant"
        },
        {
            "fieldName": "instanteRequiredEva",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "zonedDateTimeEva",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "zonedDateTimeRequiredEva",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "booleanEva",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "booleanRequiredEva",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enumEva",
            "fieldType": "EnumFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3"
        },
        {
            "fieldName": "enumRequiredEva",
            "fieldType": "EnumRequiredFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "byteImageRequiredEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMinbytesEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteImageMaxbytesEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteAnyEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "byteAnyRequiredEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteAnyMinbytesEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteAnyMaxbytesEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteTextEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "byteTextRequiredEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteTextMinbytesEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteTextMaxbytesEva",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        }
    ],
    "changelogDate": "20160208184031",
    "dto": "mapstruct",
    "service": "no",
    "pagination": "no"
}

```

FieldTestPagerEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "stringJade",
            "fieldType": "String"
        },
        {
            "fieldName": "stringRequiredJade",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "stringMinlengthJade",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldName": "stringMaxlengthJade",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "stringPatternJade",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "integerJade",
            "fieldType": "Integer"
        },
        {
            "fieldName": "integerRequiredJade",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "integerMinJade",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "integerMaxJade",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "longJade",
            "fieldType": "Long"
        },
        {
            "fieldName": "longRequiredJade",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "longMinJade",
            "fieldType": "Long",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "longMaxJade",
            "fieldType": "Long",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "floatJade",
            "fieldType": "Float"
        },
        {
            "fieldName": "floatRequiredJade",
            "fieldType": "Float",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "floatMinJade",
            "fieldType": "Float",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "floatMaxJade",
            "fieldType": "Float",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "doubleRequiredJade",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "doubleMinJade",
            "fieldType": "Double",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "doubleMaxJade",
            "fieldType": "Double",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "bigDecimalRequiredJade",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bigDecimalMinJade",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "bigDecimalMaxJade",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "localDateJade",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "localDateRequiredJade",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "instantJade",
            "fieldType": "Instant"
        },
        {
            "fieldName": "instanteRequiredJade",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "zonedDateTimeJade",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "zonedDateTimeRequiredJade",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "booleanJade",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "booleanRequiredJade",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enumJade",
            "fieldType": "EnumFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3"
        },
        {
            "fieldName": "enumRequiredJade",
            "fieldType": "EnumRequiredFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "byteImageRequiredJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMinbytesJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteImageMaxbytesJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteAnyJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "byteAnyRequiredJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteAnyMinbytesJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteAnyMaxbytesJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteTextJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "byteTextRequiredJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteTextMinbytesJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteTextMaxbytesJade",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        }
    ],
    "changelogDate": "20160208184031",
    "dto": "no",
    "service": "no",
    "pagination": "pager"
}

```

FieldTestPaginationEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "stringAlice",
            "fieldType": "String"
        },
        {
            "fieldName": "stringRequiredAlice",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "stringMinlengthAlice",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldName": "stringMaxlengthAlice",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "stringPatternAlice",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "integerAlice",
            "fieldType": "Integer"
        },
        {
            "fieldName": "integerRequiredAlice",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "integerMinAlice",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "integerMaxAlice",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "longAlice",
            "fieldType": "Long"
        },
        {
            "fieldName": "longRequiredAlice",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "longMinAlice",
            "fieldType": "Long",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "longMaxAlice",
            "fieldType": "Long",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "floatAlice",
            "fieldType": "Float"
        },
        {
            "fieldName": "floatRequiredAlice",
            "fieldType": "Float",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "floatMinAlice",
            "fieldType": "Float",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "floatMaxAlice",
            "fieldType": "Float",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "doubleRequiredAlice",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "doubleMinAlice",
            "fieldType": "Double",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "doubleMaxAlice",
            "fieldType": "Double",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "bigDecimalRequiredAlice",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bigDecimalMinAlice",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "bigDecimalMaxAlice",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "localDateAlice",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "localDateRequiredAlice",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "instantAlice",
            "fieldType": "Instant"
        },
        {
            "fieldName": "instanteRequiredAlice",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "zonedDateTimeAlice",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "zonedDateTimeRequiredAlice",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "booleanAlice",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "booleanRequiredAlice",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enumAlice",
            "fieldType": "EnumFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3"
        },
        {
            "fieldName": "enumRequiredAlice",
            "fieldType": "EnumRequiredFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "byteImageRequiredAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMinbytesAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteImageMaxbytesAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteAnyAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "byteAnyRequiredAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteAnyMinbytesAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteAnyMaxbytesAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteTextAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "byteTextRequiredAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteTextMinbytesAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteTextMaxbytesAlice",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        }
    ],
    "changelogDate": "20160208184031",
    "dto": "no",
    "service": "no",
    "pagination": "pagination"
}

```

FieldTestServiceClassEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "stringBob",
            "fieldType": "String"
        },
        {
            "fieldName": "stringRequiredBob",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "stringMinlengthBob",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldName": "stringMaxlengthBob",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "stringPatternBob",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "integerBob",
            "fieldType": "Integer"
        },
        {
            "fieldName": "integerRequiredBob",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "integerMinBob",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "integerMaxBob",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "longBob",
            "fieldType": "Long"
        },
        {
            "fieldName": "longRequiredBob",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "longMinBob",
            "fieldType": "Long",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "longMaxBob",
            "fieldType": "Long",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "floatBob",
            "fieldType": "Float"
        },
        {
            "fieldName": "floatRequiredBob",
            "fieldType": "Float",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "floatMinBob",
            "fieldType": "Float",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "floatMaxBob",
            "fieldType": "Float",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "doubleRequiredBob",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "doubleMinBob",
            "fieldType": "Double",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "doubleMaxBob",
            "fieldType": "Double",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "bigDecimalRequiredBob",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bigDecimalMinBob",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "bigDecimalMaxBob",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "localDateBob",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "localDateRequiredBob",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "instantBob",
            "fieldType": "Instant"
        },
        {
            "fieldName": "instanteRequiredBob",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "zonedDateTimeBob",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "zonedDateTimeRequiredBob",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "booleanBob",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "booleanRequiredBob",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enumBob",
            "fieldType": "EnumFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3"
        },
        {
            "fieldName": "enumRequiredBob",
            "fieldType": "EnumRequiredFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "byteImageRequiredBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMinbytesBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteImageMaxbytesBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteAnyBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "byteAnyRequiredBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteAnyMinbytesBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteAnyMaxbytesBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteTextBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "byteTextRequiredBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteTextMinbytesBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteTextMaxbytesBob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        }
    ],
    "changelogDate": "20160208184031",
    "dto": "no",
    "service": "serviceClass",
    "pagination": "no"
}

```

FieldTestServiceImplEntity.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "stringMika",
            "fieldType": "String"
        },
        {
            "fieldName": "stringRequiredMika",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "stringMinlengthMika",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength"
            ],
            "fieldValidateRulesMinlength": 0
        },
        {
            "fieldName": "stringMaxlengthMika",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "stringPatternMika",
            "fieldType": "String",
            "fieldValidateRules": [
                "pattern"
            ],
            "fieldValidateRulesPattern": "^[a-zA-Z0-9]*$",
            "fieldValidateRulesPatternJava": "^[a-zA-Z0-9]*$"
        },
        {
            "fieldName": "integerMika",
            "fieldType": "Integer"
        },
        {
            "fieldName": "integerRequiredMika",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "integerMinMika",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "integerMaxMika",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "longMika",
            "fieldType": "Long"
        },
        {
            "fieldName": "longRequiredMika",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "longMinMika",
            "fieldType": "Long",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "longMaxMika",
            "fieldType": "Long",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "floatMika",
            "fieldType": "Float"
        },
        {
            "fieldName": "floatRequiredMika",
            "fieldType": "Float",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "floatMinMika",
            "fieldType": "Float",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "floatMaxMika",
            "fieldType": "Float",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "doubleRequiredMika",
            "fieldType": "Double",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "doubleMinMika",
            "fieldType": "Double",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "doubleMaxMika",
            "fieldType": "Double",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "bigDecimalRequiredMika",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "bigDecimalMinMika",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "min"
            ],
            "fieldValidateRulesMin": 0
        },
        {
            "fieldName": "bigDecimalMaxMika",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "max"
            ],
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "localDateMika",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "localDateRequiredMika",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "instantMika",
            "fieldType": "Instant"
        },
        {
            "fieldName": "instanteRequiredMika",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "zonedDateTimeMika",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "zonedDateTimeRequiredMika",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "booleanMika",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "booleanRequiredMika",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "enumMika",
            "fieldType": "EnumFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3"
        },
        {
            "fieldName": "enumRequiredMika",
            "fieldType": "EnumRequiredFieldClass",
            "fieldValues": "ENUM_VALUE_1,ENUM_VALUE_2,ENUM_VALUE_3",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "byteImageRequiredMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteImageMinbytesMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteImageMaxbytesMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteAnyMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "byteAnyRequiredMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteAnyMinbytesMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteAnyMaxbytesMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        },
        {
            "fieldName": "byteTextMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text"
        },
        {
            "fieldName": "byteTextRequiredMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "byteTextMinbytesMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "minbytes"
            ],
            "fieldValidateRulesMinbytes": 0
        },
        {
            "fieldName": "byteTextMaxbytesMika",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "maxbytes"
            ],
            "fieldValidateRulesMaxbytes": 10000
        }
    ],
    "changelogDate": "20160208184031",
    "dto": "no",
    "service": "serviceImpl",
    "pagination": "no"
}

```

Label.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "many-to-many",
            "ownerSide": false,
            "otherEntityRelationshipName": "label"
        }
    ],
    "fields": [
        {
            "fieldName": "labelName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "3"
        }
    ],
    "changelogDate": "20150805124936",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}

```

Operation.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "bankAccount",
            "otherEntityName": "bankAccount",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipName": "label",
            "otherEntityName": "label",
            "relationshipType": "many-to-many",
            "otherEntityField": "labelName",
            "ownerSide": true,
            "otherEntityRelationshipName": "operation"
        }
    ],
    "fields": [
        {
            "fieldName": "date",
            "fieldType": "Instant",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "amount",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150805125054",
    "dto": "no",
    "service": "no",
    "pagination": "infinite-scroll"
}


```
</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.9.4

node: v6.10.3

npm: 3.10.10

bower: 1.8.0

gulp:
[17:27:34] CLI version 1.3.0

yeoman: 1.8.5

yarn: 0.24.6

Docker version 17.05.0-ce, build 89658be

##### **Browsers and Operating System**

Linux: Fedora 25, chrome latest

- [ x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by aleris**
Beside eliminating the console error (see comment in #5985), also cleaned up the return value of open method in _entity-popup.service.ts, now using a promise, and removed unused modalRef component properties in _entity-management-delete-dialog.component.ts and _entity-management-dialog.component.ts.

Fix #5985

### CODE REVIEW

File: generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts [hunk 1]
```diff
@@ -204,7 +204,6 @@ export class <%= entityAngularName %>DialogComponent implements OnInit {
 })
 export class <%= entityAngularName %>PopupComponent implements OnInit, OnDestroy {
 
-    modalRef: NgbModalRef;
```
Comment (aleris) [inline generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts]: removed as it was not used

File: generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-popup.service.ts [hunk 2]
```diff
@@ -33,7 +33,8 @@ _%>
 
 @Injectable()
 export class <%= entityAngularName %>PopupService {
-    private isOpen = false;
```
Comment (aleris) [inline generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-popup.service.ts]: keep a reference to NgbModalRef instead, the dialog is opend if it is not null

File: generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-popup.service.ts [hunk 3]
```diff
@@ -42,38 +43,47 @@ export class <%= entityAngularName %>PopupService {
...
-                    };
-                }
-                        <%_ } _%>
-                        <%_ if (['Instant', 'ZonedDateTime'].includes(fields[idx].fieldType)) { _%>
-                <%= entityInstance %>.<%=fields[idx].fieldName%> = this.datePipe
-                    .transform(<%= entityInstance %>.<%=fields[idx].fieldName%>, 'yyyy-MM-ddThh:mm');
-                        <%_ } _%>
-                <%_ } _%>
-                <%_ } _%>
-                this.<%= entityInstance %>ModalRef(component, <%= entityInstance %>);
```
Comment (aleris) [inline generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-popup.service.ts]: was not returning anything

File: generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts (hunk 1 above)
Comment (deepu105) [inline generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts]: Did you check the cancel button and close icon on the model? I remember this was needed by one of that to work, but it was long time ago may be things changed

Comment (deepu105) [inline generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts]: ok seems to work fine :)

**Comment by aleris** [comment]
Maybe the best way to handle popups would be to not use them for edit or create. Of course the usage of popups is also a matter of preference. However, the popup service is probably best to be used from a event call or explicit user action and forcing the usage pattern would probably bring other problems. So the suggestion would be to use normal pages for create and edit, not popups, and only use a popup for delete confirmation, where a route doesn't really have sense any way.
