### PR TITLE
fix: Replace asterisk with UUID and conditional inject internal client

### LINKED ISSUE #20147: Insecure and misleading default realm config in jhipster-realm.json
##### **Overview of the issue**

The default jhipster-realm.json comes with some defaults that are outdated and make it hard to use for multi-tenancy.
Moreover secrets are exported as ******* which creates false sense of security as would expect a lot of deployments in production to keep them that way making them vulnerable for attacks.

##### **Motivation for or Use Case**

I would like to be able to easily rename the realm in jhipster-realm.json
And be able to regenerate all secrets so that importing the realm in production be secure by default.

I guide with all this would be great in my opinion.

##### **Reproduce the error**

Import the default realm.

Check that it can be accessed using client-secret: `**********` (10 asterisks)

Edit: There is also a client named "internal" specifically created by jhipster (which make it misleading) used only by micro-services (but always present in all configs), that in my opinion should be removed when not required. it's secret two `internal` should be regenerated and documented for change before production.

##### **Suggest a Fix**
1. recreate the realm/roles... manually
2. export the realm using, the script below and whenever and upgrade is made
```
docker exec docker_keycloak_1 /opt/keycloak/bin/kc.sh export --realm jhipster --users=realm_file --file /tmp/jhipster-realm.json
docker cp docker_keycloak_1:/tmp/jhipster-realm.json ./src/main/docker/realm-config/jhipster-realm.json
```
3. Document what should change before moving to production.
4. Optional: Document what should change for multi tenancy. (not all jhipster references should be changed, roles/claims for example should still be called jhipster) but realm name, redirectURIs... should change.

##### **JHipster Version(s)**

7.9.3

- [X] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by vishal423**
Closes #20147 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

### CODE REVIEW

File: generators/docker-compose/generator.mjs [hunk 1]
```diff
@@ -143,6 +145,8 @@ export default class DockerComposeGenerator extends BaseDockerGenerator {
       setAppsYaml() {
         this.appsYaml = [];
         this.keycloakRedirectUris = '';
+        this.applicationTypeGateway = false;
+        this.faker = faker;
```
Comment (mshima) [inline generators/docker-compose/generator.mjs:149]: We are trying to avoid method calls inside templates
```suggestion
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 2]
```diff
@@ -543,7 +545,7 @@
       "enabled": true,
       "alwaysDisplayInConsole": false,
       "clientAuthenticatorType": "client-secret",
-      "secret": "**********",
+      "secret": "<%= faker.datatype.uuid() %>",
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:548]:
```suggestion
      "secret": "<%= keycloakSecrets[0] %>",
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 3]
```diff
@@ -587,7 +589,7 @@
...
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:592]:
```suggestion
      "secret": "<%= keycloakSecrets[1] %>",
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 4]
```diff
@@ -640,7 +642,7 @@
...
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:645]:
```suggestion
      "secret": "<%= keycloakSecrets[2] %>",
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 5]
```diff
@@ -680,7 +682,7 @@
...
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:685]:
```suggestion
      "secret": "<%= keycloakSecrets[3] %>",
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 6]
```diff
@@ -105,7 +105,9 @@
       }
     ],
     "client": {
+<%_ if (applicationTypeGateway) { _%>
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:108]:
```suggestion
<%_ if (includesApplicationTypeGateway) { _%>
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 7]
```diff
@@ -711,7 +713,7 @@
         "offline_access",
         "microprofile-jwt"
       ]
-    },
+    },<% if (applicationTypeGateway) { %>
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:716]:
```suggestion
    },
<%_ if (includesApplicationTypeGateway) { _%>
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 8]
```diff
@@ -810,7 +812,7 @@
         "offline_access",
         "microprofile-jwt"
       ]
-    },
+    },<% } %>
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:815]:
```suggestion
    },
<%_ } _%>
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 9]
```diff
@@ -943,7 +945,7 @@
       "enabled": true,
       "alwaysDisplayInConsole": false,
       "clientAuthenticatorType": "client-secret",
-      "secret": "**********",
+      "secret": "<%= faker.datatype.uuid() %>",
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:948]:
```suggestion
      "secret": "<%= keycloakSecrets[4] %>",
```

File: generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs [hunk 10]
```diff
@@ -985,7 +987,7 @@
...
```
Comment (mshima) [inline generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs:990]:
```suggestion
      "secret": "<%= keycloakSecrets[5] %>",
```

File: generators/docker/generator.mjs [hunk 11]
```diff
@@ -83,9 +85,10 @@ export default class DockerGenerator extends BaseApplicationGenerator {
   get writing() {
     return this.asWritingTaskGroup({
       async writeDockerFiles({ application }) {
+        faker.seed(stringHashCode(application.baseName));
```
Comment (mshima) [inline generators/docker/generator.mjs:88]: Can be moved to preparing.
```suggestion
        if (application.authenticationTypeOauth2) {
          faker.seed(stringHashCode(application.baseName));
          application.keycloakSecrets = Array(6).forEach(() => faker.datatype.uuid());
        }
```

File: generators/docker/generator.mjs [hunk 12]
```diff
@@ -83,9 +85,10 @@ export default class DockerGenerator extends BaseApplicationGenerator {
...
         await this.writeFiles({
           sections: dockerFiles,
-          context: application,
+          context: { ...application, faker },
```
Comment (mshima) [inline generators/docker/generator.mjs:91]:
```suggestion
          context: application,
```

File: generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs [hunk 13]
```diff
@@ -543,7 +545,7 @@
       "enabled": true,
       "alwaysDisplayInConsole": false,
       "clientAuthenticatorType": "client-secret",
-      "secret": "**********",
+      "secret": "<%= faker.datatype.uuid() %>",
```
Comment (mshima) [inline generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs:548]:
```suggestion
      "secret": "<%= keycloakSecrets[0] %>",
```

File: generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs [hunk 14]
```diff
@@ -587,7 +589,7 @@
...
```
Comment (mshima) [inline generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs:592]:
```suggestion
      "secret": "<%= keycloakSecrets[1] %>",
```

File: generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs [hunk 15]
```diff
@@ -640,7 +642,7 @@
...
```
Comment (mshima) [inline generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs:645]:
```suggestion
      "secret": "<%= keycloakSecrets[2] %>",
```

File: generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs [hunk 16]
```diff
@@ -680,7 +682,7 @@
...
```
Comment (mshima) [inline generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs:685]:
```suggestion
      "secret": "<%= keycloakSecrets[3] %>",
```

File: generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs [hunk 17]
```diff
@@ -711,7 +713,7 @@
         "offline_access",
         "microprofile-jwt"
       ]
-    },
+    },<% if (applicationTypeGateway) { %>
```
Comment (mshima) [inline generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs:716]:
```suggestion
    },
<%_ if (applicationTypeGateway) { _%>
```

File: generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs [hunk 18]
```diff
@@ -985,7 +987,7 @@
       "enabled": true,
       "alwaysDisplayInConsole": false,
       "clientAuthenticatorType": "client-secret",
-      "secret": "**********",
+      "secret": "<%= faker.datatype.uuid() %>",
```
Comment (mshima) [inline generators/docker/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs:990]:
```suggestion
      "secret": "<%= keycloakSecrets[5] %>",
```

**Review by mshima — COMMENTED** [review]
We should avoid method calls inside templates. This is an ongoing task.
Looks good.

File: generators/docker/generator.mjs [hunk 19]
```diff
@@ -83,6 +85,10 @@ export default class DockerGenerator extends BaseApplicationGenerator {
   get writing() {
     return this.asWritingTaskGroup({
       async writeDockerFiles({ application }) {
+        if (application.authenticationTypeOauth2) {
+          faker.seed(stringHashCode(application.baseName));
+          application.keycloakSecrets = Array(6).forEach(() => faker.datatype.uuid());
```
Comment (mshima) [inline generators/docker/generator.mjs:90]:
```suggestion
          application.keycloakSecrets = new Array(6).forEach(() => faker.datatype.uuid());
```

File: generators/docker-compose/generator.mjs [hunk 20]
```diff
@@ -160,7 +163,14 @@ export default class DockerComposeGenerator extends BaseDockerGenerator {
               })
             );
           }
+          if (appConfig.applicationType === GATEWAY) {
+            this.includesApplicationTypeGateway = true;
+          }
           if (appConfig.applicationType === GATEWAY || appConfig.applicationType === MONOLITH) {
+            if (this.keycloakSecrets === undefined && appConfig.authenticationType === 'oauth2') {
+              faker.seed(stringHashCode(appConfig.baseName));
+              this.keycloakSecrets = Array(6).forEach(() => faker.datatype.uuid());
```
Comment (mshima) [inline generators/docker-compose/generator.mjs:172]:
```suggestion
              this.keycloakSecrets = new Array(6).forEach(() => faker.datatype.uuid());
```

**Review by mshima — APPROVED** [review]

File: generators/docker-compose/generator.mjs [hunk 21]
```diff
@@ -160,7 +163,14 @@ export default class DockerComposeGenerator extends BaseDockerGenerator {
               })
             );
           }
+          if (appConfig.applicationType === GATEWAY) {
+            this.includesApplicationTypeGateway = true;
+          }
           if (appConfig.applicationType === GATEWAY || appConfig.applicationType === MONOLITH) {
+            if (this.keycloakSecrets === undefined && appConfig.authenticationType === 'oauth2') {
+              faker.seed(stringHashCode(appConfig.baseName));
+              this.keycloakSecrets = new Array(6).forEach(() => faker.datatype.uuid());
```
Comment (mshima) [inline generators/docker-compose/generator.mjs:172]:
```suggestion
              this.keycloakSecrets = Array.from(Array(6), () => faker.datatype.uuid());
```

File: generators/docker/generator.mjs [hunk 22]
```diff
@@ -83,6 +85,10 @@ export default class DockerGenerator extends BaseApplicationGenerator {
   get writing() {
     return this.asWritingTaskGroup({
       async writeDockerFiles({ application }) {
+        if (application.authenticationTypeOauth2) {
+          faker.seed(stringHashCode(application.baseName));
+          application.keycloakSecrets = new Array(6).forEach(() => faker.datatype.uuid());
```
Comment (mshima) [inline generators/docker/generator.mjs:90]:
```suggestion
          application.keycloakSecrets = Array.from(Array(6), () => faker.datatype.uuid());
```
