### PR TITLE
Fix React infinite scrolling

### LINKED ISSUE #7927: React - Infinite-scroll loading entities twice after entity update
##### **Overview of the issue**

If Infinite scroll is enabled on an entity, after I update one of them, the FE loads the list twice after an entity update. The first part of the list contains the old entities, the second part contains the first page, containing the UPDATED entity.

##### **Reproduce the error**

I detected the problem in a production like environment (war file build with ./mvnw -Pprod package)

- Load enough entitities to trigger the infinite scroll. 
- Open the entity page and scroll to bottom (trigger the infinite scroll)
- click on edit on the first entity, edit the entity, click on save

The browser opens the entity list page, you can see:
- that the first line hasn't changed
- that the entity list is loaded twice, the second group in the list contains the updated entity

here's the [video](https://drive.google.com/open?id=168CSD8j4hfcvnrjeaisa6P6rrl7-omFM)

##### **Suggest a Fix**
After the HTTP PUT that updates the entitites I can see three subsequent calls to:
- http://localhost:8086/api/employees?page=0&size=20&sort=id,asc&cacheBuster=1530701104820 (returns the old entity)
- http://localhost:8086/api/employees?page=1&size=20&sort=id,asc&cacheBuster=1530701104839 (returns the second page)
- http://localhost:8086/api/employees?cacheBuster=1530701104875 (returns the first page, with the *updated* entities)

##### **JHipster Version(s)**

5.0.1

##### **JHipster Version(s)**

```
humanresources@0.0.0 C:\Users\ecostanzi\dev\learn\jhipster\jhipster5-react-monolith
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.intesys.lab",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.1",
    "applicationType": "monolith",
    "baseName": "humanresources",
    "packageName": "it.intesys.lab",
    "packageFolder": "it/intesys/lab",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mariadb",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "react",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "it"
    ]
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Region (region) {
  regionName String
}
entity Country (country) {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location (location) {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department (department) {
  departmentName String required
}
/**
 * Task entity.
 * @author The JHipster team.
 */
entity Task (task) {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee (employee) {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate Instant,
  salary Long,
  commissionPct Long
}
entity Job (job) {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory (job_history) {
  startDate Instant,
  endDate Instant,
  language Language
}

enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region(regionName)} to Region,
  Location{country(countryName)} to Country,
  Department{location(city)} to Location,
  JobHistory{job(jobTitle)} to Job,
  JobHistory{department(departmentName)} to Department,
  JobHistory{employee(email)} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee{department(departmentName)},
  Employee{job} to Job{employee(email)}
}
relationship ManyToOne {
  Employee{manager(email)} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

dto Region, Country, Location, Department, Task, Employee, Job, JobHistory with mapstruct
service Region, Country, Location, Department, Task, Employee, Job, JobHistory with serviceImpl
paginate Employee, JobHistory with infinite-scroll
paginate Job with pagination

</pre>
</details>

##### **Environment and Tools**

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

git version 2.12.2.windows.2

node: v8.11.3

npm: 5.6.0

yeoman: 1.8.5

yarn: 1.7.0

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 7641a569
`

##### **Browsers and Operating System**
Chrome

- [*] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by chrisdns**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs [hunk 1]
```diff
@@ -42,6 +42,7 @@ export class <%= entityReactName %>DeleteDialog extends React.Component<I<%= ent
   handleClose = event => {
     event.stopPropagation();
     this.props.history.goBack();
+    window.location.reload();
```
Comment (deepu105) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs]: dont do this(since its not nice in a single page app, we do not want to propogate bad practices) instead just call the getAll action here and see if that helps, so that the store gets updated and list automatically gets updated.

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs [hunk 2]
```diff
@@ -230,6 +230,9 @@ export const createEntity: ICrudPutAction<I<%= entityReactName %>> = entity => a
     type: ACTION_TYPES.CREATE_<%= entityActionName %>,
     payload: axios.post(apiUrl, cleanEntity(entity))
   });
+  <%_ if (pagination === 'infinite-scroll') { _%>
+    dispatch(reset());
```
Comment (deepu105) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs]: why are these calls needed?

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs (hunk 1 above)
Comment (deepu105) [reply generators/entity-client/templates/react/src/main/webapp/app/entities/entity-delete-dialog.tsx.ejs]: but seems like the action is called after the delete method and that should have updated the store.

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs [hunk 3]
```diff
@@ -249,6 +255,9 @@ export const deleteEntity: ICrudDeleteAction<I<%= entityReactName %>> = id => as
     type: ACTION_TYPES.DELETE_<%= entityActionName %>,
     payload: axios.delete(requestUrl)
   });
+  <%_ if (pagination === 'infinite-scroll') { _%>
+    dispatch(reset());
+  <%_ } _%>
   dispatch(getEntities());
```
Comment (deepu105) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity.reducer.ts.ejs]: this should have reloaded entity list. This needs to be investigated

File: generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs [hunk 4]
```diff
@@ -193,7 +197,6 @@ export class <%= entityReactName %> extends React.Component<I<%= entityReactName
           <InfiniteScroll pageStart={this.state.activePage}
                           loadMore={this.handleLoadMore}
                           hasMore={this.state.activePage <= this.props.links.last}
-                          loader={<div className="loader">Loading ...</div>}
```
Comment (deepu105) [inline generators/entity-client/templates/react/src/main/webapp/app/entities/entity.tsx.ejs]: Actually, it is nice to show some indication that things are loading, why did you remove this?

**Comment by chrisdns** [comment]
I applied the changes and removed bad practices, the issue reported seems to be fixed now but there is still one bug I did not figure out ; when we scroll down to next page, and then try to delete a row, the list gets updated but the infinite scrolling cannot be triggered anymore except if we refresh the page

**Comment by chrisdns** [comment]
No it is done

**Comment by deepu105** [comment]
Wjat about the refresh on delete issue you mentioned? Can you create a ticket to track that

**Comment by chrisdns** [comment]
Yes I will, I'll try to fix that but that's quite strange, for the moment i don't see what is causing this issue whereas there is no problem with editing or creating
